### ISSUE TITLE
Working with large files

### ISSUE THREAD

**Issue by chicag0** [thephpleague/csv#100]
I'm trying to read a CSV file with 150k rows.  My server isn't massive so I am trying to do this is a way that handles memory properly, I can't just return all rows as an array.

What is the best way to loop over this?  I tried using a loop like this: `foreach ($data as $lineIndex => $row)` but ran into memory issues.

I can create a PHP loop and then use ->fetchOne() row at a time, but I believe this 'rewinds' the file after every read, so if I am grabbing row 140,000 it takes 10 seconds to return the data.  Any ideas for processing large files?

I am okay with storing the last line read in my cache, and then using ->fetchOne but is there a way to prevent the long seek delay?

**Comment by nyamsprod** [comment]
you should use Reader::query($callable) method directly it's the best option for now

**Comment by chicag0** [comment]
Any chance you can provide an example how I can use this?

**Comment by nyamsprod** [comment]
you can see one in the examples or [in the documentation](http://csv.thephpleague.com/reading/#fetching-csv-data)
