### ISSUE TITLE
How to use it with Symfony2 ?

### ISSUE THREAD

**Issue by ychoucha** [thephpleague/csv#101]
Hello can we have a way to use it with symfony2 

please

**Comment by nyamsprod** [comment]
what's preventing you from using it with Symfony2 ?

**Comment by nyamsprod** [comment]
http://symfony.com/doc/current/components/class_loader/psr4_class_loader.html 
according to the symfony documentation there's nothing to do. If you are using composer then the library is already present and loaded you just need to call it in your symfony based script
