### ISSUE TITLE
Enclosure should be remove when stripping BOM sequence

### ISSUE THREAD

**Issue by onema** [thephpleague/csv#102]
I have the following code:

```php
$csv = '﻿"Paret name","Child name","Title"
"parent 1","child 1","title"
"parent 2","child 2","title"
';
$csvReader = Reader::createFromString($csv);
$assoc = $csvReader->fetchAssoc();
```

And the associative array returned by `fetchAssoc` looks like this:

```
Array (
    [0] => Array (
            ["Paret name"] => parent 1
            [Child name] => child 1
            [Title] => title
        )
    [1] => Array (
            ["Paret name"] => parent 2
            [Child name] => child 2
            [Title] => title
        )
)
```

Where `parent name` contains the quotes `"`. At fist, I thought there was something wrong with the `fetchAssoc` method but after close inspection I realized that the file I was getting the CSV from was `UTF-8` with BOM. Then I try to set `stripBom` to `true`, but it didn't work as I was still getting the same output. 

```php
$csv = '﻿"Paret name","Child name","Title"
"parent 1","child 1","title"
"parent 2","child 2","title"
';
$csvReader = Reader::createFromString($csv);
$csvReader->stripBom(true);
$assoc = $csvReader->fetchAssoc();
```
The only way for me to get it to work was to manually strip the BOM before creating the reader:

```
$csv = preg_replace('/\x{FEFF}/u', '', $csv);
```

- Am I using the reader correctly? 
- Should I expect the reader to automatically remove the BOM for me if `stripBom` is set to true?

**Comment by nyamsprod** [comment]
@onema thanks for reporting the bug. A patch was made available on the master branch. After review and testing a patch release will be made next week. In the meantime you can test that the dev-master branch fix works for you

**Comment by onema** [comment]
Awesome! will update and be testing it today.

**Comment by onema** [comment]
I just tested the master branch and `fetch*` methods work as long as I call `stripBom(true)` before each call. It threw me off a bit, but looking at the [code](https://github.com/thephpleague/csv/blob/master/src/Modifier/QueryFilter.php#L259) it seems this is the intended behavior; I didn't see anything related to this in the [docs](http://csv.thephpleague.com/query-filtering/).

```php 
$csv = '﻿"Paret name","Child name","Title"
"parent 1","child 1","title"
"parent 2","child 2","title"
';
$csvReader = Reader::createFromString($csv);
$csvReader->stripBom(true);
$assoc = $csvReader->fetchAssoc();
$all = $csvReader->fetchAll();
```
`$assoc`
```
Array (
    [0] => Array (
            [Paret name] => parent 1
            [Child name] => child 1
            [Title] => title
        )
    [1] => Array (
            [Paret name] => parent 2
            [Child name] => child 2
            [Title] => title
        )
)
```

`$all`
```
Array (
    [0] => Array (
            [0] => "Paret name"
            [1] => Child name
            [2] => Title
        )
    [1] => Array (
            [0] => parent 2
            [1] => child 2
            [2] => title
        )
)
```

**Comment by nyamsprod** [comment]
Quoting the docs you are referring to:
> After an extract/conversion method call, all query options are cleared;

This includes the `stripBom` method which is nothing more than a query option.

I know it may seems strange but this is a trade-off I choose when implementing the solution. Stripping BOM sequence is **only useful when the first cell of the first row is expected** in the result set. In all others situations you don't want to add another layer of Iterator when it is not needed.

**Comment by onema** [comment]
:+1: thank you for your work on this.

**Comment by nyamsprod** [comment]
The patch release 7.1.2 is released with the bug fix
