### ISSUE TITLE
Remove the need for SplFileObject flags

### ISSUE THREAD

**Issue by nyamsprod** [thephpleague/csv#105]
Since the beginning the `League\Csv\Reader` class has been relying on the `SplFileObject` flags for controlling which CSV line are returned or not. The problem is that some differences appear when
 
- using different PHP version (including HHVM);
- using `SplTempFileObject`(used in with `Reader::createFromString`)  vs `SplFileObject` (use with other named constructors).

We need a independent yet normalized way to loop through the CSV. So that the following will work out of the box without the need of `SplFileObject` flags.

```php
foreach ($csv as $row) {
   //do something meaningfull with the $row array
}
```
The last row shouldn't contains `null` or `false`

**Comment by jjanvier** [comment]
@nyamsprod any idea how to achieve this? I'm facing the same problem in one of my project

**Comment by nyamsprod** [comment]
The bug that needed this rewrite has been fixed in the master. The feature is no longer necessary
