### ISSUE TITLE
output() appends a row with the filesize?

### ISSUE THREAD

**Issue by JoeDawson** [thephpleague/csv#107]
Hey!

Excellent package by the way.

Currently outputting my CSV to discover that there's a random row being added to the end which appears to be the filesize.

```php
use League\Csv\Writer as CSV;

$csv = CSV::createFromFileObject(new \SplTempFileObject());

$csv->insertOne(['Venue Name', 'Total Entries', 'Passed', 'Failed']);

foreach($report['venues'] as $venue)
{
	$total =  $report['passes'][$i]+ $report['fails'][$i];

	$csv->insertOne([$venue->name, $total, $report['passes'][$i], $report['fails'][$i]]);

	$i++;
}

return $csv->output('report-'. $request->user()->id .'-'. Carbon::now()->timestamp .'.csv');
```

This outputs the following table;

![Output](http://f.cl.ly/items/2Q1g0i0m3d1x2R3s041n/Screen%20Shot%202015-06-12%20at%2013.02.53.jpg)

What's odd, is that when I use `$csv->toHTML()`, I just get this?

![toHTML](http://f.cl.ly/items/0322281B3H1P273M1Y0w/Screen%20Shot%202015-06-12%20at%2013.11.31.jpg)

Any ideas why the filesize is being appended when using `output()`?

Thanks in advance!

**Comment by nyamsprod** [comment]
Hi @JoeDawson,
Thanks for using the library. Like stated in the [documentation for the output method](http://csv.thephpleague.com/basic-usage/)  
> Since version 7.0, the method returns the number of characters read from the handle and passed through to the output.

This was done to match [PHP native function fpassthru](http://php.net/fpassthru)

The real question is why are you using `output` to save your CSV, this method is meant to be used to download the CSV, no `return` is needed 99% of the time :) .

**Comment by JoeDawson** [comment]
Oops, thanks @nyamsprod!

Wasn't aware that the `return` wasn't needed. Thank you very much!
