### ISSUE TITLE
Reader speed

### ISSUE THREAD

**Issue by dopesong** [thephpleague/csv#108]
I see that you're using str_getcsv which is much slower than fgetcsv.

http://stackoverflow.com/questions/4274109/handling-csv-files-fgetcsv-str-getcsv

The main problem is to read file correctly with fgetcsv. But in result it speeds up it for sure.

**Comment by nyamsprod** [comment]
Sorry but I don't understand the issue ? could you be more explicit. For what is worth `str_getcsv` is **not** used to parse the CSV at all.

**Comment by dopesong** [comment]
http://php.net/manual/en/function.fgetcsv.php#68213 - this example runs little bit faster :)

**Comment by nyamsprod** [comment]
again I'm not using `str_getcsv` to parse the CSV

**Comment by dopesong** [comment]
My mistake it's used only in one place, but not in query: https://github.com/thephpleague/csv/blob/633aad5203d7001ae1323a432129a79e91560cf4/src/Reader.php#L247
