### ISSUE TITLE
createFromString only reads first line when using CR instead of LF

### ISSUE THREAD

**Issue by tzfrs** [thephpleague/csv#111]
Hello,

I just exported an excel file to CSV, and wanted to parse this file using this library. I'm using a Mac, so it seems the new lines are done with CR. So, it should work like this, right?

// CR
`$reader = Reader::createFromString($file, "\n");`

// LF
`$reader = Reader::createFromString($file);`

However, the first one fails. When trying to ouptut the data later

    $data   = $reader->query();
    foreach ($data as $lineIndex=>$row) {
        print $row[0] . "\n";
    }

I'm only getting the first line. When converting the file to LF and parsing it, I'm getting all the datasets. Is this a known issue? Is there a reason?

**Comment by nyamsprod** [comment]
Hi @tzfrs Using the library on a Mac is covered in the [library documentation](http://csv.thephpleague.com/instantiation/)
