### ISSUE TITLE
apache error 500: (Array, 65435, Object(LimitIterator))

### ISSUE THREAD

**Issue by rootilein** [thephpleague/csv#112]
I tried to implement your library inside laravel with a csv file with about 90.000 lines.
About 50-60k lines are working fine, but then I get a HTTP 500 error from apache.

                $reader = Reader::createFromPath($persistedFile);
                $reader->setDelimiter(';');
                $reader->setOffset(1);
                DB::table('tablename')->truncate();

                $reader->each(function ($row) use (&$sth) {
                    $element = array(
                        'elem1' => $row[0],
                        'elem2' => $row[1],
                        'elem3' => $row[2],
                        ....
                        );
                    MODEL::insert($element);
                    unset($element);
                    set_time_limit(60);
                    return true;
                });

Inside the log, I can find this line:
> App\Http\Controllers\ImportController->App\Http\Controllers\{closure}(Array, 65435, Object(LimitIterator))

Is there another way to import that file?

**Comment by nyamsprod** [comment]
Maybe you should just simply remove your [set_time_limit](http://php.net/set_time_limit) from the loop and from the script. This is in not a League\Csv problem

**Comment by rootilein** [comment]
without set_time_limit, it's breaking, too.
any idea what could be the reason, when it's not League\Csv?
