### ISSUE TITLE
Feature request: Force enclosure character for every field in Writer

### ISSUE THREAD

**Issue by paslandau** [thephpleague/csv#113]
Hey there,
is it possible to force the `Writer` to add the escape character for every field (even if it wouldn't be necessary, e.g. even if no newline/delimiter is present in the field value)?

*Background:* Some receiving systems explicitly require to wrap every field in double quotes. I'm aware that this is not required by the usual CSV definition - but I stumble across this case fairly often in the "real world" and usually have no controll over the receiving end of the data.

Cheers
Pascal

**Comment by nyamsprod** [comment]
Hi @paslandau I think you made a mistake in your feature request... the problem is not the escape character but the enclosure character :+1: 
This feature (along with completely removing the enclosure #109) has been requested several times but I always refused to implement it without a proper PR has is would degrade the package quality. That being said, I think it is possible to force an enclosure on every field using the plugins features of the package.

**Comment by paslandau** [comment]
Hey @nyamsprod ,
you're right, I was talking about the enclosure character. Thanks for clearing that up ;)  

I don't really see how adding an option like that _decreases_ package quality, but I understand that the implementation is not trivial when `fputcsv` is used internally, since there's no option for adding the enclosure regardless of necessity on that function. I was just hoping there would be a workaround.

Can you elaborate on 

> I think it is possible to force an enclosure on every field using the plugins features of the package 

? Or point me to the corresponding page in the docu? I don't really understand to what you're referring as a "plugin".

Thx
Pascal

**Comment by nyamsprod** [comment]
Because answering on an issue would have taken too much time ... I wrote  a blog post about the solution hope you'll get the information you need there :+1: http://nyamsprod.com/blog/2015/qa-enforcing-enclosure-with-leaguecsv/

**Comment by paslandau** [comment]
Haha, seems like a good trade off for me :)

Thanks for taking the time to write an in-depth article about the topic. I'll give it a try.

Cheers
Pascal

**Comment by ebuildy** [comment]
For those who came here from a search engine, solution is available from version 9.1: http://csv.thephpleague.com/9.0/interoperability/enclose-field/. 

```EncloseField::addTo($outputWriter, "\t\x1f");``` (small typo in the doc)

**Comment by roberttolton** [comment]
What's the right class to be using? I'm getting:
`Class 'League\Csv\EncloseField' not found`
and:
`Class 'League\Csv\EnclosureField' not found`

**Comment by ebuildy** [comment]
Do you have version 9.1 ? It's open-source, so you can browser your ``vendor`` directory to find the class yourself ^^

**Comment by nyamsprod** [comment]
@roberttolton 9.1 is yet to be released. Still being tested but the API is stable. There was a typo in the v9 documentation. The class name is EncloseField. If you really need this feature you can use the master branch.

**Comment by roberttolton** [comment]
Thanks guys, yeah I noticed it was only on the 9.1 release, so I'm using `"league/csv": "^9.1@dev"` in my composer file now, and seems to work fine.
