### ISSUE TITLE
CPU usage scaling with file-size

### ISSUE THREAD

**Issue by ryzr** [thephpleague/csv#114]
Given the following code:

```php
ini_set("auto_detect_line_endings", '1');

$reader = \League\Csv\Reader::createFromPath(public_path($csv->file), 'r')
    ->setDelimiter($csv->delimeter)
    ->setEnclosure($csv->enclosure)
    ->setEscape($csv->escape);

$data = $reader->query();

foreach ($data as $row_num => $row) {
    //do nothing
}
```

Memory consumption is fine, achieving everything perfectly. However I see a higher CPU usage when using larger files. In a local environment:

38.8kb CSV -> Apache process reaches ~9% CPU
5.86MB CSV -> Apache process reaches ~45% CPU

Just wanting to know:

- Is this an expected outcome? I assumed everything was processed row-by-row (which seems to be the case as memory usage is fine)
- Is this something that could be rectified with proper server setup? (live setup is LNMP, local setup is WAMP)

**Comment by ryzr** [comment]
Worth noting, adding a micro sleep in the loop `usleep(100);` normalized CPU usage to around 10% locally. The higher the sleep, the lesser the CPU usage.

**Comment by nyamsprod** [comment]
Hi @ryzr sorry But I fail to reproduce this behavior on my personal laptop or on a remote server must be a configuration problem outside of the package scope
