### ISSUE TITLE
The values are not convertible into strings

### ISSUE THREAD

**Issue by james-daddies** [thephpleague/csv#116]
When the Writer comes across a `NULL` value from the database, an exception is thrown. 

`exception 'InvalidArgumentException' with message 'the values are not convertible into strings' in /home/inventory/www/vendor/league/csv/src/Writer.php:255`

I can handle the cases of `NULL` with `$row->value ?: ''` but really I would except the Writer to be able to handle `NULL` out of the box.

**Comment by postalservice14** [comment]
Looks like this might be fixed in version 7.  I can't seem to reproduce it with the latest version.

**Comment by james-daddies** [comment]
I'll run a composer update and test again.

**Comment by nyamsprod** [comment]
Type conversion from `null` to empty string was indeed made out of the box in [version 7.0](http://csv.thephpleague.com/upgrading/7.0/#null-handling)
