### ISSUE TITLE
Question about utf8

### ISSUE THREAD

**Issue by rbruhn** [thephpleague/csv#120]
I was wondering if the idea of filters can be explained a little better. I have a csv file that's suppose to be utf8 but sometimes someone submits a file where one cell might contain messed up characters. For example: M�_ll. Arg.

When trying to save this row to MongoDB, I receive an error: 'MongoException' with message 'non-utf8 string: M�_ll. Arg.'

I've read the stream filter page, and looked at some examples, but don't quite understand what needs to be done. Am I suppose to make my own class and supply that to the register and filter call?
```
stream_filter_register(FilterTranscode::FILTER_NAME."*", "\lib\FilterTranscode");

$reader->appendStreamFilter(FilterTranscode::FILTER_NAME."iso-8859-1:utf-8");
```
Is it possible to fix the characters on read? If so, can I get an example?
Or is what I'm trying to do not possible? Should I instead just check the row array for improper characters?

Thanks.

**Comment by nyamsprod** [comment]
@rbruhn Well stream filters are a feature of [PHP itself](http://php.net/manual/en/function.stream-filter-register.php) not restricted to League\Csv. And yes you can use stream filters to convert with the Csv\Reader class your CSV content prior to exporting it. Just look at the documentation around [stream filters](http://csv.thephpleague.com/filtering/) where the mechanism and examples of how to use them with the package are explained.
