### ISSUE TITLE
sanitizeStreamFilter breaks stream filters with new-line characters in their arguments

### ISSUE THREAD

**Issue by HeyRatFans** [thephpleague/csv#122]
When using [`appendStreamFilter`](https://github.com/thephpleague/csv/blob/master/src/Modifier/StreamFilter.php#L173) or [`prependStreamFilter`](https://github.com/thephpleague/csv/blob/master/src/Modifier/StreamFilter.php#L188) the name of the filter is sanitised by the [`sanitizeStreamFilter`](https://github.com/thephpleague/csv/blob/master/src/Modifier/StreamFilter.php#L203). This method currently casts the name to a string, trims and returns it.

Trimming the string removes any trailing new-lines or other invisible characters like NULLs or white-space to be removed. This causes problems for filters that expect these characters to be used as arguments. For example a filter that uses str_replace to convert Windows-style line endings (\r\n) to Linux-style (\n) cannot be used because the trailing \n gets removed by the trim call.

This issue affects release 7.1.2 of thephpleague/csv and is known to be present on both PHP 5.6.10 on Ubuntu 14.04 and 5.5.25 on Windows 7.

**Comment by nyamsprod** [comment]
This issue is resolved in the master branch
