### ISSUE TITLE
can you delete a column with this?

### ISSUE THREAD

**Issue by BardiaAfshin** [thephpleague/csv#127]
Is there a way to delete a column with this library? What about searching for duplicate information on a specific column?

**Comment by nyamsprod** [comment]
Hi @BardiaAfshin thanks for your interest in the library. I think the [documentation website](http://csv.thephpleague.com) answers all your questions. To summarize:

- Yes and No, you can not delete column but you can generate a modified version of your input CSV  using [the package formatter feature](http://csv.thephpleague.com/inserting/#row-formatting)

- Yes you can, just use the package [filtering features](http://csv.thephpleague.com/query-filtering/#filtering-methods).

Hope this will help
