### ISSUE TITLE
Roadmap to version 8.0

### ISSUE THREAD

**Issue by nyamsprod** [thephpleague/csv#131]
Hi everyone here's the roadmap to release version 8.0 for the CSV library. While version 7.0 was all about the Writer class, the new version will focus on the Reader class. 

### The plan

In version 7.2.0 (previously version 7.1.3) the following changes will occur:

- The default flags when instantiating a CSV object will be `SplFileObject::READ_CSV|SplFileObject::READ_AHEAD|SplFileObject::SKYP_EMPTY`. Previously the flags where `SplFileObject::READ_CSV|SplFileObject::DROP_NEW_LINE` which cause many bugs when iterating out of the box any CSV.
- `detectDelimiterList` will be deprecated in favour of `fetchDelimitersOccurence` method. The `detectDelimiterList` method is broken and its usage is not recommended.  `fetchDelimiterOccurences` will be more verbose but will return the correct information.
- `Reader::query` method will be deprecated in favour of `Reader::fetch` method.  Technically there's no difference between both methods but this normalize the Reader API for ease of use.

In version 8.0 I will change the return type for the following methods:

- `Reader::fetchAssoc($offset_or_keys, callable $callable = null)` will return an **iterator**;
- `Reader::fetchColumn($columnIndex = 0)` will return an **iterator**;

In version 8.0 the following method will be added:

- `Reader::fetchPairs($offsetColumnIndex = 0, $valueColumnIndex = 1, callable $callable = null)` will return a **generator** 

This way the Reader class will be usable for large CSV file while minimizing memory usage.
Version 8.0 will require at least PHP 5.5.0. 

### Open questions

- Since we are requiring PHP 5.5 we could use Generators. But I fail to see the advantage of using Generator since all extracting methods will return Iterators ?

**Update 2015-10-25**
Generators will be used for the newly added method `fetchPairs`.

**Comment by frankdejonge** [comment]
@assertchris There a question about Generators, so I ping you because you are the expert.

**Comment by nyamsprod** [comment]
@assertchris @frankdejonge the library is based on SplFileObject which his an PHP iterator optimized for files. I don't see how using a Generator would make the code use less memory unless I missed something. I recall this blog post by Anthony Ferrara where [he states similar things] (http://blog.ircmaxell.com/2012/07/what-generators-can-do-for-you.html). If I understand it correctly

**Comment by Heart1010** [comment]
Eventually the article from yesterday is also a good read!?

[Memory Performance Boosts with Generators and Nikic/Iter](http://www.sitepoint.com/memory-performance-boosts-with-generators-and-nikiciter)

**Comment by nyamsprod** [comment]
@Heart1010 this article is about `fopen` not `SplFileObject` in fact I would go as far as to say that 90% of what's in this article could have been done using the current CSV package :+1: And yes if I were to parse a CSV with fopen I would definitely use generators :) . The problem is not the use of generators but its use combined with an already instantiated Iterator which is the case for every usage of the current library

**Comment by assertchris** [comment]
The only way generators are better than iterators is in reducing the code to implement iterators. If you require 5.5 then you can use generators, but if you already get iterators from your code then porting that stuff over to exclusively use generators only benefits people looking at your implementation code.

Generators are iterators with less code and some structure for sending data/exceptions back into them.

About that post - the purpose was to illustrate a use case for nikic/iter. I could have used this package for that, but that would be missing the point. It's also an interesting take on relating csv data, and where generators help with that. I don't think it's relevant to this discussion at all.

**Comment by nyamsprod** [comment]
@assertchris Thanks for the input. I had came to the same conclusions as yours and I fully agree with your assessment about generators vs iterators.

**Comment by nyamsprod** [comment]
All the changes for v8 have landed on the dev-master branch. you can download and try it using composer:

```
composer require league/csv:dev-master
```

BC breaks are covered [in the upgrade page](http://csv.thephpleague.com/upgrading/8.0/) 
New features are covered [in the temporary  new reader page](http://csv.thephpleague.com/reading-8.0/)

Of note: the new version only runs on **PHP5.5+** and feature a completely rewrote `Reader` class. All other functionalities remain the same.

If no critical BC break or bug are found. The new version will be released December 3rd 2015 exactly 2 years after the first stable version of the library :+1:

**Comment by davesouthey** [comment]
Has the official release of v8 been postponed?

**Comment by nyamsprod** [comment]
@davesouthey Not at all. Too much work right now.. The v8 will be released this week .

**Comment by davesouthey** [comment]
@nyamsprod Okay, great. Just wondered as your previous post said the aim was the 3rd. I'm not putting pressure on, just offering to help if there is anything holding it back.

**Comment by nyamsprod** [comment]
@davesouthey help accepted :+1:  If you are a genius in scrutinizer (ie: better than me which is not very difficult) then you may be able to explain and/or fix a simple bug why does Why does [scrutinizer](https://scrutinizer-ci.com/g/thephpleague/csv/code-structure/master/class/League%5CCsv%5CModifier%5CStreamFilter) thinks that the complexity is 65 when on local PHPUnit gives 24

**Comment by davesouthey** [comment]
I'm certainly no scrutinizer genius and documentation around complexity seems rather sparse but I am think scrutinizer is taking into account all functions within the class whereas some other cyclomatic complexity calculations will ignore functions that aren't used within the class file.

The following aren't used within the class:
initstreamfilter, isactivestreamfilter, setstreamfiltermode, getstreamfiltermode, appendstreamfilter, prependstreamfilter, hasstreamfilter, removestreamfilter, clearstreamfilter, getstreamfilterpath.

**Comment by nyamsprod** [comment]
@davesouthey the folks from [scrutinizer have replied to my tweet](https://twitter.com/scrutinizerci/status/674279570116362240) . TL;DR this is a bug in their engine. So we'll have to wait until the fix is in production

**Comment by davesouthey** [comment]
Their fix has gone up :)

**Comment by nyamsprod** [comment]
version 8.0.0 is out
