### ISSUE TITLE
fetch() returns only hex values

### ISSUE THREAD

**Issue by larsbo** [thephpleague/csv#134]
I got a strange encoding bug with a csv file from paypal reporting.
When I try to fetch some data from the file with $reader->fetchOne() I only got hex values like
"\x00"\x00T\x00r\x00a\x00n\x00s\x00a\x00k\x00t\x00i\x00o\x00n\x00s\x00c\x00o\x00d\x00e\x00"\x00"
I tried some transcoding as described here http://csv.thephpleague.com/bom/ but nothing worked.

If needed I can send you the buggy csv file.

**Comment by nyamsprod** [comment]
@larsbo the Reader does not alter your CSV content I think this is an encoding problem did you try http://csv.thephpleague.com/filtering/

**Comment by larsbo** [comment]
@nyamsprod Yes, I know. I'm very sure that the file has some encoding issues.
I tried some filtering with the Transcode library, e.g.
```php
$csv->appendStreamFilter(FilterTranscode::FILTER_NAME."UTF-8:UTF-16LE");
```
and any other combination of encodings but nothing worked.

Is it even possible to solve such encoding problems with League\Csv or should I use another library to fix it?

**Comment by nyamsprod** [comment]
@larsbo This is a case where you need to get more infos around the source CSV encoding itself before determining what to do. The problem is not at the package level but the lack of info around the CSV you are trying to process.

**Comment by larsbo** [comment]
Oh, ok. 
So you cannot safely determine what encoding the author of the csv file has tried to use if there is something wrong?

So if that were the case I have to convince PayPal that they doing it wrong? :-)

**Comment by nyamsprod** [comment]
Have you tried to open the CSV file to have a look at it ? maybe the answer is there. A CSV file is nothing more than a file exchange format. if I send you a XML or a Json file without telling you in which encoding the file is ? You may assume it is in UTF-8 like the CSV package does but that is only an assumption the only person who knows the real encoding is the one who encoded the file. 

Bottom line:

1°) Open the file and try to figure it out by yourself 
2°) If you can't then yes you have to ask the CSV provider (in your case Paypal) for help 

There's no other workaround.

**Comment by larsbo** [comment]
Yes, of course. When I open it with [Sublime Text](http://www.sublimetext.com/) I can see the data without any problems.
After saving it as a new file or just overwrite the original one and load it again with League\Csv the encoding problem has gone and everything look fine.

This was the reason why I started this issue because I thought maybe there is some kind of special encoding thing that the library cannot handle properly.

**Comment by nyamsprod** [comment]
In this case then It's still not a library problem since through the use of filter you can virtually encode/transcode any character set in UTF-8. IMHO as you did not know the source encoding you were only guessing the file encoding did you try http://php.net/manual/fr/function.mb-detect-encoding.php for instance on the raw file to try to detect the encoding ?
This is again pure speculation It would have been great to see in which encoding Paypal did send you the CSV to begin with
