### ISSUE TITLE
Reader::fetchPairs return type

### ISSUE THREAD

**Issue by nyamsprod** [thephpleague/csv#136]
`League\Csv\Reader` version 8.0.0 will introduce the `Reader::fetchPairs` #131  method with the following signature

```php
public function fetchPairs(
    int $offsetColumnIndex = 0,
    int $valueColumnIndex = 1,
    callable $callable = null
);
```
The return type is yet to be decided between two options:

**Option one: return an Array**
```php
$csv = Reader::createFromPath('/path/to/file.csv');
$res = $csv->fetchPairs(); //$res is an array
foreach ($res as $offset => $value) {
    //$offset will always be unique!!
}
```
- main advantage: behave like expected in regards to other `fetchPairs` methods seen in PDO or other CSV libraries.
- main disadvantage: This method is not recommended for huge CSV files as it converts the internal Iterator into an array.

**Option two: return an Iterator**

```php
$csv = Reader::createFromPath('/path/to/file.csv');
$res = $csv->fetchPairs(); //$res is a \Generator
foreach ($res as $offset => $value) {
    //$offset may appear more than once !!
}
```

- main advantage : with huge CSV the memory consumption is minimal
- main disadvantage: if a value appears more than once in the offsetColumnIndex no merging will occur and some offset duplicate will appear

Which option do you prefer see implemented and why ?

Of note, whatever solution is chosen its behavior and limitation will be fully explain in the documentation.

**Comment by ssfinney** [comment]
Why not both? Include an optional parameter for returning a generator. Returning the array here seems the "safest" option (no duplicate offsets), so add an optional parameter to return a generator for increased performance.

**Comment by nyamsprod** [comment]
@ssfinney optional parameters to condition return type value is a recipe for disaster... I'd rather have two methods than one with a mixed return type depending on parameters

**Comment by ssfinney** [comment]
@nyamsprod I can understand that.

I guess my point is that I see the benefit in both options (for different use cases) so I would like to choose between the two depending on my situation.

However, maybe I'm off base and the user should make his project fit the implementation, not the other way around.

**Comment by nyamsprod** [comment]
Thanks to all your inputs a PR #137 has been done with the new methods which hopefully will solve the Reader::fetchPairs issue. Please review the changes in this PR for more informations
