### ISSUE TITLE
Manipulating the same file with reader and writer

### ISSUE THREAD

**Issue by repat** [thephpleague/csv#140]
Not sure if this is really an issue but I didn't know where else to ask this. I want to open a file, change something and close it again. So I thought I'd create a Reader, get the rows, create a Writer for the same file, change the values (e.g. with a formatter), and write the changed values to the same file. I tried a couple of versions but this seemed the easiest to read:

```php
$file = new SplFileObject('test.csv', "r+");

$reader = Reader::createFromFileObject($file);

$rows = $reader->fetchAll();

// print_r($rows);
// Array
// (
//     [0] => Array
//         (
//             [0] => john
//             [1] => doe
//             [2] => john.doe@example.com
//         )
// )

//$writer = Writer::createFromFileObject($file);
$writer = $reader->newWriter("w");

$formatter = function ($row) {
  $row[0] = "PREFIX_" . $row[0];
  return $row;
};

$writer->addFormatter($formatter);
$writer->insertAll($rows);
```

What I got however was this

```
john,doe,john.doe@example.com
PREFIX_john,doe,john.doe@example.com
```

According to the PHP Documentation, `fopen` should do this with `w`[1]

> 'w'	Open for writing only; place the file pointer at the beginning of the file and truncate the file to zero length. If the file does not exist, attempt to create it.

But it doesn't do it to the `SplFileObject`. Now, I know you can solve this by using  `$file->fseek(0)` and maybe I'm just understanding the code wrong (and it's too late at night;)), but what exactly does `newWriter("w")` do then?

[1] https://secure.php.net/manual/de/function.fopen.php

Thanks for the help

**Comment by nyamsprod** [comment]
@repat thanks for using the library.
Your problem is explained in the [documentation](http://csv.thephpleague.com/instantiation/).
For the open mode to be taken into account with the `newWriter` method you need to have instantiated your CSV object with the named constructor `createFromPath`.
The open mode only applies on a CSV object which was instantiated *à la* `fopen`

**Comment by repat** [comment]
Ok, thanks for the clarification. But I can't seem to figure out how to do the task I was describing above properly, which is:
1. Get the data
2. Change something in the data
3. Write the data back to the same file

This code works but it seems rather complicated. Would it be possible to give insertAll() a `$withHeaders` flag in one of the next releases? A lot of the CSV files we generate have to have headers.

```php

$filename = 'test.csv';

$file = new SplFileObject($filename, "r");
$reader = Reader::createFromFileObject($file);
$header = $reader->fetchOne();
$rows = $reader->fetchAssoc(0);

unlink($filename);

$file = new SplFileObject($filename, "w+");
$writer = Writer::createFromFileObject($file);
$writer->insertOne($header);

$formatter = function ($row) {
  $row["columnName"] = "PREFIX_" . $row["columnName"];
  return $row;
};

$writer->addFormatter($formatter);
$writer->insertAll($rows);
```

**Comment by nyamsprod** [comment]
Yes your code is very complicated indeed :+1: here's how I would do it. 
```php
use League\Csv\Reader;
use League\Csv\Writer;

$filename = 'test.csv';
$cellIndex = 3; //the cell index you want to format
$updateCsv = function ($row, $rowIndex) use ($cellIndex) {
    if (0 === $rowIndex) {
        return $row; //we do not change the header
    }
    if (!isset($row[$cellIndex])) {
        $row[$cellIndex] = ''; //in case the cellIndex does not exist
    }
    $row[$cellIndex] = 'PREFIX_'.$row[$cellIndex];
    return $row;
};

//we loop and format the Input CSV
$csv = Reader::createFromPath($filename, 'r');
$iterator = $csv->fetch($updateCsv);

//we create a temporary CSV file
$tmpPath = '/tmp/csv-temp-file.csv';
$tmpFile = Writer::createFromPath($tmpPath, 'w');
$tmpFile->insertAll($iterator);
unset($csv, $tmpFile); //we destruct both CSV objects because we are extra-cautious :)

rename($tmpPath, $filename);
```

That being said, you are free to extends the `Writer` class to add an extra argument to the `insertAll` method to help you improve your code.
