### ISSUE TITLE
Remove quotation marks from datetime output.

### ISSUE THREAD

**Issue by wesleyvicthor** [thephpleague/csv#141]
I am having an output of datetime with quotation marks, like this
3183-335-TAB03|335|18567|BOL|1|3183|"2015-12-11 19:32:40"|2015-12-11|2|TAB03|

How can I remove them ?
As you can see, the date field after the date quoted one is ok.
Is the reason the time in the date ?

I am basically using writer::insertOne();

**Comment by wesleyvicthor** [comment]
yeah, just noticed the setEnclosure method but, unfortunately I am not allowed to set a empty one.

**Comment by nyamsprod** [comment]
Hi,

@wesleyvicthor Please refer to issue #113
