### ISSUE TITLE
Quoting all fields

### ISSUE THREAD

**Issue by DixxieFlatline** [thephpleague/csv#143]
Hello, I'm trying to enclose **all** fields with double quotes but I can't get it. If using the following formatter:
~~~
$formatter = function ($row) {
    return array_map(function ($field){
        return('"' . $field . '"');
    }, $row);
};
~~~
the result I get is something like this: 
>"""KUNNR""";"""ALTKN""";"""BZIRK""";"""KDGRP""";"""KTOKD""";"""NAME1"""

I only want the fields to be enclosed, not them being enclosed with double quotes escaped with more double quotes. Is there a way to do this? If it's not, maybe it can be a good feature.

**Comment by nyamsprod** [comment]
@DixxieFlatline your problem has already been asked and respond to in the issue tracker #113

**Comment by DixxieFlatline** [comment]
Oh sorry, I'm new to Github and didn't saw the closed issues tab.

Thanks.
