### ISSUE TITLE
InvalidArgumentException on fetchAssoc()

### ISSUE THREAD

**Issue by DixxieFlatline** [thephpleague/csv#145]
Hello, first of all thanks for making this utility and sharing your code.

I have a problem when using *fetchAssoc()* without arguments (it will use the first row -headers- as the keys, as shown in the docs) and I am not able to find a solution. When I execute this function I get an **InvalidArgumentException** saying ***Use a flat array with unique string values***. The file is codified on UTF-8, and the headers are the following:
>CUPS;Nombre Cliente;CIF/NIF del Cliente;Estado;ID DST;Distribuidora;Previsión Inicio;Proceso;Tarifa Acceso;P1 (W);P2 (W);P3 (W);P4 (W);P5 (W);P6 (W);Activación;Contrato Distribuidora;Fin CMR;Tipo Punto de Medida;Propiedad Contador;Modo Control Potencia;Motivo de Rechazo;Tarifa Acceso;Dirección Cliente;CP Cliente;Población Cliente;Código Municipio;Ind. Act. Lec. Ciclo;Código CIE;Potencia Instalada BT;Fecha Emisión CIE;Fecha Caducidad CIE;NIF Instalador;Código Instalador;Nombre Instalador

As you may notice, all fields are unique. The exception only appears when executing *fetchAssoc()* using as argument any row of the doc, nor using another string or, for example,*fetchOne()*.

Thanks in advance.

**Comment by nyamsprod** [comment]
Hi,

Do you see this behavior as a bug ? If so could you please fill a proper bug report as stated in the [guidelines](https://github.com/thephpleague/csv/blob/master/CONTRIBUTING.md) So that I can look into it further. 
In any case I would suggest you reading the documentation before you do so.

thanks in advance

**Comment by DixxieFlatline** [comment]
Hello again and thanks for your support.

I detected the exception was thrown because of the **aray_unique()** method used in **validateKeys()**, so doing a further exam on the headers I've seen that there is really a repeated one wich I didn't saw before (and it wasn't supposed to be on the doc).

Thanks and sorry for the unconvenience I could have caused for my error.

**Comment by nyamsprod** [comment]
Not a problem I'm glad the exception thrown was the correct one (y)

**Comment by gabiudrescu** [comment]
I ended up here after searching on Google `Use a flat array with unique string values` because the CSV I had was manipulated with Excel and ended up with a header like this:

`pv.code,pv.images,,,`

though in Excel nothing appeared to be wrong, opening the .csv file with Sublime helped me better understand the error message.

I'm leaving this here so others might understand how to debug such errors in the future.

**Comment by lordspace** [comment]
I had the same issue. It turned out that the transactions I had exported had a column with the same name shown twice.
I had to edit vendor\league\csv\src\Reader.php file to see which column was a duplicate. 
A better error message would have saved me 30 minutes of troubleshooting.

**Comment by nyamsprod** [comment]
@lordspace what's so difficult to understand or misleading in the error message ?
> The header record must be empty or a flat array with unique string values.
was the header non empty then it means that it contains duplicates or non string fields. What other information is missing ?

**Comment by lordspace** [comment]
@nyamsprod there was 1 duplicate column.  I would have made this 2 checks .. for empty header & then another check using array_diff to list the duplicates. I wrote a function that formats the columns and appends numbers to duplicate columns

**Comment by nyamsprod** [comment]
@lordspace 👌 the changes you are suggesting have already been applied in the master branch. They will be released with the next 9.x release hopefully next month

**Comment by lordspace** [comment]
great!
