### ISSUE TITLE
fetchAssoc does not return expected result

### ISSUE THREAD

**Issue by cosecantt** [thephpleague/csv#146]
Here is the products.csv file

    product_code	name        type	id_group	sku	barcode	unit_price quantity_unit
    120	            Product1	Type1	2	        KB1	1111111	11000	   pc
    121	            Product2	Type2	2	        KB2	2222222	15000	   kg
    122	            Product3	Type3	2	        KB3	3333333	20000	   gr
    123	            Product4	Type4	2	        KB4	4444444	30000	   pc
Here is the code

    use League\Csv\Reader;
    $reader = Reader::createFromPath('uploads/products.csv');
    $keys = $reader->fetchOne();
    $data = $reader->fetchAssoc($keys);
    echo '<pre>', print_r($data, 1), '</pre>';

Here is the result

    League\Csv\Modifier\MapIterator Object
    (
        [callable:League\Csv\Modifier\MapIterator:private] => Closure Object
        (
            [static] => Array
                (
                    [keys] => Array
                        (
                            [0] => product_code
                            [1] => name
                            [2] => type
                            [3] => id_group
                            [4] => sku
                            [5] => barcode
                            [6] => unit_price
                            [7] => quantity_unit
                        )

                    [keys_count] => 8
                )

            [this] => League\Csv\Reader Object
                (
                    [stream_filter_mode:protected] => 1
                    [path:protected] => uploads/products.csv
                    [open_mode:protected] => r+
                    [delimiter:protected] => ,
                    [enclosure:protected] => "
                    [escape:protected] => \
                    [newline:protected] => 

                    [encodingFrom:protected] => UTF-8
                    [input_bom:protected] => 
                    [output_bom:protected] => 
                    [iterator_filters:protected] => Array
                        (
                        )

                    [iterator_sort_by:protected] => Array
                        (
                        )

                    [iterator_offset:protected] => 0
                    [iterator_limit:protected] => -1
                    [strip_bom:protected] => 
                    [stream_filters:protected] => Array
                        (
                        )

                    [stream_uri:protected] => uploads/products.csv
                    [stream_regex:protected] => ,^
        php://filter/
        (?P:?read=|write=)?  # The resource open mode
        (?P.*?)           # The resource registered filters
        /resource=(?P.*) # The resource path
        $,ix
                )

            [parameter] => Array
                (
                    [$row] => 
                )

        )

    )

But according to the documentation the expected result should be:
http://csv.thephpleague.com/reading/

    [
          [
                 'product_code' => '120',
                 'name' => 'Product1',
                 'type' => 'Type1',
                 'id_group' => '2',
                 'sku' => 'KB1',
                 'barcode' => '1111111',
                 'unit_price' => '11000',
                 'quantity_unit' => 'pc',
           ],    
           ...
    ]

**Comment by nyamsprod** [comment]
`Reader::fetchAssoc` returns an Iterator since version 8.0 has stated in the documentation. So using a simple `foreach` on the result of the method call should return the expected results.
I can update the example to highlight that. It's a legacy of version 7.0 :+1:

**Comment by cosecantt** [comment]
Oh my. I missed that part. Works fine. Thank you for your response.

**Comment by nyamsprod** [comment]
the documentation examples have been updated to highlight the change of return type.
