### ISSUE TITLE
[Feature] Saving the created csv file to the server

### ISSUE THREAD

**Issue by cosecantt** [thephpleague/csv#147]
If I am not missing that feature, it would be pretty great if there is a `save` feature  after creating(writing) a csv file on the server, without outputting on the browser, which enables the users save the file on the server for later download ...

     $csv->save('path/to/saved/file/products.csv');

Thank you for the script!

**Comment by nyamsprod** [comment]
Hi @cosecantt ,

I don't get what your are saying you are already able to save the CSV when using the Writer class on a given path. What would your proposed `save` method add ?

**Comment by cosecantt** [comment]
I mean I want to save the created CSV file directly to the server under uploads folder. Is it possible with this current version? If yes would you mind give some tips. Thank you.

**Comment by nyamsprod** [comment]
```php
$csv = Writer::createFromPath('/path/to/the/final.csv');
```

Whatever you create or append it will be saved at `/path/to/the/final.csv` so I don't understand your question unless you have a concrete exemple ?

Everything else will always at some point involve this code :+1:

**Comment by cosecantt** [comment]
I want to pull data from database and save it to the server.
 
    $sth = $dbh->prepare("SELECT firstname, lastname, email FROM users LIMIT 200");
    $sth->setFetchMode(PDO::FETCH_ASSOC);
    $sth->execute();
    $csv = Writer::createFromFileObject(new SplTempFileObject());
    $csv->insertOne(['firstname', 'lastname', 'email']);
    $csv->insertAll($sth);
    
Now instead of 

    $csv->output('users.csv');

I want to save it to the server

    $csv->save('path/to/the/final.csv');

In this case how it is possible? Thank you.

**Comment by nyamsprod** [comment]
please, read my answer and the full documentation on the writer class as I have already respond to your question.

**Comment by cosecantt** [comment]
Ok thank you for your answer. It was a little bit confusing. My apology. Now saving worked fine.
But I am having issues with UTF-8 characters. Whenever I read from database and write it to csv it does not recognize the UTF characters. Or vice versa. Anything I am missing? Thank you.

**Comment by nyamsprod** [comment]
Since I don't know exactly what you are trying to do I can not assist you. Keep in mind that this is an issue not a support thread. The library and its documentation won't always answer all the questions regarding any specific case. In your case I'm betting that you need to take into account many factors that are out of scope from the library.

**Comment by meharunnisashaik** [comment]
@cosecantt

can you please give the smaple code how you saved csv in to folder. my code is 

$data="data i want to show"";
 $csv = \League\Csv\Writer::createFromFileObject(new \SplTempFileObject());
 $csv->insertOne(['firstname', 'lastname', 'email']);
$csv->insertAll($data);
$csv->output('final.csv');

file is getting downloaded..but i want to save the file in laravel public/downloads folder..

i tried to use save method but might be syntax error file not saving folder..

**Comment by lightmed** [comment]
@meharunnisashaik 

If you want to import data to file, this is the correct way:

$csv = Writer::createFromPath('/path/to/the/final.csv');
$csv->insertOne(['firstname', 'lastname', 'email']);
$csv->insertAll($data);
