### ISSUE TITLE
PHP bug: escape characters not stripped by SplFileObject:fgetcsv

### ISSUE THREAD

**Issue by mjordan** [thephpleague/csv#149]
If an enclosure character appears within a field, but that enclosure is escaped, the escape character appears in the Reader's output. For example, using the following input file:

```
"first row, first field", "first \"row\", second field"
"second row, first field", "second row, second field"
"third row, first field", "third row, second field"
```
and the following script:

```php
<?php

require 'vendor/autoload.php';
use League\Csv\Reader;

$reader = Reader::createFromPath('test.csv');
$results = $reader->fetch();
foreach ($reader->fetch() as $row) {
    print_r($row);
}
```

the output is:

```
Array
(
    [0] => first row, first field
    [1] => first \"row\", second field
)
Array
(
    [0] => second row, first field
    [1] => second row, second field
)
Array
(
    [0] => third row, first field
    [1] => third row, second field
)
```

Is the inclusion of the backslash in the first row's output intended, or should the backslash be automatically removed? Or is removing the backshlash up to the application?

**Comment by nyamsprod** [comment]
@mjordan It would seems you encounter this [PHP bug](https://bugs.php.net/bug.php?id=55413). Since this package is based on PHP's internal engine for parsing a CSV. There's not much I can do to fix that at the moment. We can make a PR on the gh-pages to document it.

**Comment by nyamsprod** [comment]
@mjordan you may be able to work around the bug using the package stream features though. Look at the examples in the documentation

**Comment by mjordan** [comment]
OK, thanks for looking into this. I'll try the stream feature.

**Comment by nyamsprod** [comment]
I've updated the documentation website to highlight this bug. 

- http://csv.thephpleague.com/properties/
- http://csv.thephpleague.com/7.0/properties/

**Comment by nyamsprod** [comment]
A Stream Filter has been added to CSV v9.0 codebase to fix this issue
