### ISSUE TITLE
BOM length is appended to the end of the csv output

### ISSUE THREAD

**Issue by Lidbetter** [thephpleague/csv#157]
Looking through RFC's I can't find where this is listed.

When calling `$writer->output('filename');`

the output file looks like this:
csv:
![screen shot 2016-03-23 at 12 39 36](https://cloud.githubusercontent.com/assets/6525616/13993047/f56dd586-f0f4-11e5-9b03-5d3f677b98b5.png)
numbers:
![screen shot 2016-03-23 at 12 38 58](https://cloud.githubusercontent.com/assets/6525616/13993050/fa098fcc-f0f4-11e5-862b-2e54e875426a.png)

**Comment by nyamsprod** [comment]
Hi @Lidbetter this question was already raised and answered to on the following issue #107 .

PS: what RFC are you referring to ?

**Comment by Lidbetter** [comment]
Thanks, I was returning the output from my controller, rather than just calling output
