### ISSUE TITLE
The delimiter must be a single character : !#

### ISSUE THREAD

**Issue by eXorus** [thephpleague/csv#161]
Hello,

I'm working with a csv file like this :

"Réf."!#"Type"!#"Country"
"1785"!#"house"!#"France"

When I'm using  $inputCsv->setDelimiter('!#');
it's not working I have this error :

InvalidArgumentException in Controls.php line 69: 
The delimiter must be a single character

And I don't know how to manage "" with your lib.

Thanks

**Comment by nyamsprod** [comment]
@eXorus thanks for using the library.

You should read the library documentation. It may help you solve your issue.

**Comment by eXorus** [comment]
Sorry but I don't see anything how to manage delimiter with more than one characters ?

Could you help me ?

**Comment by nyamsprod** [comment]
I never tried this but you could use the library stream capabilities to replace the delimiter on the fly. If this works I'd like to see a blog post about how you did it as it may help other people in your situation.

**Comment by nyamsprod** [comment]
I'm sorry I can not be of more help as this is not an issue per se there's not much I can do.

**Comment by eXorus** [comment]
Thanks I will try to do it and give you an example.
