### ISSUE TITLE
Inserting with Writer::insertOne() on the end of the file.

### ISSUE THREAD

**Issue by jandayanan** [thephpleague/csv#162]
I am using now the Writer::class and it seems to me that the write only occurs on the beginning of the file. My aim is to append data to an existing CSV file. 

I have the following code: 
Where csvPath is the path of the existing CSV file to read from. Multi is just a flag to whether or not insert is as each row or as a 2 dim array.

``` PHP
     $writer = Writer::createFromPath( $this->csvPath );

        if( !$multi ){
            if( count( $rows ) === count( $this->columns ) ) {
                $writer->insertOne( $row );
            }
        }else{
            foreach( $rows as $row ){
                if( count( $row ) === count( $this->columns ) ){
                    $writer->insertOne( $row );
                }
            }
        }
```

I am looking for something like:
`` $writer->insertOne( $row, $index );

where index is the line of the file where the insertion will occur. Or something like:
`` $writer->insertOne( $row, $insert_at_end );

**Comment by nyamsprod** [comment]
@jandayanan thanks for using the library.

You should refer to the library documentation website where you will find all the information needed to solve your issue.
