### ISSUE TITLE
Reader Iterator doesn't respect setOffset

### ISSUE THREAD

**Issue by rosstuck** [thephpleague/csv#165]
I'm not sure if this is actually a bug, but the Iterator doesn't seem to support setOffset(). This might be part of the intended API, but each() does seem to respect offsets.

I haven't checked this with other query options like limit.

```
$reader->setOffset(50); 

$reader->each(function ($row) {
   //respects offset, starts on row 50
});

foreach ($reader as $row) {
   //always starts on row 0
}
```

I'm using CSV 8.0.

**Comment by nyamsprod** [comment]
@rosstuck This is not a bug it is expected behavior but it seems I removed the info in the documentation for v8. 

This is documented in v7 documentation.

> After an extract/conversion method call, all query options are cleared;

**Comment by nyamsprod** [comment]
The missing information is added to [v8 documentation](http://csv.thephpleague.com/query-filtering/)

**Comment by rosstuck** [comment]
Thanks for the quick response! To be clear, in my code snippet above, I'm not running those two pieces of code one after the other, it was just meant to show that each() respects the offset, whereas the version relying on IteratorAggregate does not.

If the same holds true though, I'm still confused about using the API with each() because it only returns a single row.

My use case is that I'm trying to read a large CSV file, streaming, and occasionally would like to start it from a particular row number (for example, resuming a test job). Can you help me understand what the best way to do this is? I'm a bit confused because each() only returns one row (even with limit explicitly set to all) and Iterator aggregate returns all but doesn't respect the offset.

**Comment by nyamsprod** [comment]
in that case then you need to use the `fetch` method like so:

```php
$reader->setOffset(50);
foreach($reader->fetch() as $row) {
  //starts at the 51th row...
}
```

**Comment by rosstuck** [comment]
Okay, I'll give that a shot, thanks!
