### ISSUE TITLE
problem with utf-8 reading

### ISSUE THREAD

**Issue by jbehrouzi** [thephpleague/csv#167]
Hi 
i tried to read from a cvs file which it's encoding is utf-8 , i do that this way :

` 
$csv = Reader::createFromPath(storage_path('app') . "/requirement/lessons.csv");
$csv->each(function ($row) use (&$sth) {
                var_dump($row[0]);
` 
this is my out put :
![image](https://cloud.githubusercontent.com/assets/11288751/16713496/a580ba6e-46be-11e6-8fc5-a84fa3fc536f.png)

how can i fix that ?

**Comment by nyamsprod** [comment]
Did you read the [documentation ](http://csv.thephpleague.com/) ?

**Comment by jbehrouzi** [comment]
yes of course ! 
this is my file 

[http://s7.picofile.com/file/8259232850/lessons.csv.html](url)

**Comment by nyamsprod** [comment]
@jbehrouzi as a hint you could use the stream filter capabilities as explain in the documentation
