### ISSUE TITLE
Blank CSV File Created

### ISSUE THREAD

**Issue by Britic** [thephpleague/csv#169]
## Issue summary

I'm creating an export with values from the database and up to a certain number of rows it works perfectly, then when one extra row is added, the CSV returned is blank.

I've checked the data of that row and it is just a string, also, using offsets in the database query I've managed to add the row in fine with a smaller set of data.

So, it's not the data format that's the problem and I'm at a loss.

I've tried using $writer->insertOne() and also $writer->insertAll() but have exactly the same results.

Is there some kind of limit when adding to a file that I don't know about? I am not getting any error logs on the server.

For additional info, there are 9 columns each with a short string of text (avg 2 characters). Depending on the dataset, the limit is somewhere around the 50 row mark

### System informations

_(In case of a bug report Please complete the table below)_

| Information | Description |
|--------------|---------|
| League\Csv version |8.1.0  | 
| PHP/HHVM version | 5.6 | 
| OS Platform |Linux  | 

## Standalone code, or other way to reproduce the problem

For me, any dataset of over 50 rows with the amount of data described above is causing the problem.

I am not getting any error logs on the server

        $exportFilePath = $this->createExportFile('questions');
        $writer = Writer::createFromPath($exportFilePath);
        $headings = [
            'Campaign Name',
            'Location Name',
            'Address 1',
            'City',
            'State',
            'Zip',
            'Assessment Date',
            'Question',
            'Answer'
        ];
        $writer->insertOne($headings);

        $questionsData = $this->getQuestionsExportData();

        foreach ($questionsData as $data) {

            $dataRow = [
                $data->campaignName,
                $data->locationName,
                $data->locationAddress,
                $data->locationCity,
                $data->locationState,
                $data->locationZip,
                $data->completed,
                $data->questionText,
                $data->answerText,
            ];
            $writer->insertOne($dataRow);
        }

        return \Response::download($exportFilePath);

### Expected result

CSV file with all rows with data

### Actual result

Empty CSV file

**Comment by nyamsprod** [comment]
Hi @Britic, thanks for the report. From your code I fail to see how you can be sure that the behaviour you are reporting comes from the League\Csv package ?

```php
return \Response::download($exportFilePath);
```
you seems to give your `exportFilePath` to a download method both of which are not produced by the package. Since I don't know how these (methods/functions) works I can not debug your issue maybe try to do what you've describe using **only** the package functionnalities then I'll be able to fix what needs to be fix ... if the issue still remains.

**Comment by Britic** [comment]
Thanks for your response.

`return \Response::download($exportFilePath);`
is a Laravel function for returning the file for download. I understand that's not under your control, but even ignoring that, the file on the server remains completely blank.

When I replace any use of writer with the native functions, I get the expected file download.

`
    public function questionsExport()
    {
        $exportFilePath = $this->createExportFile('questions');
        $handle = fopen($exportFilePath, 'w+');
        //$writer = Writer::createFromPath($exportFilePath);

        $headings = [
            'Campaign Name',
            'Location Name',
            'Address 1',
            'City',
            'State',
            'Zip',
            'Assessment Date',
            'Question',
            'Answer'
        ];
        //$writer->insertOne($headings);
        fputcsv($handle, $headings);

        $questionsData = $this->getQuestionsExportData();

        foreach ($questionsData as $data) {

            /* @var $assessment \App\Assessment */
            $dataRow = [
                $data->campaignName,
                $data->locationName,
                $data->locationAddress,
                $data->locationCity,
                $data->locationState,
                $data->locationZip,
                $data->completed,
                $data->questionText,
                $data->answerText,
            ];
            //$writer->insertOne($dataRow);
            fputcsv($handle, $dataRow);
        }

        $headers = array(
            'Content-Type' => 'text/csv',
        );

        return \Response::download($exportFilePath, null, $headers);
    }
`

If you want to close this issue as I can't confirm where the error lies, then that's no problem.

**Comment by nyamsprod** [comment]
hmm what your are doing is very complicated. 

There's a simple article on how to use [League\Csv  with Laravel you shoud check](https://mattstauffer.co/blog/export-an-eloquent-collection-to-a-csv-with-league-csv).

I hope it does answer your question.
