### ISSUE TITLE
Unexpected echo statement?

### ISSUE THREAD

**Issue by hhamon** [thephpleague/csv#170]
Hello,

In file https://github.com/thephpleague/csv/blob/master/src/Config/Output.php at line 209, there is an echo() statement. I don't think it's intended and should be removed.

Thus, there is method called `getInputBOM()` but its real signature is `getInputBom()`. Sometimes, you use the `getInputBom()` and sometimes `getInputBOM()` method names in the code. It makes harder to use grep/ack to find where the method is called in the code.

**Comment by nyamsprod** [comment]
> In file https://github.com/thephpleague/csv/blob/master/src/Config/Output.php at line 209, there is an echo() statement. I don't think it's intended and should be removed.

Yes it is intended ... for the purpose of handling BOM sequence.

> Thus, there is method called getInputBOM() but its real signature is getInputBom(). 

As a matter of fact its real signature is `getInputBOM` because it is related to BOM :+1:  This will be patch in a bug fix release. thanks for the report.

**Comment by nyamsprod** [comment]
in the meantime you can also submit a PR to correct this its easy to fix

**Comment by hhamon** [comment]
Done here: https://github.com/thephpleague/csv/pull/171
