### ISSUE TITLE
Cannot delete a CSV file after usage

### ISSUE THREAD

**Issue by andjelicsasa** [thephpleague/csv#173]
## Issue summary

Hi,
I am trying to delete a file right after I have parsed it. I get an exception with a following message:
`unlink(/home/vagrant/Root/Projects/photoncms/app/PhotonCms/Dependencies/Files/Temporary/invitations_no_headers.csv): Text file busy`

I open the file with ($filepath - absolute path to the file):
`$inputCsv = Reader::createFromPath($filepath);`

At the end I have tried to delete the file using Laravel Storage facade ($csvFile - relative path to file):
`\Storage::disk('temporary')->delete($csvFile);`

Is there a way to close the file so I can delete it?

Composer package: "league/csv" : "^8.0"
Running on Laravel homestead

**Comment by nyamsprod** [comment]
Hi @andjelicsasa this issue is not related to League\Csv but on how SplFileObject works. Before deleting your file you need to free any resource attached to it the easiest solution is
```php
$inputCsv = Reader::createFromPath($filepath);
$inputCsv = null;
//now you can delete your file
```
For a complete explanation [please check here](http://stackoverflow.com/questions/11850726/splfileobject-vs-fopen-in-php/23682549#23682549)

**Comment by andjelicsasa** [comment]
Thanks for the explanation @nyamsprod , I will look more into it.

Setting the variable to null doesn't work as well as unset().

If I find a solution I will post it here, for others.

**Comment by nyamsprod** [comment]
@andjelicsasa this means that you have other resources pointing to this file elsewhere in your code. Just google for `Text file busy php`.

**Comment by andjelicsasa** [comment]
@nyamsprod yep you're right, I had a QueryFilter instance.

`$rows = $inputCsv->setOffset($hasHeaders ? 1 : 0)->fetch();`

Thanks!
