### ISSUE TITLE
Why can't setInputEncoding add a transcode filter too?

### ISSUE THREAD

**Issue by dequis** [thephpleague/csv#177]
Or, to put it differently, handling input encodings is overcomplicated and I don't get why

The docs have stuff like:

```
$csv = Reader::createFromPath('/path/to/file.csv');
$csv->setInputEncoding('iso-8859-15');
echo $csv->getInputEncoding(); //returns iso-8859-15;
```

Which is something one would expect to decode the file on the fly, but for some reason it's asymmetrical and only applies to conversion, not reading or writing.

For everything else, we're supposed to add a stream filter for FilterTranscode, which is not included because:

> The FilterTranscode class is not attached to the Library because converting your CSV may depend on the extension you choose, in PHP you can use the following extensions :
> - The mbstring
> - The iconv
> - The intl

However, setInputEncoding uses mbstring. Even if the availability of different extensions was a problem, this could be solved with runtime detection (I personally don't see a problem in only supporting mbstring - or are there actual users who have iconv/intl loaded but not mbstring?)

So instead I'm supposed to copy the "example" FilterTranscode class into my own codebase, and initialize it like this:

```
stream_filter_register(FilterTranscode::FILTER_NAME."*", "\lib\FilterTranscode");
$reader->appendStreamFilter(FilterTranscode::FILTER_NAME."iso-8859-1:utf-8");
```

I can see how stream filters are a powerful concept, but this just ends up being an obtuse api. Especially frustrating when there's something called `setInputEncoding` that is explicitly documented to not do what one would expect it it do.

**Comment by nyamsprod** [comment]
@dequis 
> Which is something one would expect to decode the file on the fly, but for some reason it's asymmetrical and only applies to conversion, not reading or writing.

It's asymmetrical because stream support **is limited** on `SplFileObject` the underlying object used by the package. This means that registering a stream filter is not always possible.

Of note, since version 8.1.0 you can simply do:

```php
<?php

use League\Csv\Reader;

$reader = Reader::createFromPath('/path/to/my/iso8859.csv');
$reader->appendStreamFilter('convert.iconv.ISO-8859-1/UTF-8//TRANSLIT');
var_dump($reader->fetchAll());
```
using PHP's built-in `iconv` stream filters which simplifies stream filter usage.

**Comment by dequis** [comment]
Oh whoops i only saw the referenced commit after submitting that comment (because I had the browser a tab open for four days). Thanks for that. I'll comment stuff specific to that implementation in #178

**Comment by nyamsprod** [comment]
@dequis I've re-started working on league v9 and I was wondering does setting the input encoding really means that you should automatically transcode the CSV into utf-8 ? the setInputEncoding method was originally created to ease CSV transcode into XML or Json (which requires UTF-8 to work well), it is not meant to be use to transcode on the fly the CSV document while manipulating it.

**Comment by dequis** [comment]
Hmm, I guess PHP doesn't have the concept of "unicode strings" so decoding doesn't mean anything without a target encoding. I do think that target encoding should implicitly be UTF-8 in all cases, but that's more of an opinion.

I haven't considered the use case of manipulating CSV files (reading and writing back), I guess in those cases it may be desirable to keep the file in its source legacy encoding, but then it matters more to make it explicit.

Anyway all I wanted from this issue was a quick no-frills no-thinking way to read files with any legacy encoding and work with them with a sane one internally. From the outside, without knowing the implementation details, `setInputEncoding` seemed to promise that.

**Comment by nyamsprod** [comment]
> I do think that target encoding should implicitly be UTF-8 in all cases, but that's more of an opinion.

That's what it does with transcoding to XML or Json 👍 

I'm strongly thinking of removing the `setInputEncoding` from the Reader/Writer object and move it to the RecordSet object so that it does not mislead the user into thinking that any translation is done automagically. However the naming still suggests that the Record are transcoded so maybe a name change also will be needed to clarify the method intent.

and yes the only real way of autoconversion is through stream filter. 

Once I've figured this out ... I'll make a PR referencing this issue 

thanks

**Comment by nyamsprod** [comment]
To convert the input CSV document you are required to use the stream filters capabilities like explained in the documentation.

in v9 see #210  `setInputEncoding` will be renamed `setConversionInputEncoding`. By renaming the method we should resolve the misunderstandings in its usage. 

Hope this resolve your issue.

**Comment by nyamsprod** [comment]
I'm going to close this issue has no fix can be done in v8 about it and v9 fix this by changing the method name

**Comment by dequis** [comment]
Well that counts as fixed for me, really. Thanks!
