### ISSUE TITLE
Sample for reading from flysystem?

### ISSUE THREAD

**Issue by philippfrenzel** [thephpleague/csv#182]
Hi,

this is not a real issue, is more a request for example ;)
I guess this works easy - but I didn't find anything within the docs - so I can't rtfm ;)

Thanks Philipp

**Comment by nyamsprod** [comment]
there's no example as it is trivial IMHO but maybe @frankdejonge will tell you otherwise

**Comment by frankdejonge** [comment]
@philippfrenzel hi, an easy example is this:

```php
$filesystem = new Filesystem(new Local($rootDirectory));
$contents = $filesystem->read($relativePath);
```

**Comment by philippfrenzel** [comment]
Ok, until then I can easily follow, but what reader from CSV->reader() do I use then?

Thanks for your support!

**Comment by frankdejonge** [comment]
Oh wait, shit. This is a different project.

**Comment by frankdejonge** [comment]
@philippfrenzel just a sec, will type up an example for you. Thought this was just "how to read something from flysystem".

**Comment by philippfrenzel** [comment]
Don’t worry - I use flysystem in production and it works wonderfull!
So sadly I’m only a home made coder why from time to time I’m stuck in potentially easy issues :)

Your support is highly appreciated!

**Comment by frankdejonge** [comment]
@philippfrenzel ok, so it's fairly simple, you can just create a reader from a string:

```php
$filesystem = new Filesystem(new Local($rootDirectory));
$contents = $filesystem->read($relativePath);
$reader = Reader::createFromString($contents);
```

**Comment by philippfrenzel** [comment]
Ok, so if this will do the job - that's great! ;) Thanks!
