### ISSUE TITLE
Is there a limit to the size of a CSV

### ISSUE THREAD

**Issue by RomainGoncalves** [thephpleague/csv#183]
Hi,

I'm trying to import a large quantity of data in a CSV using the library. I have 90K+ lines, however the final CSV is 65535 lines.

Is there a limit put on the number of lines a file can have?

Thank you for any help

### System informations

_(In case of a bug report Please complete the table below)_

| Information | Description |
|--------------|---------|
| League\Csv version | 8.8.1 |
| PHP/HHVM version | 7 |
| OS Platform | OS X |

**Comment by nyamsprod** [comment]
Without any actual code I can not be of any help. For what is worth the package uses stream filter whenever possible so you should be able to consume any large CSV without any problem.

**Comment by RomainGoncalves** [comment]
I'm sorry, I wasn't clear.

I actually have a PHP array of 90K+ lines of processed data. Then I try to input that in a CSV using the library. 

Code looks like this:

```php

// $end = [ ['12-03.2015', 'event #1', '1', '2,', '1'], ....];

$writer = Writer::createFromFileObject(new SplTempFileObject()); //the CSV file will be created using a temporary File
		$writer->insertOne(["date", "event", "Total Events", "Unique Events", "Event Value", "Avg Event Value"]);
		$writer->insertAll($end);
		return $writer->output('events.csv');
```

65535 lines are written properly, but it stops there.

Thanks for your help.

**Comment by zf2timo** [comment]
65535 looks interesting -> [32bit]( http://programmers.stackexchange.com/questions/176858/is-there-something-special-about-the-number-65535)
Maybe there is an error with 32Bit somewhere?
Does your `$end` variable really all the expected 90k entries?

**Comment by RomainGoncalves** [comment]
hello @zf2timo 
thanks for your reply.

Yes my $end has the 90K array entries, I made sure of that.

Has it been tried before to enter a lot of row at one time?

**Comment by nyamsprod** [comment]
> Has it been tried before to enter a lot of row at one time?
Usually lot of rows means exporting Database rows using PDO or using a Generator. This works as I've been doing this with more than 100K+ rows. For me this is the recommended ways in term of memory usage and all, using a 90K rows array seems strange to me.

**Comment by RomainGoncalves** [comment]
well, I get lots of data from Google's API and need to write it into a csv. No PDO or generator.

What sort of generator?

**Comment by nyamsprod** [comment]
you're getting 90K data from a straight call to Google API's ?

**Comment by RomainGoncalves** [comment]
No. I call the API many times over in order to get all the data I need, otherwise it gets sampled.

**Comment by RomainGoncalves** [comment]
Do you think I should write the CSV as I receive the different calls?

**Comment by nyamsprod** [comment]
So you **do** stock your data somewhere in between calls right ? This somewhere being a File or a DB. You can access it using an Iterator or a Generator and you'll be able to create your CSV without any problem.

**Comment by RomainGoncalves** [comment]
For now, I do all the calls at once, I don't store the results in DB. Just in an array while the calls are being made.

**Comment by RomainGoncalves** [comment]
OK i've tried implementing the CSV within a loop, so that my $end never has 90K anymore, more like 5k rows each iterations. But the final CSV is still limited to 65535 lines...

I don't get it.

BTW, I'm on a Mac, El Capitan, php7 if that helps...

**Comment by RomainGoncalves** [comment]
OK my (huge..?) mistake. Happens that, the file is actually written properly! However Numbers (mac equivalent of Excel) does not display more than 65535 rows... I inputted the file within Google Spreadsheets, and I see all rows up to 90K+.

Sooo that's that.

Thanks for your help and I will close this thread.

**Comment by fgilio** [comment]
Thanks for the final update @RomainGoncalves
