### ISSUE TITLE
Reader from URL

### ISSUE THREAD

**Issue by pezzetti** [thephpleague/csv#186]
Is it possible instantiate a Reader from URL instead of a local path to the file?

Thanks!

**Comment by nyamsprod** [comment]
@pezzetti please refer to the documentation the `createFromPath` named constructor accepts the same arguments as `fopen` . So the answer is yes

**Comment by alwinaugustin** [comment]
Is it possible to use `Statement` over it ?  When I use the following code, I am getting `stream does not support seeking` error.
```
$reader = Reader::createFromPath('my_s3_file_path.csv', 'r');
$records = (new Statement())
                ->offset(0)
                ->limit(10)
                ->process($reader, $keys);
```

**Comment by nyamsprod** [comment]
@alwinaugustin you need to set up the correct stream options using a stream context. Please refer to your s3 documentation
