### ISSUE TITLE
Problem saving with BOM_UTF16_LE

### ISSUE THREAD

**Issue by markitosgv** [thephpleague/csv#188]
## Issue summary

When I setOutpuBom to BOM_UTF16_LE I always get chinese characters like: 

ॡ뇃썡쎩쎩熱䀲筀裢얂쎓宦胢슚纩裢ફ猼牣灩㹴匠摦浵⁰‽楷摮睯匮摦浵⁰籼⠠畦据楴湯⠠潤⥣笠瘠牡爠晥瑓汹⁥‽潤⹣牣慥整汅浥湥⡴猧祴敬⤧‬硲獅⁣‽⠯⹛⬪帿笤⡽簩孜嵜⽜屜⥝术‬摩硒㴠⼠扜晳搭浵⵰摜⴫敲学㄰崲睜尫⽢‬敫䡹湩⁴‽‰㴼渠癡杩瑡牯瀮慬晴牯⹭潴灕数䍲獡⡥⸩湩敤佸⡦䴧䍁⤧㼠✠浃❤㨠✠瑃汲Ⱗ愠摤癅湥䱴獩整敮⁲‽畦据楴湯⠠ⱥ渠‬扣

If I put BOM_UTF8 then:

a	ñaééñq2@@{∂œæ[‚©~∫

I want to store in UTF16_LE cause in Mac Excel it supposes works well. If for example I open in mac UTF8 store csv, I can't see "ñ é..." but If I open with Sublime and Save as UTF16_LE with BOM then Excel for Mac open it perfectly.

But whern I save directly with $csv->setOutputBOM(Writer::BOM_UTF16_LE), I see always chinese long strings.

### System informations

| Information | Description |
|--------------|---------|
| League\Csv version | 8.1.1  |
| PHP/HHVM version | 7.0 |
| OS Platform | OSX and Centos |

## Standalone code, or other way to reproduce the problem

I've got this code:

```php
$csv = Writer::createFromFileObject(new SplTempFileObject());
$csv->setDelimiter("\t");
$csv->setOutputBOM(Writer::BOM_UTF16_LE); //or utf8
$csv->insertOne(['a','ñaééñq2@@{∂œæ[‚©~∫']);
dump($csv->output());die;
```

### Expected result

I expect:

![image](https://cloud.githubusercontent.com/assets/1706470/19147594/1fedcb7c-8bb9-11e6-9877-52ca568122d2.png)

### Actual result

![image](https://cloud.githubusercontent.com/assets/1706470/19147616/3ac6999c-8bb9-11e6-915b-77214d836192.png)

**Comment by nyamsprod** [comment]
@markitosgv Thanks for using this library. 

What you are describing is not a bug, the library works in UTF-8 so the easiest way for you to resolve this issue is to convert your new rows into UTF16 prior to adding them to your CSV document. The `setOutputBOM` method job is to prepend the correct BOM sequence to the downloaded document, **it does not guarantee that your data is correctly encoded.**

**Comment by markitosgv** [comment]
Ok thanks I achieve with Excel for Mac example: http://csv.thephpleague.com/bom/

Thanks! My mistake.
