### ISSUE TITLE
Platform issue or my code problem

### ISSUE THREAD

**Issue by Sat02** [thephpleague/csv#190]
## Issue summary

Plugin working fantastic  in windows platform but when I execute the same thing in Linux I am getting the following error 
Parse error: syntax error, unexpected '$row' (T_VARIABLE) in csv/src/Reader.php on line 226

on line 226 
following lines are there

protected function generatePairs(Iterator $iterator)
    {
        foreach ($iterator as $row) {
            yield $row[0] => $row[1];
        }
    }

### System informations

_(In case of a bug report Please complete the table below)_

| Information | Description |
|--------------|---------|
| League\Csv version |  |
| PHP/HHVM version |  |
| OS Platform |  |

## Standalone code, or other way to reproduce the problem

_(Please complete the text below to help us fix the issue)_

**Comment by nyamsprod** [comment]
@Sat02 what is your PHP/HHVM version and your version of the library ? I suspect you are using a incompatible versions

**Comment by Sat02** [comment]
Thank you so much
It's because of PHP version

**Comment by Sat02** [comment]
Thank you so much
It's because of PHP version
