### ISSUE TITLE
Move columns?

### ISSUE THREAD

**Issue by GaryJones** [thephpleague/csv#191]
## Issue summary

I've got a project that takes an export from one system, and imports into another. The order of columns in the exported CSV is different to what's needed for the importable CSV.

Is there / can there be a quick way of moving columns around, other than reading a file, looping through each row, and adjusting the [order of] keys in the row array?

**Comment by nyamsprod** [comment]
@GaryJones thanks for using the library.

About your issue since CSV document are treated as stream, there's no other way of doing it than how you describe your proposed solution.

**Comment by GaryJones** [comment]
Thanks for the confirmation :-)
