### ISSUE TITLE
Integer Strings..

### ISSUE THREAD

**Issue by SolStis86** [thephpleague/csv#192]
## Issue summary

I have a very annoying client who requires numbers less than 10 to be preceded by a 0, so 01, 02, 03....

Ive created the logic for this however when running $csv->insertOne(['01']), the field is populated with the single digit integer...

Is there a config i can change to fix this?

### System informations

_(In case of a bug report Please complete the table below)_

| Information | Description |
|--------------|---------|
| League\Csv version | 8.1.1  |
| PHP/HHVM version | 7.0  |
| OS Platform | centos 7 |

## Standalone code, or other way to reproduce the problem

$offer_no = $offer_no < 10 ? '0' . $offer_no : $offer_no;

$csv->insertOne([
                (string) $offer_no,
                ...

**Comment by nyamsprod** [comment]
here's what I did 
```php
use League\Csv\Writer;

$writer = Writer::createFromFileObject(new SplTempFileObject());
$writer->insertOne([1, '01', '001']);
echo $writer, PHP_EOL;
```
And I do get this
```
1,01,001
```

Something else must be wrong in your settings.
