### ISSUE TITLE
Testing-Mocking Package

### ISSUE THREAD

**Issue by vrubiella** [thephpleague/csv#193]
## Issue summary

This package has wonderfull funcionallity but is so difficult to integrate on test process. 

**Reader::createFrompath** is an static method (impossible to mock on new phpunit versions).

Constructor requires file path and it's not possible to define later, also  it's so difficult integrate in a  dependence injection container. 

It would be interesting to have an empty constructor and setter methods to define path and other options.

| Information | Description |
|--------------|---------|
| "league/csv" : "8.1.2"|  |
| PHP 7 |  |
| Alpine 3.3 |  |

**Comment by nyamsprod** [comment]
@vrubiella thanks for using the library but I don't get your problem. The library comes bundles with a test suite that does test for named constructors, so why trying to mock the named constructors ?
Last but not least what you are suggesting was implemented in earlier versions of the library and led to too many issues that were all resolve with the use of named parameters.

**Comment by vrubiella** [comment]
@nyamsprod maybe i'm wrong, but, I don't like create class wrappers only for testing purposes.

For example, I have a method that loads CSV data to database, csv path:

```php
function loadDataFromCSV(string $csvPath)
{
  // ... code here
  $csvObj = Reader::createFromPath($csvPath);

 //... code here
}
```

When I was testing (unit testing) *loadDataFromCSV* method, I just test that createFromPath method is called with $csvPath, I don't want execute Reader method.

Something like these:

```php
 $this->createMock('Reader')->expects($this->once())
->method('createFromPath')
->with($csvDummyPath)
->willReturn($dummyReader);
```

Maybe there are another way to do this test unit ? (without creating a wrapper class containing Reader calls)

**Comment by nyamsprod** [comment]
@vrubiella if you are on PHP7 I'd suggest using [anonymous class](https://secure.php.net/manual/en/language.oop5.anonymous.php) or I would change the function signature to 

```php
function loadDataFromCSV(Reader $csvPath)
```
This would ensure that your fonction does not do multiple things and enable your function to work with all possible range of CSV source IMHO

**Comment by vrubiella** [comment]
@nyamsprod so, this solutions it's good for solve problem in "loadDataFromCSV", but externalices the problem to method who calls to "loadDataFromCSV". 

In my opinion, testing we shouldn't acces to real filesystem or real files.

**Comment by nyamsprod** [comment]
if you are so afraid of touching the filesystem then maybe use this https://packagist.org/packages/mikey179/vfsStream 👍 .

**Comment by vrubiella** [comment]
ok, closing issue.
