### ISSUE TITLE
Limit is reset after each fetch

### ISSUE THREAD

**Issue by alxy** [thephpleague/csv#201]
I'm not sure if this behavior is intended or a bug, but I realized I always need to set the ``limit`` again after I call ``fetchAll``.

Why isn't the limit parameter left as is?

**Comment by nyamsprod** [comment]
This is not a bug but the behavior will be decoupled from the Reader class in the next major so that the limit parameter is not reset between calls see #178

**Comment by alxy** [comment]
Thanks, that looks promising!
