### ISSUE TITLE
Please use resources internally instead of SplFileObject instances.

### ISSUE THREAD

**Issue by frankdejonge** [thephpleague/csv#202]
## Issue summary

Due to the need to use SplFileObject instances internally any input it required to be compatible with the restrictions said class puts in them. Every SplFileObject method we call has a function counterpart. The only thing we actually use is the iterative capabilities of the object. This could/should be replaces with an own implementation.

If we accomplish this we achieve a higher level of interoperability, we're able not only to work with local files but also with resources from remote locations, which is, by any definition, simple "the shit".

----------

### System informations

| Information | Description |
|--------------|---------|
| League\Csv version | next |
| PHP/HHVM version | any |
| OS Platform | dna |

## Standalone code, or other way to reproduce the problem

Try to use the existing package with a resource and weep.

### Expected result

More interoperability

### Actual result

A sad face because it's not yet at this level of awesomeness.

**Comment by nyamsprod** [comment]
This issue is resolved in the master branch ... rejoice my friend as the answer is being review for release
