### ISSUE TITLE
How to write to a file with BOM?

### ISSUE THREAD

**Issue by ZWalrus** [thephpleague/csv#204]
## Issue summary
I could not write a content directly to a file with BOM.
What I do:
```
    $writer = Writer::createFromPath($fileOut);
    $writer->setOutputBOM(Writer::BOM_UTF8);
    $writer->setDelimiter(";");
    $writer->insertAll($data);
```
I got the file without BOM in the beginning;
But I get it with BOM only after one more step:
`    file_put_contents($fileOut, (string)$writer);`
Perhaps I missed anything?
Thank you.

**Comment by nyamsprod** [comment]
No you did not miss anything ... BOM is only added if you output the data somewhere using the __toString is one method to do so.

**Comment by ZWalrus** [comment]
OK. Thank you for the answer! I like this tool, very cool!
