### ISSUE TITLE
League\Csv\Reader::fetchAssoc being depreciated.

### ISSUE THREAD

**Issue by thinkstylestudio** [thephpleague/csv#206]
## Issue summary

I was wondering what function I should be reaching for to replace the soon to be removed League\Csv\Reader::fetchAssoc? 

### System informations

_(In case of a bug report Please complete the table below)_

| Information | Description |
|--------------|---------|
| League\Csv version |  8.2.0  |
| PHP/HHVM version |  |
| OS Platform |  |

## Standalone code, or other way to reproduce the problem

Example of what I'm doing with it. 

```php
<?php

  $typeResultsFiltered = $this->fetchSingleColumn($reader, 78); // Atis Types
        $typeResultsFiltered->each(function ($value) {
            $contentType               = new Type();
            $contentType->content_type = $value;
            $contentType->save();
        });
        $results = $reader->fetchAssoc($this->csvKeys);
        $results = collect(iterator_to_array($results, false));
        //dd($results);
        $filteredResults = $results->filter(function ($value, $key) {
            //dump();
            return $key >= 4;
        })->reject(function ($value) {
            return empty($value["Name"]);
        });
```

**Comment by nyamsprod** [comment]
The [v9 public API is almost complete](https://gist.github.com/nyamsprod/b9fac96126a40185bff48b0c3c5c4529). One or Two methods names may change and one method may be dropped but everything else is there.

**Comment by mbrodala** [comment]
Thanks for the heads up. Maybe a hint on every deprecation in the could could be useful here.

**Comment by nyamsprod** [comment]
these hint will be put into the documentation when the upgrading pages for the next major release are written.
