### ISSUE TITLE
fetchAssoc() fails with freshly created Reader

### ISSUE THREAD

**Issue by shadowhand** [thephpleague/csv#213]
## Issue summary

I need to pre-process a CSV file that was given to me that contains a number of columns with duplicate names. In order to process this file I am creating a reader, writing some columns with a writer, and then getting a reader:

```php
$reader = Reader::createFromPath('path/to/file.csv');
$write = Writer::createFromStream(fopen('php://temp', 'r+'));
$columns_to_extract = [1, 2, 3, 4, 5, 43];

foreach ($reader->fetch() as $row) {
    $write->insertOne(array_intersect_key($row, $columns_to_extract));
}

$reader = $write->newReader()->setOffset(0);
```

And then I pass the `$reader` into another class that uses `fetchAssoc()`:

```php
function process(Reader $csv)
{
    foreach ($csv->fetchAssoc() as $row) {
        // do stuff with row
    }
}
```

This works fine for other CSVs, but as soon as I add this pre-processing step, I get the following error:

```
InvalidArgumentException: the specified row does not exist or is empty in importer/vendor/league/csv/src/Reader.php on line 338

Call Stack:
    0.0002     233496   1. {main}() importer/bin/import:0
    0.0255    1522728   2. League\Csv\Reader->fetchAssoc() importer/bin/import:17
    0.0255    1522928   3. League\Csv\Reader->getAssocKeys() importer/vendor/league/csv/src/Reader.php:247
    0.0255    1523208   4. League\Csv\Reader->getRow() importer/vendor/league/csv/src/Reader.php:281
```

### System informations

_(In case of a bug report Please complete the table below)_

| Information | Description |
|--------------|---------|
| League\Csv version | 8.2.0 |
| PHP/HHVM version | 5.6.29 |
| OS Platform | osx  |

## Standalone code, or other way to reproduce the problem

*See description.*

### Expected result

No error.

### Actual result

Exception thrown.

**Comment by shadowhand** [comment]
Applying the following patch resolves the issue:

```diff
--- src/Reader.php	2017-02-21 10:51:56.000000000 -0600
+++ src/Reader.php	2017-02-21 10:51:52.000000000 -0600
@@ -329,7 +329,7 @@
     protected function getRow($offset)
     {
         $fileObj = $this->getIterator();
-        $fileObj->setFlags(SplFileObject::READ_AHEAD | SplFileObject::SKIP_EMPTY);
+        $fileObj->setFlags(SplFileObject::READ_CSV | SplFileObject::READ_AHEAD | SplFileObject::SKIP_EMPTY);
         $iterator = new LimitIterator($fileObj, $offset, 1);
         $iterator->rewind();
         $line = $iterator->current();
```

**Comment by shadowhand** [comment]
For whatever reason, the following code works:

```php
foreach ($reader->fetch() as $row) {
    $write->insertOne(array_intersect_key($row, $columns_to_extract));
}

$reader = Reader::createFromString((string) $write);
```

**Comment by nyamsprod** [comment]
@shadowhand it works because the latter uses `SplTempFileObject` while the first example uses a userland `StreamIterator` to enable `Writer::createFromStream`. I'll review your fix and merge it since I have to release a patch version with other fixes hopefully later this week or next week.

**Comment by shadowhand** [comment]
My "fix" appears to break other things. :) I'll trust you can sort it out.

**Comment by nyamsprod** [comment]
@shadowhand while waiting for the patch in your code if you change 
```
$write = Writer::createFromStream(fopen('php://temp', 'r+'));
//by
$write = Writer::createFromFileObject(new SplTempFileObject());
```
It will work.

**Comment by nyamsprod** [comment]
@shadowhand the PR #215 should fix your code could you try it please if it's ok for you I'll release the patch

**Comment by nyamsprod** [comment]
version 8.2.1 is out with the fix

**Comment by shadowhand** [comment]
Just confirmed that this fix works. Thanks!
