### ISSUE TITLE
->output creating empty first row

### ISSUE THREAD

**Issue by stephenvicino** [thephpleague/csv#217]
## Issue summary

When creating a file to output as CSV, its insertting a blank first row above the header

## Standalone code, or other way to reproduce the problem

$csv = Writer::createFromFileObject(new SplTempFileObject());

//we insert the CSV header
$csv->insertOne($header);

// The PDOStatement Object implements the Traversable Interface
// that's why Writer::insertAll can directly insert
// the data into the CSV
$csv->insertAll($contents);

// Because you are providing the filename you don't have to
// set the HTTP headers Writer::output can
// directly set them for you
// The file is downloadable

header('Content-Disposition: attachment; filename="User-List-'.date("Y-m-d").'.csv"');

$csv->output('User-List-'.date("Y-m-d").'.csv');

I have tried just using the insertOne($header); this is the $header 
    $header = ["Email", "First Name", "Last Name", "Phone Number", "Company", "DOB", "Tags"];

**Comment by nyamsprod** [comment]
@stephenvicino
- why adding twice the HTTP header if you want to have specific header for that ? Maybe the error comes from that ?
- have you checked the data you are inserting ?

**Comment by nyamsprod** [comment]
> why adding twice the HTTP header if you want to have specific header for that ? Maybe the error comes from that ?

**Comment by stephenvicino** [comment]
Where is it being added twice? I am a bit confused on this.

**Comment by nyamsprod** [comment]
http://csv.thephpleague.com/basic-usage/#outputting-the-csv it is explained in the documentation

**Comment by stephenvicino** [comment]
I revised my code but still having the issue:

$csv = Writer::createFromFileObject(new SplTempFileObject());

$csv->insertOne($header);

$csv->insertAll($contents);

header('Content-Type: text/csv; charset=UTF-8');
header('Content-Disposition: attachment; filename="User-List-'.date("Y-m-d").'.csv"');

$csv->output();

**Comment by nyamsprod** [comment]
then it means you have a problem with your contents :)

```php
$csv = Writer::createFromFileObject(new SplTempFileObject());
$csv->insertOne(['head 1', 'head 2', 'head 3']);
$csv->insertAll([
    ['a', 'b', 'c'],
    ['e', 'f', 'g'],
]);

header('content-type: text/csv; charset=utf-8');
header('content-disposition: attachment; filename="User-List-'.date("Y-m-d").'.csv"');
$csv->output();
```

This works for me as expected. If it does then it means it's your data at fault

**Comment by stephenvicino** [comment]
I copied your code and I still got a blank first row.

**Comment by nyamsprod** [comment]
This means that you are already outputting a blank line prior to using the `output` method in your script. The blank line is not added by the library

**Comment by nyamsprod** [comment]
I'm closing this issue as it is not related to the package in itself.

**Comment by kumar1010sumit** [comment]
I have same issue. And its a real issue. I used Ubuntu 18.04

**Comment by 201294** [comment]
you have to make your output buffer empty before inserting the data to it, use   ob_clean(); method before $csv->insertOne(['head 1', 'head 2', 'head 3']);
$csv->insertAll 
thats all you have to do

**Comment by az33m** [comment]
> you have to make your output buffer empty before inserting the data to it, use ob_clean(); method before $csv->insertOne(['head 1', 'head 2', 'head 3']); $csv->insertAll thats all you have to do

Worked for me. Thanks.
