### ISSUE TITLE
UTF-8 BOM is not stripped

### ISSUE THREAD

**Issue by cdarken** [thephpleague/csv#218]
I have a CSV file that used UTF-8 BOM. Even if I activate the option to remove the bom, it breaks my headers row.

The issue seems a lot like #102 because if I quote the headers column, the quotes are not removed.

### System informations

_(In case of a bug report Please complete the table below)_

| Information | Description |
|--------------|---------|
| League\Csv version | 8.2.1  |
| PHP/HHVM version | 5.6.30  |
| OS Platform | Ubuntu 14.04  |

```
$csv = Reader::createFromPath($file);
$csv->stripBom(true);
foreach ($csv->fetchAssoc() as $row) {
        print_r ($row);
}
```

[Sample file](https://github.com/thephpleague/csv/files/824072/withbom.txt)

**Comment by nyamsprod** [comment]
I fail to reproduce your bug ? With the file you are providing. I get the following result

```php
$csv = Reader::createFromPath('withbom.txt', 'r');
$csv->setDelimiter(';');
$csv->stripBom(true);
foreach ($csv->fetchAssoc() as $row) {
    var_dump($row);
}
echo $csv, PHP_EOL;
```

```php
array(3) {
  'ID' => //no BOM found on the ID key
  string(1) "1"
  'NAME' =>
  string(2) "Me"
  'EMAIL' =>
  string(14) "me@example.com"
}
"ID";NAME;EMAIL  //the BOM is still present
1;Me;me@example.com
```

Are you sure about the issue ??

**Comment by cdarken** [comment]
Thanks for the response. Yes, I'm pretty sure. But give me a minute to just create a simple test outside of my project where I encountered the error.

**Comment by nyamsprod** [comment]
To be complete if you do the following
```php
$csv = Reader::createFromPath('withbom.txt', 'r');
$csv->setDelimiter(';');
$csv->stripBom(true);
foreach ($csv as $row) {
    var_dump($row); //the BOM sequence IS NOT removed
}
```
The BOM sequence **won't be stripped**  because your are calling the inner Iterator without any extraction. Instead you are require to use one of the extract methods to enure the stripping mechanism is used:

```php
$csv = Reader::createFromPath('withbom.txt', 'r');
$csv->setDelimiter(';');
$csv->stripBom(true);
foreach ($csv->fetch() as $row) {
    var_dump($row); //the BOM sequence is removed
}
```

**Comment by cdarken** [comment]
I'm using fetchAssoc() as I specified. That classifies as an extract method, right?
The thing is, in a fresh test, just using league/csv, the BOM is stripped. But in my project, even though I use exactly the same code, it isn't. Does it matter if it's an uploaded file? It shouldn't, right?

**Comment by nyamsprod** [comment]
@cdarken no it should not matter.

**Comment by cdarken** [comment]
Umm, if I call fetchOne before calling fetchAssoc, the stripping will not happen? Because I think that's the case.

**Comment by nyamsprod** [comment]
@cdarken Ok I understand now. You must **always** call stripBOM before each extract method call. This is why I changed the behavior in the upcoming version because having to call the stripBOM method each time is kind of stupid :) .

**Comment by cdarken** [comment]
Ok. Got it. Is it specified in the docs that now we should call it each time? If so, I have no way of knowing because the phpleague site is down.
Thanks for the help.

**Comment by nyamsprod** [comment]
@cdarken yes it is specified... 
you can still access the docs on the master branch. Here's the relevant part
https://github.com/thephpleague/csv/blob/master/docs/query-filtering.md#query-filters
