### ISSUE TITLE
Cannot read CSV file directly from AWS S3

### ISSUE THREAD

**Issue by bs-thomas** [thephpleague/csv#222]
## Issue summary

Not allowing me to fetch data when I use createFromPath to read the first line of the CSV file.

### System informations

_(In case of a bug report Please complete the table below)_

| Information | Description |
|--------------|---------|
| League\Csv version | 8.2.1 |
| PHP/HHVM version |  PHP 5.6.25 |
| OS Platform |  Windows 10 Pro |

## Standalone code, or other way to reproduce the problem

```
// Create the stream wrapper
$s3Client = \Aws\S3\S3Client::factory(array(
            'version' => 'latest',
            'region' => $region,
            'credentials' => array(
                'key'    => $key,
                'secret' => $secret,
            ),
        ));
$s3Client->registerStreamWrapper();

// Now read the data 
$reader = \League\Csv\Reader::createFromPath($filePath, 'r');
$headers = $reader->fetchOne();
```

### Expected result
Can get the first row of the data.

### Actual result

RuntimeException in Reader.php line 120:
Cannot rewind file s3://beamstyle-web-01/clients/www.polyauction.com.hk-localhost/auction/import/lots/import_lots_data_97d9b5e8-b659-4435-9e7f-640afbc19174.csv

**Comment by bs-thomas** [comment]
At the repository https://github.com/aws/aws-sdk-php/ at AWS end, I got assistance from@jeskew and got the following working code.  Thank you!

```
// Create the stream wrapper
$s3Client = \Aws\S3\S3Client::factory(array(
            'version' => 'latest',
            'region' => $region,
            'credentials' => array(
                'key'    => $key,
                'secret' => $secret,
            ),
        ));
$s3Client->registerStreamWrapper();

$context = stream_context_create(array(
    's3' => array(
        'seekable' => true
    )
));

$stream = fopen($filePath, 'r', false, $context);
$reader = \League\Csv\Reader::createFromStream($stream);
```

**Comment by fernandocoronatomf** [comment]
@bs-thomas Thanks, it worked for me as well. But does anybody have any idea why? I don't understand why seekable => true allows me to stream the first line

**Comment by quevlu** [comment]
@fernandocoronatomf @bs-thomas It's been a long time, but I have a question. In $filePath what type of value is ?

**Comment by quevlu** [comment]
I've found some samples. I'll try it later

https://gist.github.com/jeremeamia/042254f6fe2982745b03

https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-stream-wrapper.html

https://github.com/box/spout/issues/673

**Comment by quevlu** [comment]
I could do it.

```
$file = $event->file();
        $companyId = $event->companyId();

        $s3Client = Storage::s3()->getDriver()->getAdapter()->getClient();
        $s3Client->registerStreamWrapper();

        $filesystemDriver = config('filesystems.default');

        $context = stream_context_create([
            's3' => [
                'seekable' => true,
            ],
        ]);

        $s3Path = 's3://' . config("filesystems.disks.{$filesystemDriver}.bucket") . '/' . $file->relativePath();

        $stream = fopen($s3Path, 'r', false, $context);

        $reader = Reader::createFromStream($stream);
        foreach ($reader->chunk(1024) as $chunk) {
            dd($chunk);
        }
```

**Comment by natsu90** [comment]
I had the same problem and had to use this workaround

````
$content = file_get_contents($filePath);
$reader = Reader::createFromString($content);
````

**Comment by bs-thomas** [comment]
> @fernandocoronatomf @bs-thomas It's been a long time, but I have a question. In $filePath what type of value is ?. I've been working with a full url from a fake s3 (minio). I've seen some samples with s3 protocol.

Sorry for the delayed reply.  It was in the form of s3://bucketName/and/your/path.pdf

**Comment by bs-thomas** [comment]
> I had the same problem and had to use this workaround
> 
> ```
> $content = file_get_contents($filePath);
> $reader = Reader::createFromString($content);
> ```

You're going to crash your server if the file is bigger.
