### ISSUE TITLE
how to remove the strlen from csv output?

### ISSUE THREAD

**Issue by PsychicCat** [thephpleague/csv#227]
Very simple question: how do I remove the strlen when I do `$writer->output()`?

It gives me the csv string but then also an int like `100` which would be the strlen of that csv. I cannot find anything in the documentation on how to get rid of this...?

**Comment by nyamsprod** [comment]
@PsychicCat why do you want to remove it ? the output method works like php [fpassthru](http://php.net/fpassthru) you should just die after using it

**Comment by PsychicCat** [comment]
@nyamsprod It's ending up as an extra row on my CSV file. Am I doing something wrong? 

```
        $csv = Writer::createFromFileObject(new \SplTempFileObject());
            $csv->insertOne(array_keys(get_object_vars($report[0])));
            foreach ($report as $row) {
                $csv->insertOne(get_object_vars($row));
            }
            return $csv->output();
```
