### ISSUE TITLE
Documentation is invalid or outdated

### ISSUE THREAD

**Issue by Dumk0** [thephpleague/csv#228]
## Issue summary

I went to http://csv.thephpleague.com/ for full documentation reference. The very first sample script is absolutely not working.

> Reader, the read only connection object enables accessing CSV records easily
```php
<?php
use League\Csv\Reader;

//load the CSV document from a file path
$csv = Reader::createFromPath('/path/to/your/csv/file.csv');
$csv->setHeaderOffset(0);

$header = $csv->getHeader(); //returns the CSV header record
$records = $csv->getRecords(); //returns all the CSV records as an Iterator object

echo $csv; //returns the CSV document as a string
```

None of the methods setHeaderOffset, getHeader, getRecords exists in the library 8.2.1

Please update the documentation and/or add in to the project repo.

**Comment by nyamsprod** [comment]
@Dumk0 nothing is wrong with the documentation. v9 will be released soon, so the website has been updated accordingly. On the link you've provided you have access to all documentation for each version (v9, v8 and even the no-longer supported v7)

**Comment by Dumk0** [comment]
Okay, my bad. I was looking into FEATURES block I didn't scroll to the end to see that there are links to different version documentation. IMHO from UX point of view it would be better to show links to documentation on top of web page and have the link to correct version of docs in the README.md
