### ISSUE TITLE
enclosure Random behaivor

### ISSUE THREAD

**Issue by pardalsalcap** [thephpleague/csv#235]
## Issue summary

Hi, Sorry but my english is not so good.
I have some issues with the enclosure deature, it randomely applies que enclosure, here is an example

It seems it needs an space " " to add the field enclosure

## Standalone code, or other way to reproduce the problem

```
// The header
$writer = Writer::createFromPath($path, 'w+'); // a+
$writer->setDelimiter(",");
$writer->setEnclosure('"');
$writer->insertOne([
   Lang::get("diccionarios.dic43"),
   Lang::get("diccionarios.dic870"),
   Lang::get("diccionarios.dic29"),
   Lang::get("diccionarios.dic31"),
   Lang::get("diccionarios.dic729")
]);

foreach ($references as $item)
{
   $writer->insertOne([
                        (string)$item->code.$item->colour,
                        (string)utf8_decode($item->title),
                        (string)utf8_decode($item->name),
                        (string)utf8_decode($stocktxt),
                        (string)utf8_decode($previsiontxt)
                    ]);
}
```

### Expected result

"Referencia","Descripción","Color","Stock","Fecha prevista"
"0009T","Bombillas","Naranja ","6",""

### Actual result
Referencia","Descripción ",Color,Stock,"Fecha prevista "
0009T,"Bombillas ","Naranja ",6,

### With a dummy space 

```
// The header
$writer = Writer::createFromPath($path, 'w+'); // a+
$writer->setDelimiter(",");
$writer->setEnclosure('"');
$writer->insertOne([
   Lang::get("diccionarios.dic43")." ",
   Lang::get("diccionarios.dic870")." ",
   Lang::get("diccionarios.dic29")." ",
   Lang::get("diccionarios.dic31")." ",
   Lang::get("diccionarios.dic729")." "
]);

foreach ($references as $item)
{
   $writer->insertOne([
                        (string)$item->code.$item->colour." ",
                        (string)utf8_decode($item->title)." ",
                        (string)utf8_decode($item->name)." ",
                        (string)utf8_decode($stocktxt)." ",
                        (string)utf8_decode($previsiontxt)." "
                    ]);
}
```
### Result with dummy space
"Referencia ","Descripción ","Color ","Stock  ","Fecha prevista "
"0009T ","Bombillas   ","Naranja ","6 "," "

**Comment by nyamsprod** [comment]
@pardalsalcap this question has already been answered in the issue tracker please refer to #113

**Comment by pardalsalcap** [comment]
Yes thats a solution. Thanks!

Anyway I think that the setEnclosure() method should be mandatory. I mean if setEnclosure('"') all fileds must have "xxxx", "cccc", "aaaaa" 

But maybe I'm missing something.

Thanks anyway
