### ISSUE TITLE
Issue when csv contains characters like 'é'

### ISSUE THREAD

**Issue by gerald27** [thephpleague/csv#236]
## Issue summary

There's an extra characters when outputting letters with symbol
example char: é

### System informations

| Information | Description |
|--------------|---------|
| League\Csv version | 7.1.* |
| PHP/HHVM version | 7.1 |
| OS Platform | Windows7  |

## Standalone code, or other way to reproduce the problem

$reader = Reader::createFromPath($file->getRealPath());
$reader->setOutputBOM(Reader::BOM_UTF8);
return $reader->fetchAll();

### Expected result

[0 => "ééééé"]

### Actual result
[0 => b"ééééé"]

**Comment by nyamsprod** [comment]
@gerald27 League\Csv 7.* is not supported anymore do you get the same result with League\Csv 8.x ?

**Comment by gerald27** [comment]
@nyamsprod yes still the same result using League\Csv 8.x.

**Comment by nyamsprod** [comment]
@gerald27 could you provide the source data or a small part of if so that I could reproduce the bug, if it is a bug If I can't reproduce it I can investigate it :)

**Comment by nyamsprod** [comment]
I believe this is not a bug could you change your code to this 

````php
$reader = Reader::createFromPath($file->getRealPath());
return $reader->stripBOM()->fetchAll();
```
League v8 and before does not remove automatically the BOM string from the first field of the first record. You need to explicitly call the stripBOM method. before any call to any extract method. 

By the way this behaviour will be fix in the next major release 👍

**Comment by gerald27** [comment]
I have change my code to that but still the same issue. 

Result: [![image](https://user-images.githubusercontent.com/9834829/27170372-3e09d9c8-51e0-11e7-8cad-7dfbef5ae03d.png)](url)

Csv: [https://www.dropbox.com/s/0z651wlnpada44d/list3.csv?dl=0](url)

Thanks.

**Comment by nyamsprod** [comment]
The file I received was in `iso-8859-1` so I did the following:

```php
$csv = Reader::createFromPath('test.csv', 'r');
$csv->appendStreamFilter('convert.iconv.ISO-8859-1/UTF-8//TRANSLIT');
var_dump($csv->fetchAll());
```

No extra characters was shown, before and after but the data was correcly converted to UTF-8

**Comment by gerald27** [comment]
Thanks for the help, it's working great now.
