### ISSUE TITLE
Nulls value in CSV

### ISSUE THREAD

**Issue by davidbonachera** [thephpleague/csv#237]
## Issue summary

It's more a feature request / question than an issue. When you export CSV from SQL statement, you may have rows like that : 

`Firstname;Lastname;NULL;NULL;Age;`

I'm wondering if this parser (Reader part) could strip out the NULLs string and put it blank like that : 

`Firstname;Lastname;;;Age;`

It will avoid checking if each value is "NULL" and also it may avoid persisting a value that shouldn't be ?

**Comment by nyamsprod** [comment]
if you are importing from SQL to CSV then you are using the Writer class :) . If you are using the Writer class then you can use the Writer::addFormatter to convert NULL to the empty string c[heck the documentation for that](http://csv.thephpleague.com/8.0/inserting/#row-formatting).

if you are exporting from CSV to SQL using the Reader class. When using for instance the [Reader::each](http://csv.thephpleague.com/8.0/reading/#readereach) method nothing prevents you to format your data prior to inserting it in the database.

**Comment by davidbonachera** [comment]
Sorry I haven't been clear. I mean that I got my csv after my SQL request then I have to parse this csv with the reader class and then I do some transformation.

**Comment by nyamsprod** [comment]
The Reader enables you to access your data, how you choose to format or transform the returned CSV records is up to your script/business logic and therefore is out of scope for this library.

**Comment by davidbonachera** [comment]
So to be clear, in the case where the Reader sees a NULL in a csv row, it should read it as a "NULL" string ? 

And in your opinion, my script should first clean the CSV and those "NULL", then it should use the Reader, then it should process the data ?

**Comment by nyamsprod** [comment]
no you can directly format or transform your record as the Reader returns it using a function which accept the Reader returned record and transform it according to your needs

**Comment by davidromani** [comment]
Hi, sorry if this is not the right place to ask my question, but it seems that the issue title fits with my case.

I must read a CSV exported from MySQL and it seems that there are strange "\N" string values in some columns that I suspect that are representing null reference values. 

My problem is that when I try to use the CastToInt isn't working because I don't know how to pre-transform this "\N" into a nullable integer.

**Comment by nyamsprod** [comment]
@davidromani please open a different ticket as you are asking on a 2017 issue a question about a feature introduce in the late 2023. Clearly that would make it harder for anyone to understand the relation between both issues.
