### ISSUE TITLE
unable to install thephpleague version 8.0 and 7.0

### ISSUE THREAD

**Issue by arnacmj** [thephpleague/csv#238]
I have php version of 7.0 but when I try to install version 8.0 thephpleague/csv it complain and it needs a minimum version of php 7.1 same with version 7.0

### System informations

Problem 1
    - This package requires php >=7.1 but your PHP version (7.0.10) does not satisfy that requirement.

**Comment by nyamsprod** [comment]
this has nothing to do with version 8.0. v8 requires PHP5.5. It must be another package.

**Comment by arnacmj** [comment]
Maybe you should try it to your self sir,

"league/csv": "8.0",

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php >=7.1 but your PHP version (7.0.10) does not satisfy that requirement.

**Comment by arnacmj** [comment]
Im wondering in documentation required minimum version of PHP 5.5 in version 8.0?

**Comment by nyamsprod** [comment]
> Maybe you should try it to your self sir,

This package has been developed in PHP5. Please look at your composer.json and stop making assumption without testing. [This package is tested from PHP5.5 -> PHP7.1](https://travis-ci.org/thephpleague/csv/builds/204510725)

**Comment by arnacmj** [comment]
I got to change my php version to 7.1.16 and everything works find,

**Comment by arnacmj** [comment]
Anyways @nyamsprod  thank you for immediate response.
