### ISSUE TITLE
Uncaught BadMethodCallException: League\Csv\Reader::fetchAssoc() method does not exist

### ISSUE THREAD

**Issue by Fabbio86** [thephpleague/csv#239]
## Issue summary

Good day! I did not install Csv via composer but still it's running more or less. The only method I can't seem to find is fetchAssoc. Do you have any idea about what I could be doing wrong? I just downloaded the files from github and changed the namespace.

**Comment by nyamsprod** [comment]
@Fabbio86 I believe the issue is that you have downloaded the master instead of downloading one the release tag. I've updated the [documentation website with that information](http://csv.thephpleague.com/8.0/installation/#going-solo).

Hope this answer your question.
