### ISSUE TITLE
Allow empty enclosure and escape.

### ISSUE THREAD

**Issue by andersonamuller** [thephpleague/csv#24]
Would it be possible to allow a empty string when setting the enclosure and the escape char? A client has a special format that, for some reason, should not differentiate any chars between the delimiter. 

``` php
    public function setEnclosure($enclosure = '"')
    {
        if (1 != mb_strlen($enclosure)) {
            throw new InvalidArgumentException('The enclosure must be a single character');
        }
        $this->enclosure = $enclosure;

        return $this;
    }
```

``` php
    public function setEscape($escape = "\\")
    {
        if (1 != mb_strlen($escape)) {
            throw new InvalidArgumentException('The escape character must be a single character');
        }
        $this->escape = $escape;

        return $this;
    }
```

**Comment by dakira** [comment]
@nyamsprod Hi. I'd like to re-open this bug. I need to be able to write CSV with no enclosures. I have no control over the importing app and the latter won't work with CSV files using enclosures.

While RFC 4180 exists, there is no official standard for writing CSV. Also, RFC 4180 defines the usage of enclosures as a SHOULD requirement which allows for not using them.

**Comment by gocsp** [comment]
i had really trouble with no enclosure, but i found a hack (for writing): 

`
$writer->setEnclosure(chr(0))
`

**Comment by nyamsprod** [comment]
@dakira I believe you can have a safe workaround using this technique

**Comment by jsandeo** [comment]
It is not a requirement of the CSV standard to have a field enclosed just because there are whitespaces in it:

[See how "Grand Cherokee" is represented in this example](https://en.wikipedia.org/wiki/Comma-separated_values#Example)

Is there a way to tell a writer not to enclose a field just because it has whitespaces?

**Comment by nyamsprod** [comment]
yes you could use [stream filters](http://csv.thephpleague.com/filtering/) for instance to achieve this

**Comment by edgreenberg** [comment]
It should be noted that once you change the delimiter (to a TAB for instance) there is no need for enclosure around spaces or quote marks.    

Tab delimited files are pretty common, and it'd be nice to be able to write them (easily).

**Comment by underdpt** [comment]
I too think that it should allow for empty enclosures, it's simpler than having to write a workaround with streamfilter.

**Comment by nyamsprod** [comment]
Once again this is not a library limitation but a PHP limitation 👍 
http://php.net/manual/en/splfileobject.setcsvcontrol.php

**Comment by jsandeo** [comment]
I just switched to https://github.com/parsecsv/parsecsv-for-php
KISS

**Comment by neilcrookes** [comment]
Does anyone know of an example stream filter that results in values not being enclosed if they have a space?

**Comment by ezintz** [comment]
@nyamsprod I guess that you might be wrong. It does not seem to me to be a limitation of PHP..

```php
/**
         * Set the delimiter and enclosure character for CSV
         * @link http://php.net/manual/en/splfileobject.setcsvcontrol.php
         * @param string $delimiter [optional] <p>
         * The field delimiter (one character only).
         * </p>
         * @param string $enclosure [optional] <p>
         * The field enclosure character (one character only).
         * </p>
         * @param string $escape [optional] <p>
         * The field escape character (one character only).
         * </p>
         * @return void 
         * @since 5.2.0
         */
```

If I change the method call to to only pass a delimiter everything works fine.

**Comment by nyamsprod** [comment]
@ezintz since I don't know what I'm wrong about I can't help you. FWIW  this issue has been resolved in v9 so I don't really know what we are still discussing about.

**Comment by dakira** [comment]
@nyamsprod maybe just a mixup, but [in this comment](https://github.com/thephpleague/csv/issues/24#issuecomment-243147847) you stated that enclosures cannot be empty because PHP enforces them to be one character. What @ezintz is trying to say is that you can just omit enclosure and escape parameters (they're optional).

That said: Do I understand it correctly that your merged stream filter PR adds enclosures where they are missing to make stream data valid CSS before it gets parsed by the library?

**Comment by nyamsprod** [comment]
@dakira no you can not omit them, please read PHP documentation link in my previous comment, i you omit them PHP will use default values. 
For the fix again read the v9 documentation there are filters to help with interoperability. They do not resolve all PHP's shortcoming but they get around pretty much the most significant ones.

**Comment by nozavroni** [comment]
I don't know why you rely on PHP's functions anyway... you could get around this issue pretty easily by writing your own.

**Comment by nyamsprod** [comment]
@ezintz sorry to bring this to you but your are wrong the only thing the documentation tells you is that by default if no specific control is given PHP will fallback to the one discribed 
```
[ string $delimiter = "," [, string $enclosure = "\"" [, string $escape = "\\" ]]]
```
So not specifying them does not mean they are not set it only means that PHP will use the default value.

**Comment by nyamsprod** [comment]
a simple workaround is to extends SplFileObject and write your own SplFileObject:fputcsv method using SplFileObject::fwrite.  this is simple and clean... anything else will lead to unexpected errors... my 2 cents... or use another library that does not rely on PHP's native function to write CSV to the file.

**Comment by VaelVictus** [comment]
For those of us who cannot turn to another library and are cursed with this problem, I just built the CSV with League and iterated over it afterwards:

```
$fp = fopen('temp.csv', 'r');
        $final = fopen($filename, 'r+');
        while (($data = fgetcsv($fp)) !== FALSE) {
            // use fwrite over fputcsv because fputcsv requires an enclosure
            fwrite($final, implode(',', $data) . "\r\n");
        }
```

I simply could not get streams to register with League's CSV despite them being available in `var_dump(stream_get_filters());` . (Symfony may have been a factor)

**Comment by nyamsprod** [comment]
@vaelVictus since v9.2 you can use the empty string for escaping 😉 check the documentation website

**Comment by VaelVictus** [comment]
I did check the docs. And it says this, which matched what I got back from the library:

>The $sequence argument should be a sequence containing at least one character that forces fputcsv to enclose the field value. If not, an InvalidArgumentException exception will be thrown.

So let's check out that changelog:

>- Supports for PHP7.4 empty string for the escape character
>- Supports for empty string for the escape character with a polyfill for PHP7.4- versions.

Mmm, PHP 7.4. So `$csv->setDelimiter('');` will work for a version which is slated for stable release in November 2019. Perhaps someone in my position will have the fortune of being on 7.4 and using your library a year from now.

**Comment by nyamsprod** [comment]
> Supports for empty string for the escape character with a polyfill for PHP7.4- versions.

Lucky you a polyfill supports the behaviour for older version 😉

**Comment by VaelVictus** [comment]
Thank you. I apologize for my tone. So here's what I'm doing:

`use League\Csv\Polyfill\EmptyEscapeParser;`

`$csv = $csv->setEnclosure(" ");`
`$csv = $csv->setEnclosure("");`
`$csv = $csv->setEnclosure("\s");`

When I use ` `, I get spaces in my CSV, which is not ideal. I just need a truly blank character, I need to effectively strip double-quotes from the CSV. What am I doing wrong here?

**Comment by VaelVictus** [comment]
**Documentation exists in the polyfill itself:** https://github.com/thephpleague/csv/blob/master/src/Polyfill/EmptyEscapeParser.php

```
<code>
     $file = new SplFileObject('/path/to/file.csv', 'r');
     $it = EmptyEscapeParser::parse($file); //parsing will be done while ignoring the escape character value.
      foreach ($it as $record) {
          //fgetcsv is not directly use hence the escape char is not taken into account
      }
</code>
```

Unfortunately, it appears doing this means you lose access to the way you should truly be building CSVs with this library, things like `$csv->insertOne`. It's a lot easier to just build the CSV with the enclosures, but use it as a "temp CSV" which you'll then use like so:

```
$final = fopen($filename, 'w');
        while (($data = fgetcsv($fp)) !== FALSE) {
            // use fwrite over fputcsv because fputcsv requires an enclosure
            fwrite($final, implode(',', $data) . "\r\n");
        }
        fclose($final);

```

**Comment by nyamsprod** [comment]
@aarticianpc just out of curiosity the switch was done because of difficult support of the empty enclosure or of the empty escape character ? 🤔
