### ISSUE TITLE
csv output crashing without giving any error in case of more of 2000 values

### ISSUE THREAD

**Issue by shakisha** [thephpleague/csv#240]
## Issue summary

We cannot understand why our code is crashing without giving any error in case of more than 2000 values.

### System informations

| Information | Description |
|--------------|---------|
| League\Csv version |  8.2
| PHP/HHVM version |  5.6.30
| OS Platform |  centos 6.8

## Standalone code, or other way to reproduce the problem
           $csv = \League\Csv\Writer::createFromFileObject(new \SplTempFileObject());
            $csv->setEnclosure(" ");
            $csv->insertOne([
                    $value1,
                    $value2,
                    $value3,
                    $value4,
                    $value5
                ]);
        }
        \Log::info('Downloading csv');
        $csv->output($downloadFileName . '.csv' );
        exit;

### Expected result

Downloading file

### Actual result

Reloading the page without any kinda of error

**Comment by nyamsprod** [comment]
@shakisha did you try your script on a standalone page... because it is working for me. Maybe something else in your script is causing the memory error

**Comment by hakobsharabkhanyan** [comment]
Hi @nyamsprod . This is happening where there is about 1000 rows . The interesting thing that Logs reaching to the 'Downloading csv' , but instead of downloading, its showing 301 redirect in console . We tried also putting headers for forcing system to understand that its download and in csv format, but did not help .
Thanks for response

**Comment by nyamsprod** [comment]
>  but instead of downloading, its showing 301 redirect in console
if you have a redirection it is not an issue with the library here's what [Writer::output](https://github.com/thephpleague/csv/blob/fa8bc05f64eb6c66b96edfaf60648f022ecb5f55/src/Config/Output.php#L178-L187) ... as you can see there are no redirection involved... if you are using a framework you should not use output directly ... http://csv.thephpleague.com/8.0/basic-usage/#outputting-the-csv check the section about integration in a framework

**Comment by hakobsharabkhanyan** [comment]
Oh i see . thank you so much .

**Comment by shakisha** [comment]
Thank you guys! :-)
