### ISSUE TITLE
Values are null on columns above 50 entries

### ISSUE THREAD

**Issue by GPSies** [thephpleague/csv#242]
## Issue summary

I'm using the League library within a YII2 project. I'm getting always 'null', if I try to access rows array (columns) above an amount of 50.

Is there a limitation, that columns can only have an amount of 50? Or is there a setting, to set it to a larger value (e.g. to 60)?

### System informations

_(In case of a bug report Please complete the table below)_

| Information | Description |
|--------------|---------|
| League\Csv version | 8.2 |
| PHP/HHVM version | 5.6 |
| OS Platform | Win7 (developer workstation) |

## Standalone code, or other way to reproduce the problem

	$importFileCsv = Reader::createFromPath($model->questionImportFile->tempName);
	$importFileCsv->setOffset(1);
	$importFileCsv->setDelimiter(';');
	
	$results = $importFileCsv->fetchAll();
	
	foreach ($results as $row) {
		$itemId = $row[6];
		$year = $row[48];
		$variant = $row[52];
	}  	

### Expected result

$variant is not null
($itemId is ok, $year is ok)

### Actual result

$variant is null

**Comment by nyamsprod** [comment]
This is strange are you sure about your CSV document integrity? There are no limit at all in the library

**Comment by GPSies** [comment]
Hi,

after further analyses I detected the error in the file (my side). Your Library is working very well 👍 !

Thanks!
