### ISSUE TITLE
Problem writing a large file

### ISSUE THREAD

**Issue by AC-TimRourke** [thephpleague/csv#246]
## Issue summary

This is really more of a question. I'm trying to export very large sets of data to CSV using your excellent library and I'm running out of memory when calling `AbstractCsv::output`. I suspect I'm not familiar enough with PHP file handling to get this right without assistance, hoping you can help.

Here's the exception that is thrown when I try to output the file by calling, for example, `$csv->output('my_cool_file.csv');`:

```
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 860975104 bytes) in /path/to/project/vendor/league/csv/src/Config/Output.php on line 210
```

In the documentation, you mention that one might consider using a "Streaming Response" of some kind, but don't elaborate. In any event, my question is this:

_How does one properly stream output from the created CSV?_

Thanks!

### System informations

| Information | Description |
|--------------|---------|
| League\Csv version | 8.2 |
| PHP/HHVM version | 5.6 |
| OS Platform | CentOS 6 |

## Standalone code, or other way to reproduce the problem

_(Please complete the text below to help us fix the issue)_

**Comment by nyamsprod** [comment]
This is a documentation issue that has been resolved by [improving the documentation](http://csv.thephpleague.com/9.0/connections/output/#using-a-response-object-symfony-laravel-psr-7-etc)

**Comment by AC-TimRourke** [comment]
Thanks so much @nyamsprod! That really clears things up. :)

**Comment by AC-TimRourke** [comment]
@nyamsprod I have a follow-up question. I'm stuck on the 8.x branch because I must support PHP 5.6. Your example references a method, `AbstractCsv::chunk`, but that method does not exist in version 8.x. Is there a way to accomplish the same chunked output without using a generator?

https://github.com/thephpleague/csv/blob/9.0.0/src/AbstractCsv.php#L277

**Comment by nyamsprod** [comment]
a quick workaround would be to use a stream of a SplFileObject and once you have all your data use directly `fread` on them instead of  using the league object something around these lines. You **should** adapt the code 👍 

```php
<?php

$file= new SplTempFileObject();
$csv = Writer::createFromFileObject($file);
$csv->insertAll($data);
$csv = null;

$file->rewind();
while (!$file->eof()) {
 echo $file->fread(1024);
}
````

**Comment by AC-TimRourke** [comment]
Thanks again @nyamsprod! I made a PR to backport `AbstractCsv::chunk` to 8.x to make this simpler and line up with the Symfony `StreamingResponse` example you shared. 

https://github.com/thephpleague/csv/pull/248
