### ISSUE TITLE
Exception while send mail with attached csv file

### ISSUE THREAD

**Issue by 0l1v3r5** [thephpleague/csv#251]
## Issue summary

Exception 'TypeError' with message 'fclose() expects parameter 1 to be resource, integer given'

in vendor/league/csv/src/Stream.php (line 131) 

### System informations

League\Csv - ^9.0
PHP - PHP 7.1.8 (cli) (built: Aug  2 2017 08:32:24) ( NTS )
OS Platform - FEDORA 26

## Standalone code, or other way to reproduce the problem

$header = ['first', 'second', 'third'];
$records = [
    [1, 2, 3],
    ['foo', 'bar', 'baz'],
    ['john', 'doe', 'john.doe@example.com'],
];

//load the CSV document from a string
$csv = Writer::createFromString('');

//insert the header
$csv->insertOne($header);

//insert all the records
$csv->insertAll($records);

// Create the message 
$message = (new \Swift_Message())

// Give the message a subject
 ->setSubject('New')

  // Set the From address with an associative array
  ->setFrom(john2@example.com)

// ->setTo()
->setTo($this->getParameter('recipients'))

 // Give it a body
  ->setBody('new message.');

// Create the attachment with our data
 $attachment = (new \Swift_Attachment())
   ->setFilename('file.csv')
   ->setContentType('text/csv')
   ->setBody("$csv") ;

// Attach it to the message
 $message->attach($attachment);

 $this->get('mailer')->send($message);

### Expected result
send mail with attached csv file

### Actual result
mail sent but with exception

**Comment by nyamsprod** [comment]
This is fixed on the master branch you can clone it and see if you still get the error. If no error is shown I'll close this issue.

**Comment by 0l1v3r5** [comment]
Thank you! it's Ok. good job! you can close this issue.

**Comment by 0l1v3r5** [comment]
everything is ok. Good job. Sorry for closing. I had to let you close it. my bad.

**Comment by 0l1v3r5** [comment]
thank you.

**Comment by nyamsprod** [comment]
don't worry it was ok for me that you've close it 👍
