### ISSUE TITLE
excel export attacks ?

### ISSUE THREAD

**Issue by graemedewe** [thephpleague/csv#253]
## Issue summary

I am looking to strip/ammend strings that can be used in excel export attacks (https://www.slideshare.net/exploresecurity/camsec-sept-2016-tricks-to-improve-web-app-excel-export-attacks). I see there is  Reader::each() , but how do I modify the object with my call back to strip out any bad chars?

I'm looking to run something like this as a callback

```
 public static function escape_csv( $payload ) {
    $triggers = array( '=', '+', '-', '@', '|', '%');

    if ( in_array( mb_substr( $payload, 0, 1 ), $triggers, true ) ) {
        $payload = "'" . $payload . "'";
    }

    return $payload;
}

```
does this feature exist as I can see anything in the docs

**Comment by nyamsprod** [comment]
In the last stable release the each method has been removed, use the getRecords or the getIterator method. If you want the sanitize your data before saving it you can use the addFormatter method or the stream filter API on the writer object. All of this is well explained in the documentation website

**Comment by graemedewe** [comment]
I need to sanitise uploads and downloads, any suggestions for how to apply this in the Reader mode? and due to being stuck on php5.6, for now, I can only use 8.2.2. thanks

**Comment by nyamsprod** [comment]
@graemedewe everything I said for v9 is still relevant for v8. Just read the documentation :)

**Comment by graemedewe** [comment]
thanks, found the right documentation now
