### ISSUE TITLE
Invalid error response for non-existent file

### ISSUE THREAD

**Issue by nwhitt** [thephpleague/csv#254]
## Issue summary

Attempting to load a non-existent file throws a fatal error instead of a League\Csv\Exception.

### System informations

| Information | Description |
|--------------|---------|
| League\Csv version | 9.0.1 |
| PHP/HHVM version | 7.0.22-0ubuntu0.16.04.1 |
| OS Platform | ubuntu |

## Standalone code, or other way to reproduce the problem

`Reader::createFromPath('/does/not/exist.csv');`

### Expected result
Similar to Flysystem
```
[League\Flysystem\FileNotFoundException]
File not found at path: /does/not/exist.csv
```

### Actual result
```
[Symfony\Component\Debug\Exception\FatalThrowableError]
Wrong parameters for League\Csv\Exception([string $message [, long $code [, Throwable $previous = NULL]]])
```

**Comment by nyamsprod** [comment]
@nwhitt League CSV and Flysystem are two independent packages so they do not follow the same exception mechanism :) .
Having said that I failed to reproduce your error with you given code I get this:

```
PHP Fatal error:  Uncaught League\Csv\Exception: fopen(/does/not/exist.csv): failed to open stream: No such file or directory in ....
```

There's already a test to validate this output [in the test suite](https://github.com/thephpleague/csv/blob/6418c1c5872e9ea9464330531f7b63232e58c496/tests/CsvTest.php#L60-L68). Are you sure about the error ? Maybe there's something else at play here

**Comment by nwhitt** [comment]
It must be in the error handling of my symfony package [with suppression](https://github.com/thephpleague/csv/blob/9.0.1/src/Stream.php#L177-L179), as I get green on unit tests. I'll close this issue until I have more information.

**Comment by IllyaMoskvin** [comment]
I had this exception happen because the [user under which PHP was running](https://stackoverflow.com/questions/7771586/how-to-check-what-user-php-is-running-as) (e.g. `apache`) did not have permissions to do anything except `read` the target file, which did indeed exist.

I fixed it by adding the `'r'` mode to my `createFromPath` call (cf. [`fopen` mode](http://php.net/manual/en/function.fopen.php)):

```
Reader::createFromPath('/file/that/actually/exists.csv', 'r');
```

I know it's somewhat off-topic, but this issue is the top result in Google for that error message, so maybe this will help someone.

**Comment by csiszarattila** [comment]
You can reproduce this error if you have a set_error_handler() somewhere in your code.

A custom set_error_handler() emits errors, and error_get_last() returns null, hence the exception throwing not working in this line, it will generate an error:
https://github.com/thephpleague/csv/blob/6418c1c5872e9ea9464330531f7b63232e58c496/src/Stream.php#L177-L178

The error easily reproducable with this code:

```
set_error_handler(function($errno, $errstr) {
    var_dump($errno, $errstr);
});

@fopen("test.cvs", 'r');
var_dump(error_get_last());

--- outputs: 
int(2)
string(65) "fopen(test.cvs): failed to open stream: No such file or directory"
NULL

```

I think error_get_last()['message'] needs to be checked, and return a general message if its empty.

**Comment by nyamsprod** [comment]
Good catch this is a easy fix. I'll try to release a patch this week or the next one...  or you can submit a PR with the fix if you want
