### ISSUE TITLE
PHP 7.0.10

### ISSUE THREAD

**Issue by garygreen** [thephpleague/csv#255]
Any reason why the min PHP version was bumped from 7.0.0 to 7.0.10? We're having trouble installing this package on our cloud hosted server because it only has 7.0.0 - if it specifically needs version `.10` to run then ignore this, otherwise could it be changed back?

**Comment by nyamsprod** [comment]
@garygreen The version bump was done to take into account a bug fix in PHP's CSV implementaton see http://www.php.net/ChangeLog-7.php#7.0.10

**Comment by garygreen** [comment]
Oh ok, makes sense. Really have to get a better host at some point 😄
