### ISSUE TITLE
Reader::createFromPath() opens the file in write mode

### ISSUE THREAD

**Issue by Bilge** [thephpleague/csv#256]
## Issue summary

Although I realise `createFromPath()` is not implemented directly by `Reader`, the fact that this calling convention exists and yet does not open the file in read-only mode is a terrible design flaw because it's misleading and error-prone. If this method must be implemented in an abstract class, and if it must default to requiring write mode access, `Reader` must override the default in order for its behaviour to be sane and predictable.

**Comment by nyamsprod** [comment]
@Bilge I believe the method behaviour is sane and predictable as [it is clearly documented](http://csv.thephpleague.com/9.0/connections/instantiation/#loading-from-a-file-path). I don't get the problem with the current method signature. Unless you show me how it could be misleading ?

**Comment by Bilge** [comment]
If that's your honest response, then excuse me for saying, but it seems you don't have a very good understanding of file permissions. In the case that I have my CSV hosted in a read-only environment, trying to open it with redundant write permissions will result in an access violation. That is, a fatal error will occur trying to open a read-only CSV with `Reader::createFromPath()`. It should strike you as obvious that a class called *reader* should only require permission to *read*; if it does not I do not have high hopes for the future of this project.

**Comment by nyamsprod** [comment]
@Bilge have you read the documentation ? If so you should already have an answer to your question ? Just use the correct open mode. 

> If that's your honest response, then excuse me for saying, but it seems you don't have a very good understanding of file permissions. 

Again if you have taken time to read the documentation we would not have this conversation. As everything is explained there with examples.

**Comment by amcsi** [comment]
But isn't it that always with a reader you would need to read the file only? The default seems unreasonable to me. It's led to bugs that were tricky to debug a few times.
