### ISSUE TITLE
Validation process

### ISSUE THREAD

**Issue by paulcanning** [thephpleague/csv#257]
I need to check that uploaded CSV are valid in terms of allowed delimiters, other special characters and that all rows have the same number of items.

How can I go about this using this library?

**Comment by nyamsprod** [comment]
@paulcanning have you read the documentation ? especially about the Reader object ?

**Comment by paulcanning** [comment]
I have read the Reader object documentation for v8.X and cannot see anything about validation in there.

**Comment by nyamsprod** [comment]
So you have all the informations needed I don't understand what's missing ? you want me to show you how to validate a CSV ? I believe this is a per project mechanism.

**Comment by paulcanning** [comment]
No I don't have _all_ the information.

> I have read the Reader object documentation for v8.X and cannot see anything about validation in there.

**Comment by nyamsprod** [comment]
> I just want a simple validation of the file. There must be a simple yes or no validation method, right?
No . You are responsible for validating your CSV. Because each CSV has its own rules

**Comment by paulcanning** [comment]
OK, so what methods should I look at for validation? **Again**, the documentation for the Reader object is void of such topics.

**Comment by nyamsprod** [comment]
Again I don't know use the filter API or the reader methods it depends on what you want to validate the API provides different hooks use the one that can help you.

**Comment by nyamsprod** [comment]
@paulcanning Can I close this issue?
