### ISSUE TITLE
add columns during runtime.

### ISSUE THREAD

**Issue by pboethig** [thephpleague/csv#260]
## Issue summary
Is it possible?.  Not many libs can do that.
_(Please explain in plain english your issue/feature request)_

### System informations

_(In case of a bug report Please complete the table below)_

| Information | Description |
|--------------|---------|
| League\Csv version |  |
| PHP/HHVM version |  |
| OS Platform |  |

## Standalone code, or other way to reproduce the problem

_(Please complete the text below to help us fix the issue)_

**Comment by nyamsprod** [comment]
@pboethig what do you mean ? I don't understand your request :'( .

**Comment by pboethig** [comment]
Hi,

I ment, that I want to be able to add new columns to the csv row during reading.

Somethng like that $reader->getHeader()->addColumns(['new column'=>'new column1']);

Kind regards

Peter

**Comment by nyamsprod** [comment]
The reader does not modify the CSV so "adding" columns is not possible per se. 
Having said that nothing prevents you to add each field of your column inside a foreach

```php
<?php

$csv = Reader::createFromPath('file.csv');
$columns = []; //your column.
foreach ($csv as $offset => $record) {
    $record['new_column'] = $column[$offset] ?? null;
}
```

If this is something you are doing frequently you could even use and `IteratorIterator` object to improve this workflow.

**Comment by nyamsprod** [comment]
@pboethig can I close this ticket?
