### ISSUE TITLE
Reader not valid from construction

### ISSUE THREAD

**Issue by Bilge** [thephpleague/csv#261]
## Issue summary

All objects, such as the CSV `Reader` class, must be valid from construction. However, it is possible to create readers for nonexistent files without incurring any indication nor exception at construction time.

```php
League\Csv\Reader::createFromPath('nonexistent file');
```
> object(League\Csv\Reader)

This code should throw an exception, such as `FileNotFoundException`.

**Comment by nyamsprod** [comment]
This issue as already been reported and explained in issue #254

**Comment by Bilge** [comment]
That issue does not match this one; it claims that either:

1. The wrong exception is thrown, or
2. A fatal error is encountered.

As this ticket reports, neither actually happens: the `Reader` object is created successfully with no exception or error raised.

**Comment by nyamsprod** [comment]
@Bilge correct me if I'm wrong but it is the same code right ? So it should fall in the same category since this code is covered by the same test in the test suite like explained in #254
