### ISSUE TITLE
Argument passed must be a seekable stream resource

### ISSUE THREAD

**Issue by Toilal** [thephpleague/csv#262]
## Issue summary

I wish I could use Writer directly on `php://output` stream (Feature Request).

### System informations

| Information | Description |
|--------------|---------|
| League\Csv version | 9 |
| PHP/HHVM version | 7.1 |
| OS Platform | Linux |

## Standalone code, or other way to reproduce the problem

```php
$output = fopen('php://output', 'w');
$this->writer = Writer::createFromStream($output);
$this->writer->insertOne(['a', 'b', 'c']);
```

### Expected result

Simple use case like this one should work as expected, as it doesn't require any seek method

### Actual result

createFromStream() fails with message: `Argument passed must be a seekable stream resource`.

When commenting out the seekable check [here](https://github.com/thephpleague/csv/blob/7dfedca6b626a5ed85e7c1ffe838c8c4364ede95/src/Stream.php#L112-L114), it works as expected.

Maybe this check could be disabled and display an error message only when trying to use a feature that really requires the stream to be seekable, and [disable behavior like this](https://github.com/thephpleague/csv/blob/7dfedca6b626a5ed85e7c1ffe838c8c4364ede95/src/Writer.php#L173-L176) when stream is not seekable.

**Comment by nyamsprod** [comment]
@Toilal thanks for submitting this enhancement. Don't forget to update the documentation too. As this means that a non seekable CSV can not use any of the output methods. FWIW you could have gone with 

```php
$csv = Writer::createFromFileObject(new SplFileObject('php://output', 'w'));
$csv->insertOne(['a', 'b', 'c']);
```

It works as expected but it will trigger an Warning instead of a Error if you try to use any output method. Maybe we could do something about that too ? I don't know

**Comment by nyamsprod** [comment]
@Toilal just for your information I've just push a commit to enable non seekable stream. This feature is stable but will be release with version 9.1.0 ... when I have time

**Comment by shameerc** [comment]
Shouldn't we also update [this exception message](https://github.com/thephpleague/csv/blob/master/src/Stream.php#L109) as it now supports non seekable streams? :)

**Comment by nyamsprod** [comment]
yes it will be updated on the next patch release along with other patches in the pipe

**Comment by shameerc** [comment]
Happy to make a PR, if it's not done already.

**Comment by nyamsprod** [comment]
already done on my local branch but thanks for this offer 👍
