### ISSUE TITLE
Preventing CSV Injection

### ISSUE THREAD

**Issue by klaude** [thephpleague/csv#268]
## Issue summary

Ref: http://georgemauer.net/2017/10/07/csv-injection.html

This isn't a bug report per-se, but a temperature check to see if y'all feel that a feature to prevent injection on CSV writing would be accepted into the project. 

I'd like to add a configuration setting to new `Writer` instantiation and a parameter to `output()` to escape formulas in the CSV document. If the user opts to escape formulas then any cell in the CSV that begins with the "=", "-", "+", or "@" characters will have a `\t` prepended to it. There are valid use cases for executable code in CSV documents, so injection prevention would default to false. 

I'd target the latest major version of the project, but don't mind back-porting this to version 8. I'm willing to do all the work, but only if this is something y'all feel is important. If y'all want to see this in the project, but feel there's a better way to have the user configure injection prevention I'm all ears. Let me know what you think. Thanks!

**Comment by nyamsprod** [comment]
@klaude For what I understand about csv injection, you do not need to add anything to league csv to make it work. as we talk the package already allow adding some sanity/escaping check prior to inserting your data to the CSV document. So what you really need is provide a clean implementation of csv injection prevention in form of a [Formatter](http://csv.thephpleague.com/9.0/writer/#records-filtering) and/or a [StreamFilter](http://csv.thephpleague.com/9.0/connections/filters/). Depending on your work I may found it useful, maintainable and thus incorporate it but I would reserve my final thought upon seeing the PR... not before.

**Comment by klaude** [comment]
That's a good call, @nyamsprod. It makes a lot more sense than a parameter bag. I'll come up with something and get you a PR. Thanks!

**Comment by nyamsprod** [comment]
@klaude having read in more depth the article you linked I have to wonder if this is a job to be shipped with League CSV. Basically the article stress that this is not a CSV issue per se but a Spreadsheet one and instead of fixing spreadsheet software we are about to pseudo fix a CSV document without the knowledge of how and who is going to use it. That a pretty dangerous decision to make ... In some regards this reminds me of PHP's escaping data model which was broken to begin with

**Comment by klaude** [comment]
I agree. That's why it makes sense to leave injection handling to the user's discretion. I feel the library should provide it so users get an easier security option. 

There are plenty of valid use cases for formulae in a CSV. I don't think execution is a bug in spreadsheet programs, but it's often overlooked as a source for injection, way more often than something like JavaScript or SQL injection. For instance, consider a user who signs up for a service with the first name `=(2+2)`. 

It's probably not the end of the world your work in #269 is bundled with the library or made a standalone package, but the article got me thinking.

**Comment by nyamsprod** [comment]
Merge into the master branch I'll close this issue 👍
