### ISSUE TITLE
Call to undefined function League\Csv\is_nullable_int()

### ISSUE THREAD

**Issue by marksparrish** [thephpleague/csv#272]
## Issue summary

When running the code in a laravel job queue I get the following error.  

Call to undefined function League\Csv\is_nullable_int() in web/vendor/league/csv/src/Reader.php:325

Maybe missing in autoloader?
Function is not referenced in the use statements like bom_match is the AbstractCsv.php file

### System informations

| Information | Description |
|--------------|---------|
| League\Csv version | 9.1.0  |
| PHP/HHVM version | 7.0.22-0ubuntu0.16.04.1  |
| OS Platform | ubuntu 16.04 |

## Standalone code, or other way to reproduce the problem

This issue only occurs when I run the code in a laravel job queue.

### Expected result

Process the file

### Actual result

Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function League\Csv\is_nullable_int() in web/vendor/league/csv/src/Reader.php:325

**Comment by nyamsprod** [comment]
@marksparrish strange 
> Maybe missing in autoloader?
Function is not referenced in the use statements like bom_match is the AbstractCsv.php file

functions are loaded by composer.json maybe something is wrong in your autoloader ?

**Comment by marksparrish** [comment]
no not my autoloader.  I think the packages.  Take a look at the functions_include.php file.  Not reference the is_nullable_int only bom_match.

**Comment by nyamsprod** [comment]
Normal they're define in the same file
