### ISSUE TITLE
Bug in offset - unable to skip header with 9.x

### ISSUE THREAD

**Issue by ddinchev** [thephpleague/csv#277]
## Issue summary

I'm using `phpleague/csv` to process CSV exports coming from a multi-language system. The header columns of the CSVs can be in a different language but are always in the right order. So I have constants, corresponding to each column. I want to get only the CSV rows.

In version 8.x I could do the following:
```php
$csv = Reader::createFromPath($filePath, 'r');
$csv->setOffset(1);
foreach ($csv->getIterator() as $record) { 
  // record would be something like `[0 => '2017-01-01', 1 => 'some value']`
  // I would access it like `$record[self::COL_DATE]`
}
```

In 9.x however, offset doesn't skip header, no matter the offset value.

Attempt 1:

```php
$csv = Reader::createFromPath($filePath, 'r');
$stmt = new Statement();
$stmt->setOffset(1);
foreach ($stmt->process($csv) as $record) {
     // first record will still be the header, regardless of the offset?!
}
```

Attempt 2:
```php
$csv = Reader::createFromPath($filePath, 'r');
$csv->setHeaderOffset(0);
foreach ($csv->getRecords() as $record) { 
  // record would be something like `['Дата' => '2017-01-01', 'Бележка' => 'some value']`
  // or something like `['Date' => '2017-01-01', 'Note' => 'some value']`
  // depending on the language
}  
```

### System informations

| Information | Description |
|--------------|---------|
| League\Csv version | 9.1.1  |
| PHP/HHVM version | 7.1.11  |
| OS Platform | Ubuntu |

**Comment by nyamsprod** [comment]
Strange attempt 1 should work or else the test suite would fail 😢. Could you provide a CSV snippet or at least the first rows so I can replicate your bug because right now I can't reproduce it

**Comment by ddinchev** [comment]
I prepared a repo with the minimum possible code to replicate the case:
https://github.com/ddinchev/league-csv-bug

Against my understanding of how these few lines should work, the record loop always goes through all the records, regardless of `offset` being set.

**Comment by nyamsprod** [comment]
@ddinchev I understand the issue ... it's because the `Statement` object is [an immutable value object ](http://csv.thephpleague.com/9.0/reader/statement/) so you should do this 

```php
$csv = \League\Csv\Reader::createFromPath(__DIR__ . '/test.csv', 'r');
$stmt = new \League\Csv\Statement();
$stmt = $stmt->offset(2); //note the re-assignment a better solution is shown below 
//or $stmt = (new \League\Csv\Statement())->offset(2);
foreach ($stmt->process($csv) as $record) {
    print_r($record);
}
```
