### ISSUE TITLE
Memory issues when working with large amounts of data

### ISSUE THREAD

**Issue by JohnnyWalkerDesign** [thephpleague/csv#278]
## Issue summary

Is there a good way to work with large amounts of data? I have a table of User information that's 80,000 rows. Not gigantic, not small. I understand that CSV makes use of Chunk as of v9 to handle large amounts of data, but I'm having a server error when trying to extract it.

The problem isn't with CSV per se, but with how best to implement it with large datasets.

### System informations

| Information | Description |
|--------------|---------|
| League\Csv version | 9.1.1 |
| PHP/HHVM version | PHP 7.1 |
| OS Platform | Unix |

### Code

        $allUsers = User::all();
        $header = array_keys($allUsers[0]);
        $csv = Writer::createFromString('');
        $csv->insertOne($header);
        $csv->insertAll($allUsers);
        $csv->output('users_'.date("Y-m-d").'.csv');

The server is actually crashing just from creating `$allUsers`. So how can pull the dataset from the database to pass to CSV to output?

**Comment by nyamsprod** [comment]
The problem is not in the library but on how Users:all is created. You should try to use a Iterator or a generator like shown on the documentation website

**Comment by JohnnyWalkerDesign** [comment]
The solution, for anyone else with the same problem, was this:

        $allUsers = User::take(1)->get()->toArray();

        $header = array_keys($allUsers[0]);

        $csv = Writer::createFromString('');

        $csv->insertOne($header);

        User::chunk(10000, function($users) use ($csv) {
            
            $csv->insertAll($users->toArray());

        });

        $csv->output('users_'.date("Y-m-d").'.csv');
