### ISSUE TITLE
Null Handling in Csv\Writer class

### ISSUE THREAD

**Issue by jaykravetz** [thephpleague/csv#28]
When passing an array containing null  to `$writer->insertOne()` an InvalidArgumentException is thrown with message: 

> the provided data can not be transform into a single CSV data row

Example:

``` php
$writer->insertOne(["one", "two", null, "four"]);
```

This creates the requirement for the client code to "sanitize" nulls before inserting

**Comment by nyamsprod** [comment]
A quick follow up just to say that in the upcoming v7 this functionality is removed from the `Writer` class and is now implemented as a pluggable system. Please check the [migration guide](http://csv.thephpleague.com/upgrading/7.0/#row-consistency-check) for more information
