### ISSUE TITLE
Problem while reading csv utf-8 (comma delimited) file

### ISSUE THREAD

**Issue by gyaan** [thephpleague/csv#281]
Everything is coming in the header itself

Lets say file is like below

id,name,address
1,hello,world

then header should be id, name, and address but its taking complete file as header and the output of header is like below
id,name,address,1,hello,world.

Is there any configuration I need to do ?

**Comment by nyamsprod** [comment]
Please refers to the [documentation](https://csv.thephpleague.com/) website where everything is explained

**Comment by gyaan** [comment]
it would be great if you specify which specific section to check.
