### ISSUE TITLE
Has delimiter detection been removed in v9?

### ISSUE THREAD

**Issue by sentientsolutions** [thephpleague/csv#282]
Version 8 appears to have had a function that counts occurrences of common delimiters, and reports them in order of occurrences. Has this been removed in v9? If so, what is the recommended alternative?

**Comment by nyamsprod** [comment]
@sentientsolutions as indicated in the CHANGELOG.md and on the documentation website the functionnality is now on a separate function defined in the League\Csv namespace.  http://csv.thephpleague.com/9.0/connections/controls/#detecting-the-delimiter-character
