### ISSUE TITLE
how can I detect \r as line seperator

### ISSUE THREAD

**Issue by scottgrayson** [thephpleague/csv#284]
## Issue summary

Excel for mac saves CSV with \r as the line seperator.  Is there a way to handle that with the Reader class?

### System informations

_(In case of a bug report Please complete the table below)_

| Information | Description |
|--------------|---------|
| League\Csv version |  9.1 |
| PHP/HHVM version | 7.1 |
| OS Platform |  MacOS 10.12.6 |

## Standalone code, or other way to reproduce the problem

example csv:
```
"Org_Name,address_linel\rW.K. Kellogg Foundation,"One Michigan Avenue, East"\rMatrix Human Services,120 Parsons Street\rMichigan Fitness Foundation,P.O. Box 27187\r
```
this is the workaround I did in the commented section:
```
     //   $inputString = str_replace(
      //      "\r",
       //     "\n",
       //     file_get_contents($inputPath)
       // );

        $input = Reader::createFromString($inputString);
        $input->setHeaderOffset(0); //set the CSV header offset
```

### Expected result
detect \r as line seperator

### Actual result
The header record must be empty or a flat array with unique string values

**Comment by nyamsprod** [comment]
@scottgrayson the solution is described in the [README file](https://github.com/thephpleague/csv#configuration)
