### ISSUE TITLE
cp1250 support?

### ISSUE THREAD

**Issue by landsman** [thephpleague/csv#286]
Script:
```
CharsetConverter::addTo($csv, 'cp1250', 'utf-8');
```

Exception:
```
The submitted charset cp1250 is not supported by the mbstring extension
```

Which encoding I should use for `cp1250` please?

**Comment by nyamsprod** [comment]
@landsman thanks for using the library. Your issue has nothing to do with the library please refer to mbstring documentation to find out which encoding your require and how to write it.
