### ISSUE TITLE
CharsetConverter::convert should not try to convert numeric value

### ISSUE THREAD

**Issue by delmicio** [thephpleague/csv#287]
## Issue summary

After updating from 9.1.2 to 9.1.3 my code is no longer working without error.

### System informations

| Information | Description |
|--------------|---------|
| League\Csv  | 9.1.3 |
| PHP | 7.1.12 |
| ubuntu  | 16.04 |

## Standalone code, or other way to reproduce the problem

```PHP
$formatter = (new Csv\CharsetConverter())
    ->inputEncoding('utf-8')
    ->outputEncoding('Windows-1252');
$csvWriter = Csv\Writer::createFromFileObject(new \SplFileObject('php://output', 'w'));
$csvWriter->addFormatter($formatter);
$csvWriter->insertOne(['str', '1', 2]); 
```

### Expected result
No errors.

### Actual result
`Type error: mb_convert_encoding() expects parameter 1 to be string, integer given at /var/www/vendor/league/csv/src/CharsetConverter.php:217`

**Comment by nyamsprod** [comment]
Bug fixed in the master branch .. a patch version will be released later this week with the bug fix.
