### ISSUE TITLE
Writer::setFlushThreshold should accept 1 as an argument

### ISSUE THREAD

**Issue by kboduch** [thephpleague/csv#289]
## Issue summary

Setting writer flush threshold to 1 throws an exception.

### System informations

| Information | Description |
|--------------|---------|
| League\Csv version | 9.1 |
| PHP/HHVM version | 7.1.x |
| OS Platform | debian |

## Standalone code, or other way to reproduce the problem

```
$csv = \League\Csv\Writer::createFromString('');
$csv->setFlushThreshold(1);
```

### Expected result
No error.
### Actual result
`League\Csv\Exception: League\Csv\Writer::setFlushThreshold() expects 1 Argument to be null or a valid integer greater or equal to 1`

**Comment by nyamsprod** [comment]
thanks for reporting and submitting a PR to resolve to bug :+1:
