### ISSUE TITLE
Records with unescaped enclosure character in multiline content are split

### ISSUE THREAD

**Issue by strarsis** [thephpleague/csv#291]
## Issue summary

Records with unescaped enclosure character in multiline contents are parsed as separate records.

### System informations

| Information | Description |
|--------------|---------|
| League\Csv version |  9.1.3|
| PHP/HHVM version |  PHP 7.0.28-0ubuntu0.16.04.1 (cli) ( NTS )|
| OS Platform |  WSL (Bash on Windows) |

## Standalone code, or other way to reproduce the problem
```php
require __DIR__ . '/vendor/autoload.php';

use League\Csv\Reader;

$data = file_get_contents(__DIR__ . '/input.csv');

if (!ini_get("auto_detect_line_endings")) {
	ini_set("auto_detect_line_endings", '1');
}

$csv = Reader::createFromString($data);
$csv->setDelimiter(';');
$csv->setHeaderOffset(0);

foreach($csv as $record) {
	print_r($record);
}
````

Input CSV (`input.csv`):
```csv
"Field 1";"Field 2";"Field 3"
"Record 4";"Unescaped 
multi 
line
text
with
unescaped
"quote" 
in text";"Test 4.2"
"Record 5";"Test 5.1";"Test 5.2"
````

### Expected result
````
Array
(
    [Field 1] => Record 4
    [Field 2] => Unescaped
multi
line
text
with
unescaped
"quote"
in text
    [Field 3] => Test 4.2
)
Array (
    [Field 1] => Record 5
    [Field 2] => Test 5.1
    [Field 3] => Test 5.2
)
````

### Actual result
````
Array
(
    [Field 1] => Record 4
    [Field 2] => Unescaped 
multi 
line
text
with
unescaped
quote" 
    [Field 3] => 
)
Array
(
    [Field 1] => in text"
    [Field 2] => Test 4.2
    [Field 3] => 
)
Array
(
    [Field 1] => Record 5
    [Field 2] => Test 5.1
    [Field 3] => Test 5.2
)
````

**Comment by nyamsprod** [comment]
@strarsis why do you consider this to be a bug ? For your CSV to be valid you need to escape the enclosure ... with another enclosure character as per CSV rules. So if your CSV is wrongly formatted the output too will be wrong.

**Comment by strarsis** [comment]
@nyamsprod: Yes, the CSV is technically invalid. But it would be nice if the parser could be made somehow more tolerant.

**Comment by nyamsprod** [comment]
@strarsis making the parser more tolerant is a recipe for disaster. As it is, the parser is already extremely tolerant IMHO as it does not out of the box follow CSV parsing as per the RFC 😄  ... and that on itself is a debate on its own. 

Having said that if you can come up with such a mechanism I'm open to reviewing it and even merging it if your solution works. In the mean time I would encourage the easiest path which is always to validate your input prior to submitting it to any third party or library like league/csv
