### ISSUE TITLE
Control over which fields are enclosed?

### ISSUE THREAD

**Issue by judgej** [thephpleague/csv#292]
## Issue summary

I need to be able to control which fields are enclosed, and which fields are not enclosed. The CSV will go to an external application that dictates this (MS Access - dates and numbers must NEVER be enclosed, strings must ALWAYS be enclosed).

### System informations

| Information | Description |
|--------------|---------|
| League\Csv version | 9.x |
| PHP/HHVM version | 7.2 |
| OS Platform | Linux |

It seems that a line of CSV data is generated by `fputcsv()`, and that has limitations that simply cannot be overruled. So, is a plugin able to override the single formatted line output with its own logic? I can provide the callback logic to enclose, terminate, escape a field, and that logic will depend on the field name (if that is possible) or position, But I cannot see a way to plug that in.

The only other alternative I see, is simply not to use this library, which would be a shame :-(

**Comment by judgej** [comment]
I guess it is the ability to add an *output filter* that I'm looking for...?

**Comment by nyamsprod** [comment]
You can use stream filters for that see https://csv.thephpleague.com/9.0/connections/filters/

**Comment by judgej** [comment]
Doesn't a stream, filter literally filter the unstructured stream? At that stage, it's too late to be able to manipulate and format individual fields. Or am I misunderstanding what the stream filters do?

**Comment by judgej** [comment]
Okay, I've run out of time on this one, so I'll knock up some custom code for my use-case instead. Thanks for your help.

**Comment by judgej** [comment]
Diffing into the code further, I realised the PHP function `fputcsv()` is only called for streams, and not the SPL file object. The SPL file object has its own `fputcsv()` method, and that is very easy to override:

<?php

```php
namespace My\Namespace;

use SplTempFileObject;

class MySplTempFileObject extends SplTempFileObject
{
    public function fputcsv($fields, $delimiter = null, $enclosure = null, $escape = null)
    {
        // Very naive CSV format, no enclosing and no escaping
        return $this->fwrite(implode($delimiter, $fields) . "\n");
        //return parent::fputcsv($fields, $delimiter, $enclosure, $escape);
    }
}
```

I need to work out where `fputcsv()` is getting its line break characters from, then I have full control of how every field is escaped and enclosed. By passing in field names as the keys to `insertOne()`, those keys can be used to identify the fields that need specific treatment.

**Comment by nyamsprod** [comment]
@judgej the character break is always `\n` to change it I use `fwrite`. So you should not worry about that.

https://github.com/thephpleague/csv/blob/9c8ad06fb5d747c149875beb6133566c00eaa481/src/Writer.php#L188-L191

**Comment by judgej** [comment]
Thanks - the PHP docs implied this, but did not make that point explicit.
