### ISSUE TITLE
Problem with UTF-8 BOM on csv Reader

### ISSUE THREAD

**Issue by jagDanJu** [thephpleague/csv#293]
## Issue summary

When reading a simple csv (utf-8 with bom), a character 194 (Â) is appended to each string.

Delimiter: »(Char: 187)

### System informations

_(In case of a bug report Please complete the table below)_

| Information | Description |
|--------------|---------|
| League\Csv version |9.1.4|
| PHP/HHVM version |7.2.5|
| OS Platform |Windows Server|

## Standalone code, or other way to reproduce the problem

> $csvData = Reader::createFromPath(PATH);
> $csvData->setDelimiter(chr(187));
> $csvData->setHeaderOffset(0);
> 
> $csvData->getHeader());

### Expected result

Header without additional Characters

### Actual result

![image](https://user-images.githubusercontent.com/3613218/40023539-ace57c7a-57cb-11e8-95e1-5c542910c107.png)

**Comment by nyamsprod** [comment]
@jagDanJu Are you sure your CSV is an correctly UTF-8 encoded ? The fact that the library remove the BOM sequence does not mean that it also convert back the CSV content to UTF-8 you must still do it manually. Here's a simple example of how to do it. 
  
Of course your CSV must supports stream filters.

```php
use League\Csv\CharsetConverter;
use League\Csv\Reader;

function csv_to_utf8(Reader $reader)
{
    if (!$reader->supportsStreamFilter()) {
        return $reader;
    }

    $input_bom = $reader ->getInputBOM(); //returns the BOM sequence if any
    if (in_array($input_bom, [Reader::BOM_UTF16_LE, Reader::BOM_UTF16_BE], true)) {
        return CharsetConverter::addTo($reader, 'utf-16', 'utf-8');
        //return $reader->addStreamFilter('convert.iconv.UTF-16/UTF-8'); //if iconv extension is installed
    }

    if (in_array($input_bom, [Reader::BOM_UTF32_LE, Reader::BOM_UTF32_BE], true)) {
        return CharsetConverter::addTo($reader, 'utf-32', 'utf-8');
        //return $reader->addStreamFilter('convert.iconv.UTF-32/UTF-8'); // if iconv extension is installed
    }

    return $reader;
}

$csvData = Reader::createFromPath($path);
csv_to_utf8($csvData);
$csvData->getHeaders();
```

**Comment by jagDanJu** [comment]
@nyamsprod I am not completely sure that the file is correctly UTF-8 encoded. The file ist from an external source.. 
Anyway, your function works pretty well.. Thanks Guy!
