### ISSUE TITLE
Handling Windows style line endings

### ISSUE THREAD

**Issue by hillelcoren** [thephpleague/csv#297]
We've recently switched to this library, on the whole it works great however when a file contains Windows style line ending they're not recognized.

I found this issue (https://github.com/thephpleague/csv/pull/64) but it seems to only apply to creating CSV files, not reading them. 

Is this supported?

**Comment by nyamsprod** [comment]
@hillelcoren thanks for using the library do you have a snippet code I can test to try to reproduce your issue. Otherwise there is no way for me to investigate and/or resolve your issue.

**Comment by hillelcoren** [comment]
This is the code I'm using:

    $csv = Reader::createFromPath($fileName, 'r');
    $stmt = new Statement();
    $data = iterator_to_array($stmt->process($csv));`

Here's a sample file [sample.csv.zip](https://github.com/thephpleague/csv/files/2044047/sample.csv.zip) (GitHub wouldn't allow .csv so I needed to zip it). It opens correctly in LibreOffice but the library sees it as a single line.

**Comment by nyamsprod** [comment]
did you set the delimiters ?

**Comment by hillelcoren** [comment]
Is there a line ending option? 

Thanks for your help btw.

**Comment by hillelcoren** [comment]
Sorry for answering your question with a question :)

I assume you mean in the PHP code? I'm not setting anything other than the code posted. The delimiter (a comma) seems to be working correctly. 

Thanks again!

**Comment by nyamsprod** [comment]
did you try this ?

**Comment by hillelcoren** [comment]
Perfect, thanks! That fixed it :)
