### ISSUE TITLE
Special characters create bad string encoding causing data loss.

### ISSUE THREAD

**Issue by augz** [thephpleague/csv#299]
## Issue summary

It seems that while fetching rows, if the data contains an em dash (–) during a fetchAll() these come back as �, which fails encoding

### System informations
| Information | Description |
|--------------|---------|
| League\Csv version | 8.2.3 |
| PHP/HHVM version | 7.1.17 |
| OS Platform | Ubuntu 17.10 |

## Standalone code, or other way to reproduce the problem

- Create CSV delimited however you like
- Have one data point contain a raw em dash (–)
- Iterate through using fetchAll()

### Expected result
String is returned
### Actual result
empty string is returned.

**Comment by augz** [comment]
Just a side note here, I tinkered with the parent package's composer.json to allow the latest install of this library, the bug is still present.

**Comment by nyamsprod** [comment]
@augz thanks for using the library. Did you try to detect and update the CSV encoding charset before using the fetchAll method?

**Comment by augz** [comment]
@nyamsprod Well this is kind of embarrassing, I'm using another package that is referencing your project, I have a preview of the code block below. The gist of it is that some items coming back from Amazon API (which is in a CSV) contain an em dash but is supposed to be UTF-8. So this returns no errors but just an empty string when an offending character is met. I am not too familiar with your package yet.

I tried $csv->setInputEncoding("UTF-8"); but it still returns an empty string when an em dash is present.


    /**
     * Get a report's content
     * @param string $ReportId
     * @return array on succes
     */
    public function GetReport($ReportId)
    {
        $status = $this->GetReportRequestStatus($ReportId);
        if ($status !== false && $status['ReportProcessingStatus'] === '_DONE_NO_DATA_') {
            return [];
        } else if ($status !== false && $status['ReportProcessingStatus'] === '_DONE_') {

            $result = $this->request('GetReport', [
                'ReportId' => $status['GeneratedReportId']
            ]);
            if (is_string($result)) {
                $csv = Reader::createFromString($result);
                $csv->setDelimiter("\t");
                $headers = $csv->fetchOne();
                $result = [];
                foreach ($csv->setOffset(1)->fetchAll() as $row) {
                    $result[] = array_combine($headers, $row);
                }
            }

            return $result;

        } else {
            return false;
        }
    }

**Comment by nyamsprod** [comment]
I've given you a link to the documentation for v9 seems you are using v8 but the basic premise is still the same the reader does not change nor update the CSV encoding unless told too. So you have to make sure the CSV is in the correct charset before feeding it to the reader. SetEncoding won't help you I'm afraid ☹️

**Comment by augz** [comment]
Without being able to predict the input string, is there a way to tell the reader from the start to force encoding to UTF-8?

**Comment by nyamsprod** [comment]
No can't do. To transcode from one charset to another you need to know the charset on both ends alas what you can do is try to detect the encoding if you CSV contain BOM sequences see #293 apart from that I don't see how you could do that

**Comment by nyamsprod** [comment]
Anyway from my point of view this is not a bug from the lib. You should report it to the package maintainer or make a PR to that library

**Comment by augz** [comment]
Go ahead and close this issue, I reported this bug to that library first and cross referenced this issue just in case there was something missed. I added my own recursive function to fix encoding for now:
```
public static function parseEncoding($arr)
{
	$result = [];
	foreach($arr as $key => $item)
	{
		$result[$key] = (is_array($item))
			? self::parseEncoding($item)
			: mb_convert_encoding($item, "UTF-8");
	}
	return $result;
}
```
