### ISSUE TITLE
RFC4180Field with createFromStream

### ISSUE THREAD

**Issue by rktyt** [thephpleague/csv#303]
## Issue summary

Segmentation fault appears when using `RFC4180Field` and `createFromStream`.

### System informations

| Information | Description |
|--------------|---------|
| League\Csv version | 9.1.4 |
| PHP/HHVM version | PHP 7.1.20 |
| OS Platform | Debian 9.5 |
| Apache version | 2.4.25 |

## Standalone code, or other way to reproduce the problem

```php
$stream = fopen('/path/to/file', 'r');
$reader = \League\Csv\Reader::createFromStream($stream);
\League\Csv\RFC4180Field::addTo($reader);
fclose($stream);
```

### Expected result

The http status code is 200.

### Actual result

Segmentation fault.
But successful when i remove `fclose($stream);`.

--------------------

I already checked <https://csv.thephpleague.com/9.0/interoperability/rfc4180-field/#usage-with-php-stream-resources>.
Is only pure PHP currently supported?

**Comment by nyamsprod** [comment]
Hi  @rktyt this is expected behaviour ... you should close the stream **after** you've destroy the Reader instance not before. If you close the resource when the Reader object is still around you will get a segfault indeed.

````php
use League\Csv\Reader;
use League\Csv\RFC4180Field;

$stream = fopen('/path/to/file', 'r');
$reader = Reader::createFromStream($stream);
RFC4180Field::addTo($reader);
///do what you want
unset($reader);  //this is crucial
fclose($stream);
```

**Comment by rktyt** [comment]
@nyamsprod thanks.
I understood that well.
