### ISSUE TITLE
CRLF Works CR Does Not

### ISSUE THREAD

**Issue by jcrawford** [thephpleague/csv#305]
## Does not like CR line endings

I have a CSV File with CR line endings and when processed with CSV Reader it tries to put every record into a single array.

./customers.csv: ASCII text, with very long lines, with CR line terminators

Chances are these files were created on Windows machines and when I convert them to CRLF then the CSV Reader works just fine.

I noticed that in version 8.0 you had method for setNewLine and getNewLine, is there a way to make 9.0 work with both line endings?

### System informations

_(In case of a bug report Please complete the table below)_

| Information | Description |
|--------------|---------|
| League\Csv version | 9.0 |
| PHP/HHVM version | PHP 7.1.13 |
| OS Platform | Mac OS 10.13.5 |

## Standalone code, or other way to reproduce the problem
use League\Csv\Reader as CsvReader;
$this->reader = CsvReader::createFromPath($filePath);
foreach($this->reader->getRecords() as $record) {
    var_dump($record); exit;
}

### Expected result
I expect it to return an array for each row in the document

### Actual result
It returns a single array with 1700+ elements for all rows in the document at once.

**Comment by nyamsprod** [comment]
@jcrawford thanks for using the library did you try to update your PHP ini configuration https://github.com/thephpleague/csv#configuration ? Or change the file open mode ?

**Comment by jcrawford** [comment]
Thanks that did the trick, I couldn't find anything about that in the docs, didn't think about checking the README.
