### ISSUE TITLE
Read CSV from S3 storage

### ISSUE THREAD

**Issue by deepexcel** [thephpleague/csv#306]
How do I  read CSV from s3 storage. 

I tried below code
```
$s3 = \Storage::disk('s3');
$filePath = '/uploads/' . $filename;
$csv = Reader::createFromPath( $s3->read($filePath ), 'r');
$csv->setHeaderOffset(0);
$stmt = (new Statement()) ->offset(0)->limit(25);

$records = $stmt->process($csv);
```

It logs the data in the file with the following errors

```
failed to open stream: No such file or directory at C:\\xampp\\htdocs\\pass_dash\\vendor\\league\\csv\\src\\Stream.php:179)

C:\\xampp\\htdocs\\pass_dash\\vendor\\league\\csv\\src\\Reader.php(69): League\\Csv\\Stream::createFromPath('questions,class...', 'r', NULL)
```

### System informations

_(In case of a bug report Please complete the table below)_

| Information | Description |
|--------------|---------|
| League\Csv version |  9.0
| PHP/HHVM version |  7.0
| OS Platform |  Windows 10

**Comment by deepexcel** [comment]
It worked with 
```
$csv = Reader::createFromString( $s3->read($filePath ), 'r');

```

**Comment by quevlu** [comment]
@deepexcel That reads in memory instead of using a stream solution.
