### ISSUE TITLE
Invalid multibyte sequence - incov filter

### ISSUE THREAD

**Issue by soukupm2** [thephpleague/csv#308]
## Issue summary

We are getting this warning
PHP Warning: SplFileObject::next(): iconv stream filter ("windows-1250"=>"UTF-8//IGNORE"): invalid multibyte sequence in /www/...

### System informations

_(In case of a bug report Please complete the table below)_

| Information | Description |
|--------------|---------|
| League\Csv version |  8.2 |
| PHP/HHVM version | 5.6.37  |
| OS Platform |  Debian 8 |

## Standalone code, or other way to reproduce the problem

$csvReader = Reader::createFromPath($file);
$csvReader->appendStreamFilter('convert.iconv.windows-1250/UTF-8//IGNORE');
$csvReader->setDelimiter(';');
$csvReader->fetchAssoc();

**Comment by nyamsprod** [comment]
@soukupm2 thanks for using this library. Did you should check to see if stream filters are supported before using them in your case ? This is documented on the documentation website http://csv.thephpleague.com/8.0/filtering/#stream-filter-api .
