### ISSUE TITLE
Custom EOL string ?

### ISSUE THREAD

**Issue by neradp** [thephpleague/csv#311]
|    Q        |   A
|------------ | ------
| Version     | 9.0

### Question

Hi..
I need update update EOL (End Of Line) string to something like that: ";\r\n"
How to do that ? ($reader->setEOL())
In reader i must trim ";" on every last parsed value..

**Comment by nyamsprod** [comment]
@neradp this is explain in the documentation website see http://csv.thephpleague.com/8.0/inserting/#handling-newline

**Comment by neradp** [comment]
Sorry ..i need that functionality for reader.. not writer..

**Comment by nyamsprod** [comment]
@neradp you do realize that `";\r\n"` is not a valid new line sequence ? I would suggest using stream filtering like explain in the document or a simple mapper function.

**Comment by neradp** [comment]
I do.. thanks...
