### ISSUE TITLE
getDelimiter shows ',' instead of ';'

### ISSUE THREAD

**Issue by HamzaDevz** [thephpleague/csv#312]
Hello,
When i read a csv file with `Reader` => i have the wrong delimiter...

### Question

How can getDelimiter function shows me the right delimiter from the file ?
`$csv = Reader::createFromPath($filePath, 'r');`
`$csv->getDelimiter()` => `,`

Thanks.

**Comment by nyamsprod** [comment]
Please refer to the documentation website where it is explained
