### ISSUE TITLE
Keep leading zeros

### ISSUE THREAD

**Issue by frankeg** [thephpleague/csv#316]
| Version     | 9.0.0

When creating a CSV leading zeros get removed.
Is there a solution?

Thanks

**Comment by nyamsprod** [comment]
@frankeg a CSV is a plain text document since the type casting is done by PHP if you need to format your cells you should formatted them as string so that on CSV creation your formatting is kept unchanged.

**Comment by frankeg** [comment]
@nyamsprod weird I swear I saw no leading zeros in a text editor.
now they're their
thanks
