### ISSUE TITLE
Convert works only with first value.

### ISSUE THREAD

**Issue by mgralikowski** [thephpleague/csv#317]
### Bug Report

9.1.4
PHP 7.2 (Laragon)
Laravel 5.7

#### Summary

Convert method works only with first value.
My csv is encoded in UTF16_LE (this is the only one utf encode which works with Excel properly).

#### Standalone code, or other way to reproduce the problem

        $reader = Reader::createFromFileObject($request->file('file')->openFile());
        if ($reader->getInputBOM() === Reader::BOM_UTF16_LE) {
            $encoder = (new CharsetConverter())->inputEncoding('UTF-16LE');
            $records = $encoder->convert($reader->getRecords());
        } else {
            $records = $reader->getRecords();
        }

        foreach ($records as $record) {
            dd($record);
        }

#### Expected result

Transformed full array.

array:4 [▼
  0 => "Properly decoded sentence"
  1 => "Other normal word"
  2 => "Second normal word"
  3 => "And third"
]

#### Actual result

Transformed only first cell in first row.

array:4 [▼
  0 => "Properly decoded sentence"
  1 => "吀爀攀嬀܁ 眀猀欀愀稀渁椀欀愀 䄀⸀㄀"
  2 => "娀搀愀渀椀攀 搀漀 　 瀀甀渀欀琀眀 䄀⸀㄀"
  3 => "∀娀搀愀渀椀攀 ∀∀猀瀀攀䈀渁椀愀∀∀ 䄀⸀㄀∀ഀ"
]

**Comment by nyamsprod** [comment]
@mgralikowski thanks for using the library. At first I thought too that this was an issue but will trying to debug this behavior I thinking more and more that this is an expected behaviour and not a bug. On the other hand the documentation should be updated to better express your concern.

Because your are **reading** a CSV, conversion must be done **PRIOR** to iteration and not after. so you should use the following code instead:

```php
$reader = Reader::createFromPath('/path/to/my/file.csv');
if (Reader::BOM_UTF16_LE === $reader->getInputBOM()) {
    CharsetConverter::addTo($reader, 'UTF-16LE', 'UTF-8');
}
foreach ($reader as $record) {
    dd($record);
}
```
the `CharsetConverter::convert` method is more suited for data insertion in case of any iterable object **already correctly parse** into CSV fields.

**Comment by mgralikowski** [comment]
Yes, i could not use filters ($reader->supportsStreamFilter() - false) so what is the best option to pass file to Your library and use filters as well? Converting uploaded file to a string and assigning to variable (I use Laravel)?

**Comment by nyamsprod** [comment]
If you can convert the uploaded file into PHP stream then you can use the stream filter mechanism

**Comment by mgralikowski** [comment]
`$reader = Reader::createFromPath($request->file('file')->getRealPath());`

`$reader = Reader::createFromStream(fopen($request->file('file')->getRealPath(), 'r+'));`

Both solutions loading properly file. Is any preferred (faster or sth)?

**Comment by nyamsprod** [comment]
Nope there are essentially the same

**Comment by mgralikowski** [comment]
```
        $reader = Reader::createFromPath($request->file('file')->getRealPath());
        $delimiters = delimiter_detect($reader, ["\t", ",", ";"]);
        $reader->setDelimiter(array_keys($delimiters, max($delimiters))[0]);
        if ($reader->getInputBOM() === Reader::BOM_UTF16_LE)
            CharsetConverter::addTo($reader, 'UTF-16LE', 'UTF-8');
        if ($reader->getInputBOM() === Reader::BOM_UTF16_BE)
            CharsetConverter::addTo($reader, 'UTF-16BE', 'UTF-8');
        // detect win-1250 (ms excel)
        
        $records = $reader->getRecords();
        
        foreach ($records as $record) {
            dd($record);
        }

This is my final code. I am going to make totally universal loader. I have problem with detecting MS Excel file. Any methods in Your library can help me or i need do it manually ? 
```

**Comment by nyamsprod** [comment]
@mgralikowski can you close this issue if the reason for it being opened in the first place has already been answered ?

**Comment by mgralikowski** [comment]
I counted on little help with above but you are right - primary reason is answered.
