### ISSUE TITLE
Null handling in \League\Csv\Reader class

### ISSUE THREAD

**Issue by roberto-aguilar** [thephpleague/csv#319]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

#### Proposal

It will be great if the `\League\Csv\Reader` class let the developer choose how to handle null values as the `\League\Csv\Writter` since https://github.com/thephpleague/csv/issues/28

My use case is that i have a file that allow empty values like:

```csv
name,age,email
Roberto Aguilar,,roberto.aguilar.arrieta@gmail.com
```

And when i fetch the record i get:

```php
[
    "name" => "Roberto Aguilar",
    "age" => "",
    "email" => "roberto.aguilar.arrieta@gmail.com",
]
```

The problem with this approach is that if this data goes straight to the database, the missing fields are stored as empty strings instead of null values (which feels weird by concept).

The current alternative which is to iterate over all the fields to replace empty strings with `null` is not great if you have to do this on every csv read in your applications.

My proposal is to replicate the same behavior as the `\League\Csv\Writter` class which allows:

```php
$reader->setNullHandling(Reader::EMPTY_AS_EMPTY_STRING); // For backwards compatibility
$reader->setNullHandling(Reader::EMPTY_AS_NULL); // What dreams are made of 🤤 
```

The latter could fetch the same record as:

```php
[
    "name" => "Roberto Aguilar",
    "age" => null,
    "email" => "roberto.aguilar.arrieta@gmail.com",
]
```

What do you think? 😃

**Comment by nyamsprod** [comment]
@roberto-aguilar thanks for using the package. 

At first glance there's a huge BC looming in your proposal how do you make the distinction between missing field (currently returned as `null` value) and empty field which are empty string ?

Also what your proposal only deals with your special case only and leaving every other cases to be dealt by the developer. 

IMHO, the better approach would be to create a PHP middleware between the Reader and your insertion operation which would make any necessary transformation according to your own business logic simple, intuitive and easily maintainable something along the line of this pseudo code. 

```php
$reader = League\Csv\Reader::createFromPath('/path/to/csv/file.csv');
$modifier = new MySpecificModifier(); //contains your business specific transfo/logic)
foreach ($modifier->transform($reader) as $row) {
  //insert your data in your DB backend
}

//with a simple signature for your transform method following this
public function MySpecificModifier::transform(Reader $reader): iterable
```

What do you think ?

**Comment by roberto-aguilar** [comment]
Thanks for the quick response, @nyamsprod!

My current approach is to use this kind of middleware between the reader and my insertions, so yeah, i agree with you in this point.

I didn't know about the missing field vs empty field problem, can you help me understand it a little bit more? how a record with a missing field looks like in a csv? If they are already returning null i can work with that too.

**Comment by nyamsprod** [comment]
@roberto-aguilar this is explained in the documentation http://csv.thephpleague.com/9.0/reader/#records-normalization (ie: when a CSV is malformed normalization is done by appending `null` value to the record

**Comment by roberto-aguilar** [comment]
Thanks for the link, now i understand 😄 

If this can be a BC and we both agree on the workaround, i can go live with the current behavior.

Thanks for taking the time, @nyamsprod 🤘
