### ISSUE TITLE
Get output file from Writer?

### ISSUE THREAD

**Issue by tomkyle** [thephpleague/csv#320]
_(Fill in the relevant information below to help triage your issue.)_

|    Q        |   A
|------------ | ------
| Version     | 9.1

### Question

The Writer instance can be created with static _createFrom…_ methods. Base class _AbstractCsv_ then stores the 'document' in a protected _$document_ var. 

Now, for using the Writer instance somewhere else I inject the writer instance in the constructor of a worker class. But how to get in the consuming class the underlying document (or better: the 'target' file), e.g. to tell where the CSV has been written?

My current workaround is injecting both _Writer_ instance and file path (or SplFileObject) – no clean solution.

**Comment by nyamsprod** [comment]
@tomkyle thanks for using the package.

Currently there are no method or simple way to get the target file and the reason is simple. Depending on how the writer was created you may or may not have this information your current workaround is the best alternative IMHO. Another approach would be to expose the document object which means exposing the class internal state which is not a good idea as it is an implementation detail that should not be exposed in the first place.

**Comment by tomkyle** [comment]
Thank you for your fast reply! I see your point with object state which ideally should not be exposed. But the same goes with _getDelimiter_ and _getEnclosure_ which both are public, and nobody would doubt their usefulness. Please let me propose another public method **getPathname** to team up with the first two. Here's why (and how):

**AbstractCsv's** ctor argument $document is either _SplFileObject_ or _Stream_, and anything other than SplFileObject is internally converted to a _Stream_ instance which mimicks the SplFileObject's CSV-related behaviour and internally works with resource types.

The **Stream** class internally uses PHP's [stream_get_meta_data](http://php.net/manual/en/function.stream-get-meta-data.php) function for checking if the resource in question “is_seekable”. The return array of this function also contains an 'uri' element as well – which perfectly exposes the URI/filename associated with this stream, e.g. `php://temp` or `/path/to/myfile.csv`. 

So my proposal is to introduce a **public getPathname** method in **AbstractCsv.** It is part of the SplFileObject API already, and for Stream class, it can be easily implemented using the `uri` key from stream_get_meta_data:

```php
// class Stream:
public function getPathname() : string
{
	$stream_meta = stream_get_meta_data( $this->stream );
	return $stream_meta['uri'];	
}
```

Now both SplFileInfo and Stream class have the getPathname method in common. Implementation now is easy:

```php
//  class AbstractCSV:
public function getPathname() : string
{
	return this->document->getPathname();
}
```
This way, no document object and no internal state would be exposed.

**Comment by nyamsprod** [comment]
@tomkyle if you can demonstrate that SplFileObject::gePathname is equal to the result of stream_get_meta_data (ie: you'd have to check PHP src code) then I'm open to adding such method with a PR from you. So you get full credit for the added behaviour 😉

**Comment by tomkyle** [comment]
@nyamsprod Challenge accepted – well, nearly… I'm not sure about the PHP _source_ code. Was it C? ;-) Please give me a few days, as I'm still contributing too seldom and certainly have to setup a proper testing.

**Comment by nyamsprod** [comment]
Yes it's C but I was able to navigate through even thought I have no good understanding of C 😉 . Don't worry about the time just submit the PR and we will try to make it right. I just want to make sure you're credited for the addition

**Comment by nyamsprod** [comment]
@tomkyle after looking into your proposition I believe a simple PHPUnit test should do the trick instead of going to look into the php source code 😉 .

You just need to be sure that the following test does not fail.

```php
/**
 *
 * @dataProvider getPathnameProvider
 */
public function testCsvGetPathName($path, $expected)
{
    self::assertSame($expected, Reader::createFromPath($path)->getPathname());
    self::assertSame($expected, Reader::createFromFileObject(new SplFileObject($path)->getPathname());
}

public function getPathnameProvider()
{
    return [
        'absolute path' => [
            'path' => dirname(__DIR__).'/data/foo.csv',
            'expected' => dirname(__DIR__).'/data/foo.csv',
        ],
        'relative path' => [
            'path' => './../data/foo.csv',
            'expected' => './../data/foo.csv',
        ],
        'tmp file' => [
            ....
        ],
        'external uri' => [
            ....
        ],
    ];
}
```

**Comment by nyamsprod** [comment]
well that's not our concern the return value is the correct one it may not be of any help but that's another issue altogether. As far as I'm concern the same thing happens if you create two instances of `SplTempFileObject` so it's predicable and expected.

**Comment by nyamsprod** [comment]
Here's the complete test I think .. that will covers your need. to be added to the CsvTest.php file.

```php

    /**
     * @covers ::getPathname
     * @covers League\Csv\Stream::getPathname
     * @dataProvider getPathnameProvider
     */
    public function testGetpathname($path, string $expected)
    {
        self::assertSame($expected, Reader::createFromPath($path)->getPathname());
        self::assertSame($expected, Reader::createFromFileObject(new SplFileObject($path))->getPathname());
    }

    public function getPathnameProvider()
    {
        return [
            'absolute path' => [
                'path' => __DIR__.'/data/foo.csv',
                'expected' => __DIR__.'/data/foo.csv',
            ],
            'relative path' => [
                'path' => 'tests/data/foo.csv',
                'expected' => 'tests/data/foo.csv',
            ],
            'external uri' => [
                'path' => 'https://raw.githubusercontent.com/thephpleague/csv/8.x/test/data/foo.csv',
                'expected' => 'https://raw.githubusercontent.com/thephpleague/csv/8.x/test/data/foo.csv',
            ],
        ];
    }

    /**
     * @covers ::getPathname
     * @covers League\Csv\Stream::getPathname
     */
    public function testGetPathnameWithTempFile()
    {
        self::assertSame('php://temp', Writer::createFromString('')->getPathname());
        self::assertSame('php://temp', Writer::createFromString(new SplTempFileObject())->getPathname());
    }
```

**Comment by tomkyle** [comment]
Yep, that's possible :)

**Comment by nyamsprod** [comment]
this feature will be release in version 9.2.0 following the acceptance of PR #321

**Comment by nyamsprod** [comment]
I've just updated the documentation https://csv.thephpleague.com/9.0/connections/instantiation/#accessing-the-csv-document-path

Now I just need one confirmation from the PHP internals and 9.2.0 will be released 😉  thanks for the contribution. I've referenced it on the CHANGELOG.md file too

**Comment by tomkyle** [comment]
It was a pleasure :-)
