### ISSUE TITLE
Reader::createFromPath "no such file or directory"

### ISSUE THREAD

**Issue by working-name** [thephpleague/csv#326]
I used composer to install your lib, and your example code to open a csv file. It states

```
Fatal error: Uncaught League\Csv\Exception: `/usr/local/var/www/shitproject/all-data-2018.CSV `: failed to open stream: No such file or directory in /usr/local/var/www/shitproject/vendor/league/csv/src/Stream.php:179 Stack trace: #0 /usr/local/var/www/shitproject/vendor/league/csv/src/Reader.php(69): League\Csv\Stream::createFromPath('/usr/local/var/...', 'r', NULL) #1 /usr/local/var/www/shitproject/letter.php(13): League\Csv\Reader::createFromPath('/usr/local/var/...', 'r') #2 {main} thrown in /usr/local/var/www/shitproject/vendor/league/csv/src/Stream.php on line 179				
```

I strongly disagree with that assessment. The file exists and is readable to the user which runs php. Running `shell_exec('tail all-data-2018.CSV')` returns the file's content as expected. 

```
-rw-r--r--@ 1 zeeman  staff  138504 Feb 11 19:22 /usr/local/var/www/shitproject/all-data-2018.CSV
```
I also used `$csv = Reader::createFromPath($inputCSV, 'r')->fetchOne();` which outputs the same error. 

|    Q        |   A
|------------ | ------
| Version     | 9.1.4

### Question

Am I battling a php bug or is this part of your lib?

**Comment by nyamsprod** [comment]
@working-name thanks for using the library. FWIW, I believe it is an issue with how the library is used. You should check how your PHP/Servers settings are. In any case, this is not related to the library or PHP. Sorry for not being more helpful 😢 .
