### ISSUE TITLE
How to convert encoding from utf8mb4 to CP-1251

### ISSUE THREAD

**Issue by petarvasilev91** [thephpleague/csv#327]
I am trying to fetch some data from a database table and then use that to make a CSV. The encoding in my database is "utf8mb4_unicode_ci" and the CSV needs to be in "CP-1251", is this the right way to convert it:

`CharsetConverter::addTo($writer, 'utf8mb4_unicode_ci', 'CP-1251');`

**Comment by nyamsprod** [comment]
@petarvasilev91 the CharsetConverter follow [the naming convention of PHP's mbstring extension](http://php.net/manual/en/mbstring.encodings.php) as describe in the documentation website.

**Comment by petarvasilev91** [comment]
@nyamsprod I tried using UTF-8 but it broke my code...
