### ISSUE TITLE
Got "The stream filter API can not be used" when trying convert from UTF-8 to Windows-1251

### ISSUE THREAD

**Issue by petarvasilev91** [thephpleague/csv#328]
This is the error in my log: "[2019-02-18 18:51:57] local.ERROR: The stream filter API can not be used {"exception":"[object] (League\\Csv\\Exception(code: 0): The stream filter API can not be used at /var/www/domovakniga.local/vendor/league/csv/src/AbstractCsv.php:476)"

Here is the code that's causing it:

`CharsetConverter::addTo($csv, 'UTF-8', 'Windows-1251');`

here is the line before that, creating $csv:

`$csv = Writer::createFromFileObject(new SplTempFileObject());`

any idea what I am doing wrong?

**Comment by nyamsprod** [comment]
Yes please refer to the documentation website where all is clearly explained about stream usage
