### ISSUE TITLE
strict_types and syntax error

### ISSUE THREAD

**Issue by kashifau** [thephpleague/csv#333]
Hi. Everything was working fine on my laravel web application when I suddenly started facing following issues:

Warning: Unsupported declare 'strict_types' in ../vendor/league/csv/src/functions.php on line 13

Parse error: syntax error, unexpected ':', expecting '{' in ../vendor/league/csv/src/functions.php on line 29

Any idea why is it being caused?

**Comment by nyamsprod** [comment]
You should check your PHP version this has nothing to do with the library I'm afraid

**Comment by the-duke** [comment]
Hi kashifau, i have exact the same problem running php version 7.2.16. How did you solve this issue?
Thanks

**Comment by kashifau** [comment]
@the-duke I am using GoDaddy server and turned out php version was changed somehow. I changed the php version from cpanel and issue was solved.
