### ISSUE TITLE
How do I offset the header and still refer to each record with a numerical index?

### ISSUE THREAD

**Issue by ryanmortier** [thephpleague/csv#336]
|    Q        |   A
|------------ | ------
| Version     | 9.2.0

### Question

I just upgraded from version 8 where I was using `->setOffset(1)` to skip the header and then I would refer to the columns with `$record[0]`, `$record[1]`, `$record[2]`, etc.

Since upgrading though, `->setOffset()` doesn't exist and looks like it was replaced with `->setHeaderOffset()` but my problem is that when using this method to skip the header, I now have to refer to my columns by the column name, e.g. `$record['Account Number']`.

Since I'm not sure if the headers will ever change, I don't want to hard code them into the import routine. Is there a way to skip the header and still have a numerical index for the columns?

**Comment by nyamsprod** [comment]
I believe this is explain in the upgrade section in the documentation website https://csv.thephpleague.com/9.0/upgrading/

**Comment by ryanmortier** [comment]
Ah sorry, it is. Thanks.
