### ISSUE TITLE
How to use encloser only when needed?

### ISSUE THREAD

**Issue by andre-hh** [thephpleague/csv#338]
|    Q        |   A
|------------ | ------
| Version     | 9.2

### Question

The default implementation of the Writer (see below) encloses values that contain spaces, although this is not necessary (as neither the enclose character nor the delimiter is part of the field). How can we achieve that only values are enclosed, where enclosing is really necessary, i.e. the enclose character or the delimiter is used?

    $writer = Writer::createFromPath('php://temp');
    $writer->insertOne(['first name', 'last name', 'email']);
    $writer->insertAll([['john,"jonnie', 'do doe', 'john.doe@example.com'],]);

    // This is successful
    $this->assertEquals(
        '"first name","last name",email
        "john,""jonnie","do doe",john.doe@example.com',
        $writer->getContent()
    );

**Comment by nyamsprod** [comment]
The package is based on PHP parser/writer and its philosophy is to be relax when parsing but conservative when writing CSV. And yes sometimes more fields are enclosed but the gain is that any decent csv parser will still be able to parse PHP generated CSV. 
Bottom Line, currently unless using a sofisticated filter mechanism this is not possible with the current codebase. 
Maybe this can be reviewed when the time  for a New major release will come. In the meantime I believe the following package is able to do it 😉 https://github.com/parsecsv/parsecsv-for-php

**Comment by andre-hh** [comment]
Thanks @nyamsprod.

The downside of https://github.com/parsecsv/parsecsv-for-php is that it does not work with streams, right?

For now I've built a stream filter but it'll probably not cover all cases and will definitely be not very performant...

```class FixEnclosureFilter extends php_user_filter
{
    /**
     * @throws \League\Csv\Exception
     */
    function filter($in, $out, &$consumed, $closing): int
    {
        $delimiter = $this->params[0];
        $enclosure = $this->params[1];

        while ($bucket = stream_bucket_make_writeable($in)) {

            $reader = Reader::createFromString($bucket->data);
            $reader->setDelimiter($delimiter);
            $reader->setEnclosure($enclosure);

            $row = '';
            $fields = $reader->fetchOne();
            for ($i = 0; $i < count($fields); $i++) {
                if ($i > 0) {
                    $row .= $delimiter;
                }

                if ((strpos($fields[$i], $enclosure)) !== false
                    || (strpos($fields[$i], $delimiter) !== false)
                    || (strpos($fields[$i], "\n") !== false)
                    || (strpos($fields[$i], "\r") !== false))
                {
                    // Escape enclosure with enclosure
                    $fields[$i] = str_replace($enclosure, $enclosure . $enclosure, $fields[$i]);

                    $fields[$i] = $enclosure . $fields[$i] . $enclosure;
                }

                $row .= $fields[$i];
            }
            $row .= PHP_EOL;

            $bucket->data = $row;

            $consumed += $bucket->datalen;
            stream_bucket_append($out, $bucket);
        }

        return PSFS_PASS_ON;
    }
}
