### ISSUE TITLE
Delimiter not recorgnized correctly between chinese characters

### ISSUE THREAD

**Issue by erystasius** [thephpleague/csv#339]
### Bug Report

| Information | Description |
|--------------|---------|
| Version | 9.2 |
| PHP version | 7.2 |
| OS Platform | Windows 10 1809 |

#### Summary

Delimiter not recorgnized correctly between chinese characters.

#### Standalone code, or other way to reproduce the problem

```
$reader = League\Csv\Reader::createFromString("支,金\n号,商\n");
foreach ($reader as $record) {
    print_r($record);
}
```

#### Expected result

```
Array
(
    [0] => 支 
    [1] => 金

)
Array
(
    [0] => 号 
    [1] => 商

)
```

#### Actual result
```
Array
(
    [0] => 支,金

)
Array
(
    [0] => 号,商

)
```

**Comment by nyamsprod** [comment]
Hi did you try the recommended method explained in the documentation 🤔 https://csv.thephpleague.com/9.0/converter/charset/

**Comment by erystasius** [comment]
> Hi did you try the recommended method explained in the documentation 🤔 https://csv.thephpleague.com/9.0/converter/charset/

I'm not sure how I'm supposed to use the converter. I can confirm the string is encoded in utf-8 (as you see, I hard code it, not taking from file), so which encoding should I convert it to? I write some code as below, but I don't get the point.

```
$encoder = (new CharsetConverter())
    ->inputEncoding("utf-8")
    ->outputEncoding("utf-8");
$reader = Reader::createFromString("支,金\n号,商\n");
$records = $encoder->convert($reader);
foreach ($records as $record) {
    print_r($record);
}
```

```
Array
(
    [0] => 支,金

)
Array
(
    [0] => 号,商

)
```

**Comment by erystasius** [comment]
FYI, the same piece of code works as expected under linux.

**Comment by nyamsprod** [comment]
so if it works under linux but not Windows maybe you should check the locale installed in your Windows server to see if they are correctly picked up by PHP. To me it seems more like a locale dependent thing rather than a bug one

**Comment by erystasius** [comment]
nevermind, i deploy my program on linux now

**Comment by ganlvtech** [comment]
https://www.php.net/manual/en/function.fgetcsv.php

> Note:
>
> The locale settings are taken into account by this function. If LC_CTYPE is e.g. en_US.UTF-8, files in one-byte encodings may be read wrongly by this function.

This notice may lead to some misunderstanding. And it's added here because I submit this issue https://bugs.php.net/bug.php?id=72330 years ago.

Finally, the simpliest way to fix this problem on Windows (Chinese version with default code page cp936) is

```php
setlocale(LC_CTYPE, "en.UTF-8");
```

or

```php
setlocale(LC_CTYPE, "zh-CN.UTF-8");
```

Don't use `zh_CN` or `en_US` because Windows use `-` instead of `_`.

See:

* https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setlocale-wsetlocale
* https://docs.microsoft.com/en-us/cpp/c-runtime-library/language-strings

**Comment by wgy855** [comment]
@ganlvtech, you are my saver. Thanks a lot.
