### ISSUE TITLE
Option for checking row consistency

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/csv#34]
It would be a really nice feature if both the Reader and the Writer could check whether the row lengths in the file are consistent. The Writer should probably throw an Exception if strict check is enabled, and someone tries to write a row, which is not consistent with the file.

I've created my own CSV package, as there were no decent CSV packages at that time. You can check it [here](https://github.com/indigophp/csv). The row consistency check is implemented.

**Comment by nyamsprod** [comment]
A quick follow up just to say that in the upcoming v7 this functionality is removed from the `Writer` class and is now implemented as a pluggable system. Please check the [migration guide](http://csv.thephpleague.com/upgrading/7.0/#row-consistency-check) for more information

**Comment by sagikazarmark** [comment]
Thanks for letting me know
