### ISSUE TITLE
How do I remove the character “ï»¿” from the beginning of a csv file

### ISSUE THREAD

**Issue by inquisitive-stha** [thephpleague/csv#340]
Version : 9.0

###Question

I am trying to read CSV file using CSV league as follows:

```

            $csv_file_path = storage_path('app/files/').$filename;
            if (!ini_get("auto_detect_line_endings")) {
                ini_set("auto_detect_line_endings", TRUE);
            }
            $csv = Reader::createFromPath($csv_file_path, 'r');
            $csv->setOutputBOM(Reader::BOM_UTF8);
            $csv->addStreamFilter('convert.iconv.ISO-8859-15/UTF-8');
            $csv->setHeaderOffset(0); //set the CSV header offset
            $csv_header = $csv->getHeader();    

            $stmt = (new Statement())
            ->offset($offset)
            ->limit($limit)
            ;

            $records = $stmt->process($csv);
```

But, I encounter some weird character like “ï»¿” at the beginning. After some searching, I found that it needs to be converted to UTF-8.

On its documentation, it suggests something like

```
$csv = Reader::createFromPath('/path/to/your/csv/file.csv', 'r');
$csv->setHeaderOffset(0);

$input_bom = $csv->getInputBOM();

if ($input_bom === Reader::BOM_UTF16_LE || $input_bom === Reader::BOM_UTF16_BE) {
    $csv->addStreamFilter('convert.iconv.UTF-16/UTF-8');
}

foreach ($csv as $record) {
    //But I could not figure out what to include here. 
}
```

Could anyone suggest me how can I handle this scenario?

**Comment by nyamsprod** [comment]
@inquisitive-stha and what is it that you do not to understand :thinking: . Once you've converted your CSV you can use the `Statement` object like you describe. I fail to understand your question :cry:

**Comment by inquisitive-stha** [comment]
Ok let's forget about the second code block. Just look at the first code block, now say me how can I remove that character from code block 1?

**Comment by nyamsprod** [comment]
Again I don't understand what you want to do I was under impression that you wanted to **read** your CSV so why use the `setOutputBOM` you only need this if you want to output your document ?
Also you should read the documentation about how the [Reader works](https://csv.thephpleague.com/9.0/reader/#records-normalization) it will help you resolve your issue.

**Comment by inquisitive-stha** [comment]
I have updated question, please go through it. And i could not understand, why this is already closed. 😕 When you are not understanding the question itself.

**Comment by nyamsprod** [comment]
I've provided a link to the documentation explaining how the reader works you should follow the instructions their to help you solve your issue. The issue is not about the package but on how you should use it and it is already answered on the link provided from the documentation website.

**Comment by inquisitive-stha** [comment]
I have updated the code to something like: 
```

            $csv_file_path = storage_path('app/files/').$filename;
            if (!ini_get("auto_detect_line_endings")) {
                ini_set("auto_detect_line_endings", TRUE);
            }
            $csv = Reader::createFromPath($csv_file_path, 'r');
            
            $input_bom = $csv->getInputBOM();

            if ($input_bom === Reader::BOM_UTF16_LE || $input_bom === Reader::BOM_UTF16_BE) {
                $csv->addStreamFilter('convert.iconv.UTF-16/UTF-8');
            }
     
            $csv->setHeaderOffset(0); //set the CSV header offset
            $csv_header = $csv->getHeader();    

            $stmt = (new Statement())
            ->offset($offset)
            ->limit($limit)
            ;

            $records = $stmt->process($csv);
```
But, I am still getting the same characters. Instead of the link and other stuff, if you suggest me some code snippet. Which line need to be included where then I could have already gone.

**Comment by nyamsprod** [comment]
I won't suggest any code snippet because your issue it with your file encoding ... you should try to determine how your file is really encoded. Sometimes the BOM character is misleading if the file is badly saved. Anyway this depends on how you obtain, stored and retrieive your document which as you can imagine is out of scope for this library.
