### ISSUE TITLE
HTML output table header row

### ISSUE THREAD

**Issue by adrienne** [thephpleague/csv#344]
_(Fill in the relevant information below to help triage your issue.)_

|    Q        |   A
|------------ | ------
| Version     | 9.2

### Question

I have the following code, expecting that my HTML conversion would output the header row with `<th>` tags. Instead it doesn't output the first row at all. 

```
$reader = Reader::createFromString($csvString);
$reader->setHeaderOffset(0);
$converter = (new HTMLConverter())
        ->table('dimensions-table')
        ->tr('data-record-offset')
        ->td('title');

$html = $converter->convert($reader);
```

If I remove `$reader->setHeaderOffset(0);` it does output the first row, but there is still no table header with `<th>` elements. Is there a way to properly output a header row?

**Comment by nyamsprod** [comment]
@adrienne thanks for using the library. Currently there's no way to assign the `<th>` tag to the converted HTML. But I'll welcome any PR adding this functionality to the current codebase. Should not even BC break.

**Comment by nyamsprod** [comment]
@adrienne to be more specific this class converts any tabular data not just the reader so the main issue if one wants to add this feature is to figure out how to make it works with any tabular data not just the Reader object.
