### ISSUE TITLE
Archive a CSV

### ISSUE THREAD

**Issue by engharb** [thephpleague/csv#349]
_(Fill in the relevant information below to help triage your issue.)_

|    Q        |   A
|------------ | ------
| Version     | 9.2

### Question

How can I archive a created CSV File?

**Comment by nyamsprod** [comment]
@engharb thanks for using the library.

What do you mean by archiving a created file ? do you have an example ?

**Comment by engharb** [comment]
@nyamsprod after I create a CSV I want to zip it 'to compress'. Is there a way how to do? I have tried  different ways with no success.

```
$csv = Writer::createFromPath('php://temp', 'w+');
$csv->insertOne($testData);
```

I want this $csv object to be zipped.

**Comment by nyamsprod** [comment]
CSV can be used with resource so I would suggest using the following snippet. **Not tested but should do the trick***

```php
<?php
use League\Csv\Writer;

$stream = gzopen("/path/to/compress/file.csv.gz", "w");
$csv = Writer::createFromStream($stream);
$csv->insertOne($record);
unset($csv);
gzclose($stream);
```
