### ISSUE TITLE
Write to a Cloud Storage file

### ISSUE THREAD

**Issue by alexeydemin** [thephpleague/csv#350]
I try to find the proper way to write to a file located on Google Cloud Storage on Laravel 5.7:
```
$path = 'testfile.txt';
Storage::disk('gcs')->put($path, null);
$stream = Storage::disk('gcs')->readStream($path);
$writer = Writer::createFromStream($stream);
$writer->insertOne(['test']);
```

It does not work, I get an empty file.

**Comment by NickToony** [comment]
I believe the $writer object is in local memory (created from the read stream), and you never actually write it back to GCS. This may help:

```
...
// Read from GCS stream
$stream = Storage::disk('gcs')->readStream($path);
$writer = Writer::createFromStream($stream);
// Edit the CSV in memory
$writer->insertOne(['test']);
// Write back to GCS
Storage::disk('gcs')->put($path, $writer->getContent());
```

**Comment by nyamsprod** [comment]
@alexeydemin the Writer uses stream so you just need to configure them properly as per GCS documentation see [stream options](https://cloud.google.com/appengine/docs/standard/php/googlestorage/advanced#permissions_caching_and_metadata_options)

**Comment by alexeydemin** [comment]
@nyamsprod I'll be really appreciated if you could direct me with a simple code example. Thank you!

**Comment by nyamsprod** [comment]
@alexeydemin [it's already documented](https://csv.thephpleague.com/9.0/connections/instantiation/#loading-from-a-file-path) 😄
