### ISSUE TITLE
BOM detection restricts stream usage with the Reader class

### ISSUE THREAD

**Issue by clcastro87** [thephpleague/csv#352]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

#### Proposal

_I would like to be able to use I/O streams. It's a great feature to support reading and writing from/to streams. But actually I/O streams are not supported (php://stdin, php://stdout)_

**Comment by nyamsprod** [comment]
@clcastro87 could you be more specific as the library supports PHP stream since version 8.2 [see documentation](https://csv.thephpleague.com/9.0/connections/instantiation/) with the Reader supporting any input stream and the writer writing to any output stream

**Comment by clcastro87** [comment]
@nyamsprod I'm using version 9.3. The issue is only for php://stdin. When I'm trying to read from stdin is throwing `stream does not support seeking`. I suppose is because php://stdin is not seekable. On file src/Stream:483 there is a check for this. My use case is that I'm trying to pipe to the php process in input using the console. Ex: cat myfile.csv | grep important | php mytest.php. I know maybe I can copy to a tmpfile and then process the stream but for huge file this is an extra waiting because I'll need to copy the entire input stream to a temp file and then start processing. I hope that you can understand my case. Thanks!

**Comment by nyamsprod** [comment]
@clcastro87 I think this exception is only triggered if you try to setup the header of your CSV file ... so yep if you really need the header it's obvious that the CSV needs to be seekable ... so if you don't need the header it should be fine IMHO ... I haven't tested it so I may be wrong.

**Comment by clcastro87** [comment]
@nyamsprod Sorry for the delay but I've been very busy the last two days. As you said of course if I try to read from stdin I'll need the field names (header). Maybe I'm doing something dumb but here you can have a simple piece of code to prove what I\m saying. 
`
$res = fopen('php://stdin', 'r');
$fields = [
    "title", 
    "brand", 
    "link", 
    "image_link",
    "price", 
    "description", 
    "gender", 
    "id", 
    "availability", 
    "google_product_category", 
    "age_group", 
    "size", 
    "color", 
    "adult", 
    "sale_price", 
    "gtin", 
    "mpn"
];
$reader = League\Csv\Reader::createFromStream($res);
foreach ($reader->getRecords($fields) as $item) {
    var_dump($item);
}
`
The error is the following:
`
carlos@carlos-laptop:~/ethyl$ tail test/Products.csv | php src/test2.php 
PHP Fatal error:  Uncaught League\Csv\Exception: stream does not support seeking in /home/carlos/ethyl/vendor/league/csv/src/Stream.php:350
Stack trace:
#0 /home/carlos/ethyl/vendor/league/csv/src/AbstractCsv.php(220): League\Csv\Stream->rewind()
#1 /home/carlos/ethyl/vendor/league/csv/src/Reader.php(269): League\Csv\AbstractCsv->getInputBOM()
#2 /home/carlos/ethyl/src/test2.php(26): League\Csv\Reader->getRecords(Array)
#3 {main}
  thrown in /home/carlos/ethyl/vendor/league/csv/src/Stream.php on line 350
`
Thanks in advance.

**Comment by nyamsprod** [comment]
@clcastro87 I think I know what's the issue .... and it's more of a bug... I/O Streams are supported the _real_ issue is that the `Reader` is trying to strip the BOM characters which is the default behavior from the `Reader` object.

So the solution would be either to disabled BOM stripping or alternatively to be more smart and to detect when to strip BOM.

going back to your issue the *simple* solution/hack would be to extend the `Reader` object ... copy/paste the `getRecords` method and replace the line 269

### before

```php
$bom = $this->getInputBOM();
```

### after

```php
$bom = '';
```

A better solution would be to add the following methods to the Reader and the Writer  parent abstract class. With an added protected property which disabled BOM stripping for specific use like yours... 

```php
protected $isBOMStrippingEnable = true; //avoid BC Break
public function AbstractCsv::enableBOMStripping(): void;
public function AbstractCsv::disableBOMStripping(): void;
public function AbstractCsv::isBOMStrippingEnabled(): bool;
```

While a PR from you would be welcomed I can not guarantee a new release for this feature in the coming weeks as I have many things to do (holidays 😄 ). So maybe it will be done late September  if all goes as plan (which is never the case 😢 )

**Comment by nyamsprod** [comment]
@clcastro87 another alternative would be to add a flag to the `Reader::getRecords` method which add options to how the getRecords should work and the default flag would be 

```php
<?php

Reader::DISABLE_BOM = 1;
Reader::ENABLE_BOM = 0;
Reader::getRecords(array $records = [], int $flags = self::ENABLE_BOM);
```

So as you can see there are many ways to go around this `bug/issue/enhancement`.

**Comment by clcastro87** [comment]
@nyamsprod Thanks for you quick answer, definitely we are not in the same timezone, :). Well, I saw that you made the changes in the feature #353 . I'll try to take a deep look and test it. At least for now I'll try to extend and add the extra flag to the getRecords function, to go quick. Then after the release I'll remove all that noise.

**Comment by nyamsprod** [comment]
I'll close this issue as it has been resolve in the subsequent PR 😉

**Comment by clcastro87** [comment]
> I'll close this issue as it has been resolve in the subsequent PR

Hi @nyamsprod , I have been busy these days, today I tested with the master branch, and the issue cotinues. I tried to be more concise and I found the bug. If we test for example with php://temp, I works fine but php://stdin is not seekable. There is a validation in Stream:349, that checks for seekable stream. I commented the exception throw in line 350 and everything worked as a charm. Sorry for the delay in the response, and all the extra work that I caused, the BOM strip is fixed but because that check the code doesn't work with the stdin. Thanks a lot. If you want I can sent you some sample data and all the command line that I'm using to reproduce the error.

**Comment by clcastro87** [comment]
[Sample.txt](https://github.com/thephpleague/csv/files/3557915/Sample.txt)
<?php
`php
include_once 'vendor/autoload.php';

$res = fopen('php://stdin', 'r');
$fields = [
    "title", 
    "brand", 
    "link", 
    "image_link",
    "price", 
    "description", 
    "gender", 
    "id", 
    "availability", 
    "google_product_category", 
    "age_group", 
    "size", 
    "color", 
    "adult", 
    "sale_price", 
    "gtin", 
    "mpn"
];
$reader = League\Csv\Reader::createFromStream($res);
$reader->preserveInputBOM();
$reader->setDelimiter("\t");
foreach ($reader->getRecords($fields) as $item) {
    var_dump($item);
}
`
The command line is the following:
`bash
tail test/Sample.txt | php src/test2.php 
`

**Comment by nyamsprod** [comment]
While the BOM control is an improvement I have to ask what huge means for you ? 
The thing is the underlying stream class or SplFileObject are SeekIterator so the baseline is that at some point you'll end up with this situation with the library.
The reason I am asking is because the library leverage stream meaning that the whole CSV doc is never loaded in memory which means that even a 10 millions records  document is parsable without much memory usage so if huge is in that order I fail to see how you can not directly use the path in the script.
Making the lib pipe compatible was never in the road map because it would break other part of the lib if I were to remove the seekable restrictions I'm afraid.

**Comment by nyamsprod** [comment]
Also quick question what happens if you use the constant `STDIN` instead of `php://input` ?

**Comment by nyamsprod** [comment]
@clcastro87 after your feedback I've slightly changed the Inout BOM public API to make it abvious which method to use... when 😄 . Hopefully I'll release the new version next week. The change is already documented on the official website.
