### ISSUE TITLE
Store exported file somewhere instead of forcing download

### ISSUE THREAD

**Issue by inquisitive-stha** [thephpleague/csv#357]
| Version     | 19.2.0

### Question

Is there any way, to store the file on the server instead of forcing the user to download the file?

#Scenario
I am trying to export huge CSV files from laravel. So, I am not sure either the following code is efficient to dump all data at the same time. 

```
$people = People::all();
$csv = \League\Csv\Writer::createFromFileObject(new \SplTempFileObject());
        $csv->insertOne(json_decode($data['csv_header']));
        foreach ($people as $person) {
            $csv->insertOne($person->toArray());
        }
        $csv->output('people.csv');
        die;
```

Therefore, I am planning to write data on the chunk i.e. fetching `$people`  up to certain rows only. However, with this method, two questions raised in my mind.

1) Will I be able to write data without removing the old data?
2) Instead of using output, is there any way to store it on the server itself?

**Comment by nyamsprod** [comment]
@inquisitive-stha yes there is. Please refer to the documentation website where everything is explained.

**Comment by inquisitive-stha** [comment]
@nyamsprod Could you please mention the link where you have mentioned, I could not find about it in both https://csv.thephpleague.com/9.0/writer/ and https://csv.thephpleague.com/9.0/connections/output/ as well.

**Comment by nyamsprod** [comment]
What you are looking for is connection https://csv.thephpleague.com/9.0/connections/instantiation/#loading-from-a-file-path

**Comment by inquisitive-stha** [comment]
@nyamsprod I got that loading from the path. Is there any way, to save the file directly to the server after insert all line 
```$csv->insertAll($new_properties);``` 
$csv->output; is just forcing to download on my local computer. I am planning to store data somewhere in the server itself like in location `downloads/filename.csv` and later send this to the user via email.

**Comment by inquisitive-stha** [comment]
@nyamsprod I got it to save the file on the server.  At the moment, my code is something like as follows:

```
        $file_path = storage_path('app\public\exports\properties.csv');
        $csv = Writer::createFromPath($file_path, "w");
        $csv_header = json_decode($data['csv_header']);
        $csv->insertOne($csv_header);
        $new_properties = array();
        foreach($properties as $property){
            $temp_arr = array();
            foreach($map_data as $mv){
                $temp_arr[] = $property->$mv;
            }
            $new_properties[] = $temp_arr;
        }
        $csv->insertAll($new_properties);
```
However, this is overwriting the old data as well. Is there any way to add data without removing the old data. This is because, I am exporting huge records, so to be safe from memory issue, I am exporting with laravel job and looping them. So, at once it would add around 10k records and on next call, I would like to add other 10k records and so on.

##Also, I notice that when the file is open in a window, it could not open the file in write mode. Even on that scenario, it showing the message, `Unable to open, No such file or directory`. It could be better if we could show the message like `Could not open in write mode or so.`

**Comment by nyamsprod** [comment]
Your questions have already been answered too in others closed issues or in the documentation. Please search there because what you are asking is not a issue or a bug or an original question that has never been answered before
