### ISSUE TITLE
Version 8 - is there a maximum number of columns which can be returned?

### ISSUE THREAD

**Issue by jason-dowzell** [thephpleague/csv#359]
We are running on PHP 5.6 so are using v8 as we cannot run v9 - when we use this we are having an issue that any time the result set has more than 116 columns it gets truncated. It only does this in the data rows and not the header row.

We are adding EOL to the end of all our output rows and when running this against larger data sets EOL always appears in column 116 even when there are more than 116 columns in the output - running the query directly in MySQL returns the correct data.

Is this any limitation known in the code? Either number of columns or memory used for example?

**Comment by nyamsprod** [comment]
@jason-dowzell as far as I know there are no limitation, however if you are using a header then you might run into a documented limitation.

> Notes
If the number of values in a CSV row is lesser than the number of named keys, the method will add null values to compensate for the missing values.
If the number of values in a CSV row is greater that the number of named keys the exceeding values will be drop from the result set.
If an offset is used, its content will be skipped in the result set.
If no argument is provided, the first row from the CSV data will be used

see https://csv.thephpleague.com/8.0/reading/#readerfetchassoc

Don't forget that version 8 is EOL so even if a it is a bug ... it won't be fixed.
