### ISSUE TITLE
Throw exceptions with context

### ISSUE THREAD

**Issue by dmlogic** [thephpleague/csv#360]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | yes

#### Proposal

Whenever an exception is thrown it is always a native `Exception`. This can make it hard to figure out what has gone wrong if the CSV handling is just part of a larger process.

I would like to see native `League\Csv\Exception` errors being throw to give some context, for example `StreamException` or `HeaderException`.

I'm very happy to do this work if there's a good chance of it being merged.

**Comment by nyamsprod** [comment]
@dmlogic all exception thrown extends the League\Csv\Exception unless it is not possible for instance for the XMLConverter class. Maybe you could add more specific exceptions but the messages are already self explanatory unless I'm missing something. Either way I fail to see the BC breaks unless the newly added exceptions do not extend the marker exception or you want to throw on new context that currently don't throw

**Comment by dmlogic** [comment]
> the messages are already self explanatory unless I'm missing something

They are, but because only one type of exception is thrown it is necessary to break up code into multiple stages of try/catch to infer the problem from context (I know there's a strong argument that I _should_ be doing that) or do a string comparison on the message.

I'd love to see more specific exceptions, which would probably need to be filed into `League\Csv\Exceptions`, hence the break. Although I guess `League\Csv\Exception` could stay where it is.

**Comment by nyamsprod** [comment]
> I'd love to see more specific exceptions, which would probably need to be filed into `League\Csv\Exceptions`, hence the break. Although I guess `League\Csv\Exception` could stay where it is.

That's an enhancement not a BC break since the new Exceptions would be extending the current exception marker class ... 🤔 . Also there are already specific exception in the root directory like `CannotInsertRecord` exception following this pattern so a subnamespace is not really needed IMHO 😉

**Comment by dmlogic** [comment]
OK - should I do a PR for a `HeaderRowException` or is this a "no"?

**Comment by nyamsprod** [comment]
When will this exception be thrown? I'd rather have a `CannotReadRecord` exception and perhaps a `SyntaxError` but I'm not confident a specific exception for header is necessary

**Comment by dmlogic** [comment]
I propose a straight swap-out for [this one](https://github.com/thephpleague/csv/blob/master/src/Reader.php#L323)

In my case I load a CSV from a stream and specify the header as row zero.

I then call `getRecords()` and only then is the exception thrown. It's therefore unclear that the problem is actually with the header unless I examine the message text. A `HeaderRowException` would make it obvious what was going on.

**Comment by nyamsprod** [comment]
For me that's a SyntaxError and yes because it's lazy loaded it's hard to understand it but that's a SyntaxError

**Comment by nyamsprod** [comment]
If you really want to add more exception I would introduce the following exceptions without BC break

- `League\Csv\SyntaxError` extends `League\Csv\Exception`
- `League\Csv\CannotReadRecord` extends `League\Csv\Exception`
- `League\Csv\CannotAddStreamFilter` extends `League\Csv\Exception`
- `League\Csv\InvalidArgument` extends `League\Csv\Exception`

**Comment by dmlogic** [comment]
Great, I'll try and get that sorted out later today

**Comment by dmlogic** [comment]
I've made a list of existing exceptions against what seems to make sense against your suggestions. I don't obviously see where `CannotReadRecord` fits so maybe we don't need that? I do wonder if a `StreamException` would be useful

|Exception location|Unchanged|`SyntaxError`|`CannotReadRecord`|`CannotAddStreamFilter`|`InvalidArgument`|
|---|---|---|---|---|---|
|`AbstractCsv::__clone`|x|||||
|`AbstractCsv::chunk`|||||x|
|`AbstractCsv::sendHeaders`|||||x|
|`AbstractCsv::setDelimiter`|||||x|
|`AbstractCsv::setEnclosure`|||||x|
|`AbstractCsv::setEscape`|||||x|
|`AbstractCsv::addStreamFilter`||||x||
|`ColumnConsistency::__construct`|||||x|
|`Reader::setHeader`||x||||
|`Reader::setHeaderOffset`|||||x|
|`Reader::computeHeader`||x||||
|`ResultSet::fetchOne`|||||x|
|`ResultSet::getColumnIndexByValue`|||??|||
|`ResultSet::getColumnIndexByKey` : 197|||||x|
|`ResultSet::getColumnIndexByKey` : 209|||??|||
|`Statement::offset`|||||x|
|`Statement::limit`|||||x|
|`Stream::__clone`|x|||||
|`Stream::createFromPath`|x|||||
|`Stream::appendFilter`||||x||
|`Stream::filterControl` :267|||||x|
|`Stream::filterControl` :271|||||x|
|`Stream::filterControl` :278|||||x|
|`Stream::rewind`|x|||||
|`Stream::seek`|x|||||
|`Stream::fseek`|x|||||
|`Writer::setFlushThreshold`|||||x|

**Comment by nyamsprod** [comment]
Nice job,

I'll try to review it when I have time this evening 😉

**Comment by nyamsprod** [comment]
As of now I'm ok with the proposed list.

`ResultSet::getColumnIndexByValue` and  `ResultSet::getColumnIndexByKey` should throw an `InvalidArgument` exception.

And indeed there seems to be no need for the `CannotReadRecord` exception at the moment. Maybe the list will be reviewed on the next major release which is not yet in the roadmap 😉 .

**Comment by dmlogic** [comment]
OK, PR done but I confess I don't understand why that PHP7.2 build is failing.

With the tests I've changed them to look for the new exceptions. For BC I've added a new test to verify that all exceptions extend the base class.

**Comment by nyamsprod** [comment]
I've merge the related PR... I'll have to update the changelog and the documentation and then a 9.5 release will be on its way . Hopefully it will happen before end of month  😉  thanks for the work. Look forward for the addition of your name in the changelod 👍

**Comment by dmlogic** [comment]
thank you for accommodating me on this one!
