### ISSUE TITLE
Autowire of CsvReader fails: it references class "League\Csv\Reader" but no such service exists

### ISSUE THREAD

**Issue by ZaneCEO** [thephpleague/csv#362]
### Bug Report

| Information | Description |
|--------------|---------|
| Version | 9.4.1 |
| PHP version | 7.3  |
| OS Platform | Linux |
| Symfony | 4.3.8 |

#### Summary

When I try to autowire any element (Controller, Service, Command, ...) with CsvReader I get tan error (see below).

The package was installed as `composer require league/csv`.

I've no problem if I don't autowire but I just use `Reader::createFromPath`

#### Standalone code, or other way to reproduce the problem

````
<?php

namespace App\Controller;

use League\Csv\Reader;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class ZztestController extends AbstractController
{
    /**
     * @Route("/zztest", name="app_zztest")
     */
    public function index(Reader $csvReader)
    {
    }
}
````

#### Actual result

Exception:

`Cannot autowire argument $csvReader of "App\Controller\ZztestController::index()": it references class "League\Csv\Reader" but no such service exists`

**Comment by nyamsprod** [comment]
@ZaneCEO this issue has nothing to do with the library but has everything to do with how autowiring is set up in your symfony application please check with symfony documentation has there's nothing I can do to solve your issue.

https://symfony.com/doc/4.4/service_container/factories.html#passing-arguments-to-the-factory-method

**Comment by ZaneCEO** [comment]
Thanks for you pointer, I'll study it right away.
