### ISSUE TITLE
Add option to return results as objects instead of arrays

### ISSUE THREAD

**Issue by kokoshneta** [thephpleague/csv#370]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

#### Proposal

I have a personal dislike of working with arrays more than necessary – I find objects, in general, more to my liking. As a result, when I use this library, I usually convert each result in a Reader result set to an object before doing whatever I need to do with it. This isn’t really much of a bother, but it does feel a bit redundant to first create an array and then convert it to an object.

Would it be possible to add an option to the class that allows you to set whether each result in a result set should be returned as an array (default, to avoid breaking BC) or as an object? Something along these lines:

```php
$csv = Reader::createFromPath($path);
$csv->setDelimiter($delimiter);
$csv->setResultType('array' | 'object');
```

This would be pure syntactic sugar, of course, but it would provide an enhanced user experience for people like me with our odd little idiosyncracies.

**Comment by nyamsprod** [comment]
@kokoshneta what you are proposing is called object or array hydratation and there are some stable and specialized libraries for that. your request is IMHO out of scope for the library main objective.

**Comment by nyamsprod** [comment]
@kokoshneta the feature you had requested is being worked on currently on the master branch with the documentation already available here. 
Any feedback from you is welcomed

https://csv.thephpleague.com/9.0/reader/record-mapping/
