### ISSUE TITLE
Make PHP 7.2 and 7.3 compatible

### ISSUE THREAD

**Issue by ozheller** [thephpleague/csv#372]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

#### Proposal

We are using php 7.2 and 7.3. I am unable to install the league/csv with composer because of the php version constraint of ^7.0.8. 

#### ERROR
Here is the error we see when running `composer require league/csv:^9.0`
```
[InvalidArgumentException]                                                                           
  Package league/csv at version ^9.0 has a PHP requirement incompatible with your PHP version (7.0.8) 
```

**Comment by nyamsprod** [comment]
@ozheller thanks for using the library as you can clearly see from your report your PHP version `your PHP version (7.0.8)` is not supported by the current library which support all PHP7 version starting with `PHP 7.0.10` as reported in the `composer.json` file of the current stable release.

**Please make sure you are using a stable and maintained version of PHP or a version supported by the stable release of `league/csv`.**

**Comment by ozheller** [comment]
Thanks @nyamsprod. My project composer.json was locked at 7.0.8.
