### ISSUE TITLE
Charset conversion (open a file, convert, save)

### ISSUE THREAD

**Issue by TechOverflow** [thephpleague/csv#373]
|    Q        |   A
|------------ | ------
| Version     | 9.5.0

### Question

How would I go about using the documented code

```
use League\Csv\CharsetConverter;

$csv = new SplFileObject('/path/to/french.csv', 'r');
$csv->setFlags(SplFileObject::READ_CSV | SplFileObject::SKIP_EMPTY);

$encoder = (new CharsetConverter())->inputEncoding('iso-8859-15');
$records = $encoder->convert($csv);
```

to simply open the file, convert the encoding, save the file with the same filename?

Also, it would be nice if there was a reference to which encoding types are supported. According to an online linter, the source CSV is in `ASCII-8bit` format and I need to convert to `UTF-8`. Is ASCII supported?

Thanks!

**Comment by nyamsprod** [comment]
@TechOverflow thanks for using the library
> Also, it would be nice if there was a reference to which encoding types are supported. According to an online linter, the source CSV is in ASCII-8bit format and I need to convert to UTF-8. Is ASCII supported?

there's a link on the documentation page which leads to the supported charset. Also I would prefer you differ your question to a better supporting channel like slack overflow or reddir /r/phphelp where dedicated php developer will be more than willing to assist you in resolving you business requirement.
