### ISSUE TITLE
The header record must be empty or a flat array with unique string values.

### ISSUE THREAD

**Issue by inquisitive-stha** [thephpleague/csv#374]
I have a CSV file with some unnecessary text in some other column with no header. So, it is throwing error.

I have code something like:

```
        $csv = Reader::createFromPath($path, 'r');
        $csv->setOutputBOM(Reader::BOM_UTF8);
        $csv->addStreamFilter('convert.iconv.ISO-8859-15/UTF-8');

        $csv->setHeaderOffset(0);
        $csv_header = $csv->getHeader();
        $sample_data = $csv->fetchOne(); //this fetchOne line is throwing this error.
```
Is there any way to ignore the column if there is no header for that column?

**Comment by nyamsprod** [comment]
@inquisitive-stha there's a solution for that in the documentation under the getRecords usage

**Comment by inquisitive-stha** [comment]
@nyamsprod I have read this getRecordsUsage part, and find about  `skipEmptyRecords` . However, even I follow the exact same technique as shown in documentation as 

```
        $csv->setHeaderOffset(0);
        $csv->skipEmptyRecords();
        $csv->isEmptyRecordsIncluded();
        $res = iterator_to_array($csv, true);
        print_r($res);
        exit();
```

it is still showing the same error.

And, one thing what I am trying to mention is that I am not talking about skipping an empty row.

I have a file with data something as shown in figure.

![image](https://user-images.githubusercontent.com/16288854/74333682-8e056800-4dc0-11ea-85af-b3909a108119.png)

As you can see there is some extra data and I want that to be stripped. If there is no header on that particular column. Should ignore those extra data.

**Comment by inquisitive-stha** [comment]
@nyamsprod any update on this?

**Comment by nyamsprod** [comment]
@inquisitive-stha like I said in my previous answer, all is explained in the documentation. I can not offer you more information as this is clearly not a bug. Since this channle is mainly forreporting bug and talking about the library development through feature request and PR I think you should ask the question on SO or reddit where the PHP community will be more than happy to help you at in resolving your problem,

kindly

**Comment by inquisitive-stha** [comment]
@nyamsprod Can't we update `computeHeader` function to something like

```
    protected function computeHeader(array $header)
    {
        if ([] === $header) {
            $header = $this->getHeader();
        }

        if ($header === array_unique(array_filter($header, 'is_string'))) {
            return $header;
        }
        //additional condition
        if(count(array_filter($header)) != count($header)) {
            throw new \Exception('One or More column is missing its header');
        }

        throw new SyntaxError('The header record must be empty or a flat array with unique string values');
    }
```

As it does not makes much sense by showing `SyntaxError` to the end-user. Currently, it's showing

```
 protected function computeHeader(array $header)
    {
        if ([] === $header) {
            $header = $this->getHeader();
        }
 
        if ($header === array_unique(array_filter($header, 'is_string'))) {
            return $header;
        }
 
        throw new SyntaxError('The header record must be empty or a flat array with unique string values');
    }
```

I don't think its actually a syntax error.

**Comment by nyamsprod** [comment]
@inquisitive-stha no we can't because you are using the method incorrectly.
