### ISSUE TITLE
Add missing csv headers when converting csv to xml

### ISSUE THREAD

**Issue by DRN88** [thephpleague/csv#375]
|    Q        |   A
|------------ | ------
| Version     | 9.0

### Question

Is there a way to manually set column headers?
I have an auto-generated csv file from a supplier, without headers.
The csv is ordered and has fixed number of columns.

My goal is to achieve this:

Example csv (no headers):
```john, doe, info@domain.local```

After converting to xml, it should be like this:
```
<?xml version="1.0" encoding="utf-8" ?>
<myroot>
  <firstname>john</firstname>
  <lastname>doe</lastname>
  <email>info@domain.local</email>
</myroot>
```
Can I specify my headers somehow, like in an array?
```$headers = [ 'firstname', 'lastname', 'email' ];```

Do I really have to rewrite the csv? (insertOne($headers), then insertAll($originalCsv).
Is there a more simple way to do this?

Thanks for your reply in advance.

**Comment by nyamsprod** [comment]
@DRN88 thanks for using the library. Please read the documentation for the Reader class where you'll find an explanation and an example of how to achieve that.
