### ISSUE TITLE
skipEmptyRecords not skipping empty records

### ISSUE THREAD

**Issue by inquisitive-stha** [thephpleague/csv#383]
v 9.4.0
### Question

I have 5-6 empty lines at the end of the CSV file but they are still being processed despite `skipEmptyRecords`.

```
$csv = Reader::createFromPath($path, 'r');
$csv->skipEmptyRecords();

$csv->setHeaderOffset(0);
$csv_header = $csv->getHeader();

$stmt = (new Statement())
    ->offset('0')
    ->limit('20')
;

$records = $stmt->process($csv);
foreach($records as $record){
    print_r($record); //here it listing all the empty records as well
}
exit();
```
My file looks like:
![image](https://user-images.githubusercontent.com/16288854/78760601-1fe4b800-79a1-11ea-89e2-725b7213c302.png)

**Comment by nyamsprod** [comment]
@inquisitive-stha please refer to the documentation the `skipEmptyRecords` is enable by default to avoid BC break. An empty line is a line with no value whatsoever. In your example the lines are not empty they contains `,`. Which is converted in a non empty array so the behavior is expected.

**Comment by inquisitive-stha** [comment]
Actually, there are no space between those commas. With space it looks like: 

![image](https://user-images.githubusercontent.com/16288854/79048120-82a4b080-7c3a-11ea-850e-e61f3351f1e3.png)

Any idea about this?

**Comment by luonghieu** [comment]
@nyamsprod  Your answer was "the lines are not empty they contains ," But ',' is delimiter of file csv.
Can you tell me I can set delimiter for what to lines become empty.

**Comment by nyamsprod** [comment]
@luonghieu an empty record is an empty array, a line with only empty fields **is not an empty record**

**Comment by inquisitive-stha** [comment]
@luonghieu row with empty values won't be trimmed by default. I have write a custom function, you can take a look here:

```
    public function trimArray($arr)
    {
        $final = array();
        foreach($arr as $k => $v)
        {
            if(array_filter($v)) {
                $final[] = $v;
            }
        }
        return $final;
    }
```
It would have been better if csvleague had used inbuilt functions.

**Comment by nyamsprod** [comment]
@inquisitive-stha nothing prevents you to create a filter to use with the `Statement` class my 2 cents. Also to be fair. This is a business logic situation that has nothing to do with the package. I tend to refuse adding too much logic in CSV as this makes the package too much opinionated for small edge cases.

**Comment by luonghieu** [comment]
@nyamsprod @inquisitive-stha 
Thanks so much, i understand your solution.
My solution from your support
`$stmt = (new Statement())
    ->where(function (array $record) {
        return (bool) array_filter($record);
    });
;`
