### ISSUE TITLE
There is any way to process large amount of data?

### ISSUE THREAD

**Issue by bavamca** [thephpleague/csv#384]
There is any way to process a large amount of data?, like my CSV has 45000 records, how to process without server fail, any chunk method available?, can we process 1000 by 1000 records

**Comment by inquisitive-stha** [comment]
https://csv.thephpleague.com/9.0/reader/#advanced-usage

This might be something you are looking for.

```
use League\Csv\Reader;
use League\Csv\Statement;

$reader = Reader::createFromPath('/path/to/my/file.csv', 'r');
$stmt = (new Statement())
    ->offset(3)
    ->limit(5)
;

$records = $stmt->process($reader);
```

**Comment by nyamsprod** [comment]
@bavamca please refer to the documentation where the library capabilities are well explained.
