### ISSUE TITLE
Delete some count of rows from csv file

### ISSUE THREAD

**Issue by shubaivan** [thephpleague/csv#387]
Example I have csv file with million rows and I created queue for handle rows by handle step 100 rows. And after 100 row wlll be handled I want to remove thouse from this csv file. It's possible ? Or maybe someone know another tools or way hoow to do that. Would be great if will be exist opportunity remove rows with offset and limit

|    Q        |   A
|------------ | ------
| Version     | 9.5

### Question

Could possible delete some count of rows from csv file, just remove or replace to empty ?

**Comment by nyamsprod** [comment]
@shubaivan thanks for using the library. I'm sorry but I fail to understand your question. Could you provide better information if you want your issue to be tackle.

**Comment by shubaivan** [comment]
@nyamsprod thank you for great library. When I described it I mean - some approach for remove row from csv after row was handled like this

```
        $csv = Reader::createFromPath($filePath, 'r');

        //build a statement
        $stmt = (new Statement())
            ->offset($offset)
            ->limit($limit);

        //query your records from the document
        $records = $stmt->process($csv);

        foreach ($records as $offsetRecord=>$record) {
            $this->handleProductJobInQueue(
                $record
            );
     
            // and after this needed remove row from csv file. This is possible?
        }
```

**Comment by nyamsprod** [comment]
@shubaivan While there are several ways to resolve your issue you need to keep in mind that the CSV package is based on streaming so you can either read from a CSV document or write from it you can not read and write which is what you are asking. Also remember that in your examples the `$records` in a ResultSet object *not* a Reader object 😉  .
