### ISSUE TITLE
Statement with where clause

### ISSUE THREAD

**Issue by pawventure** [thephpleague/csv#389]
|    Q        |   A
|------------ | ------
| Version     | 9.6

### Question

Hi,
I'm exploring/learning your CSV data manipulation. 
I'm trying to get data with a where condition.
I'm thinking if it is doable in your statement if I do something like this? 
I want to get all data row in CSV where there is an IF in column 3. 
Or can you suggest something using your package how to achieve this?

$stmt = (new Statement())
    ->offset(10)
    ->limit(25)
   -> where('Column3' == 'IF')

Thanks in advance.
Great work by the way.

**Comment by nyamsprod** [comment]
[as described in the documentation](https://csv.thephpleague.com/9.0/reader/statement/#filtering-constraint) the `where` clause expect a closure. You may use the [csv-doctrine-bridge](https://github.com/bakame-php/csv-doctrine-collections-bridge) you add your expected behaviour.
