### ISSUE TITLE
does `createFromString` handle a very big csv file?

### ISSUE THREAD

**Issue by michaelnguyen547** [thephpleague/csv#390]
_(Fill in the relevant information below to help triage your issue.)_

|    Q        |   A
|------------ | ------
| Version     | 9.6.0

### Question

I want to read csv file hosted on S3. It works fine with `createFromString` (https://github.com/thephpleague/csv/issues/306). However, I wonder if `createFromString` can handle a very big csv file.

Is it smart enough to read line by line instead of dumping everything?

**Comment by nyamsprod** [comment]
@michaelnguyen547 thanks for using the library. Did you try your solution before asking ? I don't use S3 so I can not answer a question I never faced before even though I have an idea on how it will behave you better test it for yourself IMHO. If it fails or behave not according to what the documentation state then please don't hesitate to open an issue or a pull request if you succeed in fixing the found issue.
