### ISSUE TITLE
Closing file handles

### ISSUE THREAD

**Issue by Schyzophrenic** [thephpleague/csv#391]
|    Q        |   A
|------------ | ------
| Version     | 9.6.0

### Question

I use the library to perform numerous read/write operations on batch mode. Everything works fine but it is a if I have a memory leak in the batch as the program gets slower and slower and eventually runs out of Memory when trying to send the final confirmation email. 
At this point, I am not sure (and don't think) there is an issue with the library itself but was wondering if I need to close the file handles. I couldn't find anything related to that in the documentation and wonder whether this would be the source of my leak. 

Thank you for the help

**Comment by nyamsprod** [comment]
@Schyzophrenic thanks for using the library. As I have no idea how you are using the library I can not be of any help. If you use the library as described in the documentation you should not run into any memory leaks. But If your are still, and it is coming from the library, you should try to extract the leaking part and improve your issue reporting so it can be tackle here otherwise you should close this issue.

**Comment by Schyzophrenic** [comment]
Hi @nyamsprod . I reckon this is not a lot to work on. If I had to summarize my question, it would be: "Do I need to close the file handles?" 
In the doc, we perform fopen (done inside the Writer::createFromPath for instance) but we never perform fclose hence my question. Do we just rely on the garbage collector to close the file handle? 

I tried to provide some context around why I asked the question but it may have made things more confusing, my apologies for that.

**Comment by nyamsprod** [comment]
@Schyzophrenic in that case the answer is easily found in the package codebase 😉 

https://github.com/thephpleague/csv/blob/master/src/Stream.php#L186-L203
and
https://github.com/thephpleague/csv/blob/master/src/Stream.php#L143-L156

this should answer your question

**Comment by Schyzophrenic** [comment]
I forgot to check the __destruct function, sorry about that and thank you for the time spent answering!
