### ISSUE TITLE
Need setEnclosure(""); whithout  space

### ISSUE THREAD

**Issue by ruevers** [thephpleague/csv#392]
_(Need setEnclosure(""); whithout  space)_

|    Q        |   A
|------------ | ------
| Version     | 8.1

### Question

Need setEnclosure(""); whithout  space in laravel

if as set 
   $csv->setEnclosure("");

Get the error

InvalidArgumentException
The enclosure must be a single character

    public function setEnclosure($enclosure)
    {
        if (!$this->isValidCsvControls($enclosure)) {
            throw new InvalidArgumentException('The enclosure must be a single character');
        }
        $this->enclosure = $enclosure;
 
        return $this;
    }

The source data is 

Matic Network

if I not set enclosuere he show like this 

|"Matic Network"|

and I need just this

|Matic Network|

and if I set  setEnclosure("") get errors if i not set it puts the " by defalt

**Comment by nyamsprod** [comment]
@ruevers please refer to the pinned issue as this has already been discussed
