### ISSUE TITLE
empty first record is not skipped if it contains a BOM sequence

### ISSUE THREAD

**Issue by dariusheivazi** [thephpleague/csv#394]
> @dariusheivazi I'm guilty of naming stuff poorly 😉 `Reader::skipEmptyRecords` is the default. So records deemed empty are already removed.
> 
> In you case I think the first line is technically not empty so the only way to remove it is to filter it out using the `Statement` object. At least that's what I understood from your explanation.

The library does not skip empty records as it is promised in documentation: **By default the CSV document normalization removes empty records**. 
I investigated the flow. The problem comes from the normalizing function. If the first record is empty, it does not skip that. In Issue 393 I tried to explaine it. Technically first line may contain BOM, so the normalizing funtion does not find it as **null**. The resolution is: makethe normalizing funtion a little bit more smart. That may be done by changing the Line 256 of file Reader.php:
FROM
`return is_array($record) && ($this->is_empty_records_included || $record != [null]);
`
TO:
`return is_array($record) && ($this->is_empty_records_included || ($record != [null] && $record != [$this->input_bom]));`

and It should work, of course if this does not cuase BC break. Anyway. Thanks for this great library. I hope you see this comment.

_Originally posted by @dariusheivazi in https://github.com/thephpleague/csv/issues/393#issuecomment-681943689_

**Comment by nyamsprod** [comment]
@dariusheivazi a PR has been created with the bug fix could you test the branch to see if it behave as expected.

**Comment by dariusheivazi** [comment]
> @dariusheivazi a PR has been created with the bug fix could you test the branch to see if it behave as expected.

@nyamsprod, Hi, The PR works like a charm. I tested it, and it works perfectly (at least for my case). Thanks a lot.

**Comment by nyamsprod** [comment]
Bug fix merged to master
