### ISSUE TITLE
When I try to read from stream - stream does not support seeking

### ISSUE THREAD

**Issue by shubaivan** [thephpleague/csv#397]
### Bug Report

My way, I download csv files from some resource by Guzzle, use for that stream option, then I use stream way for saving this files to digital ocean space, and the another script, consumer get this job for handle data inside the file, by each row. And I gaced with error `stream does not support seeking` 
| Information | Description |
|--------------|---------|
| Version | "^9.5" |
| PHP version |  7.4.10|
| OS Platform | alpine:edge  |

#### Summary

when executed `process` I faced with - `stream does not support seeking`

#### Standalone code, or other way to reproduce the problem

for save and read file by stream way I use 

```
"league/flysystem-bundle": "dev-master"
        "keven/flysystem-concatenate": "dev-master",
```

save part ($phpStream - stream from guzzle ), with save part everythng ok, wihout error

```
        $this->do->getStorage()
            ->writeStream($doPath, $phpStream);
```

then another consumer for read part

            $readStream = $this->do->getStorage()->readStream($filePath);

            /** @var Reader $csv */
            $csv = Reader::createFromStream($readStream);
            $csv->setHeaderOffset(0);
            $csv->setDelimiter(';');

            //build a statement
            $stmt = (new Statement())
                ->offset(1)
                ->limit(10);

            //query your records from the document
            $records = $stmt->process($csv);

            foreach ($records as $offsetRecord => $record) {
                $t = 1;
            }

I was deep inside and found point where exactly problem 
when created `Stream` class in construnctor

\League\Csv\Stream::__construct

set property 

        $this->is_seekable = stream_get_meta_data($stream)['seekable'];

and my stream answered

```
result = {array} [11]
 crypto = {array} [4]
 timed_out = false
 blocked = true
 eof = false
 wrapper_data = {array} [12]
 wrapper_type = "http"
 stream_type = "tcp_socket/ssl"
 mode = "r"
 unread_bytes = {int} 7715
 seekable = false
 uri = "https://minimoj-consumer.ams3.digitaloceanspaces.com/minimoj-consumer/minimoj/download_files/adrecord/gus_textil/20200909163429.csv"
```

and then in `\League\Csv\Stream::rewind`

this properrty cheked and thrown exception if it was false

```
    public function rewind()
    {
        if (!$this->is_seekable) {
            throw new Exception('stream does not support seeking');
        }
```

How to correct use stream ? And with what bundle problem, csv or flysystem or with digital ocean space storage ? 

#### Expected result

I should get scv rows with limit and offset from csv file

#### Actual result

thrown exception about `stream does not support seeking`

**Comment by nyamsprod** [comment]
@shubaivan thanks for the detailed report but I'm afraid there's nothing I can do to help you. The exception you get does indicate the issue. The stream your are feeding the library is not **seekable**. 
The solution is to see how to make ther stream from your third party provider streamable. I'm afraid this is out of scope for the issue list as you are faced with a documented limitation from the library. 
Sorry I can not be of more help

**Comment by shubaivan** [comment]
@nyamsprod but third library this is [flysystem-bundle](https://github.com/thephpleague/flysystem-bundle) products from the same company `thephpleague`. I got this stream from `flysystem-bundle` 

```
flysystem:
  storages:
    reaources.storage:
      adapter: 'aws'
      options:
        client: 'Aws\S3\S3Client' # The service ID of the Aws\S3\S3Client instance
        bucket: 'minimoj-consumer'
        prefix: 'minimoj'

services:
  Aws\S3\S3Client:
    arguments:
      - endpoint: '%env(S3_END_POINT)%'
        version: 'latest'
        region: 'ams3'
        use_path_style_endpoint: true
        credentials:
          key: '%env(S3_STORAGE_KEY)%'
          secret: '%env(S3_STORAGE_SECRET)%'
```

then 

```
use Keven\Flysystem\Concatenate\Append;
use Keven\Flysystem\Concatenate\Concatenate;
use League\Flysystem\FilesystemInterface;
use League\Flysystem\Util;

class DigitalOceanStorage
{
    private $storage;

    // The variable name $defaultStorage matters: it needs to be the camelized version
    // of the name of your storage.
    public function __construct(FilesystemInterface $reaourcesStorage)
    {
        $reaourcesStorage->addPlugin(new Append());
        $this->storage = $reaourcesStorage;
    }

    /**
     * @return FilesystemInterface
     */
    public function getStorage(): FilesystemInterface
    {
        return $this->storage;
    }
```


and in my service

```
    /**
     * @var DigitalOceanStorage
     */
    private $do;


           .....


            $readStream = $this->do->getStorage()->readStream($filePath);

```

and this is stream not seekable

```
result = {array} [11]
 crypto = {array} [4]
 timed_out = false
 blocked = true
 eof = false
 wrapper_data = {array} [12]
 wrapper_type = "http"
 stream_type = "tcp_socket/ssl"
 mode = "r"
 unread_bytes = {int} 7715
 seekable = false
 uri = "https://minimoj-consumer.ams3.digitaloceanspaces.com/minimoj-consumer/minimoj/download_files/adrecord/gus_textil/20200909163429.csv"
```

rom what this is dependencies, rom digital ocean space ?

**Comment by nyamsprod** [comment]
@shubaivan the php league **is not a company**. Your issue has nothing to do with the CSV package and If you believe that the issue comes from the flysystem-bundle then the best course of action is to fill your issue on that package issue tracker. Since I don't use/know how works this bundle I'm afraid I can not be of much help.

**Comment by quevlu** [comment]
@shubaivan I could solve this problem in this thread https://github.com/thephpleague/csv/issues/222. You can see my solution and if you need help please contact me
