### ISSUE TITLE
How to get all records as an array without iterating in a foreach loop?

### ISSUE THREAD

**Issue by MND13** [thephpleague/csv#398]
|    Q        |   A
|------------ | ------
| Version     | ^9.6

### Question
How to get all records as an array without iterating in a foreach loop?
I dont want to do something like this
`
$reader = Reader::createFromPath('/path/to/my/file.csv', 'r');
$records = Statement::create()->process($reader);

foreach ($records as $record) {
    $data[] = $record;
}

return $data
`

I am trying to chunk a large file by using the offset and limit functions, and return it to vue.
.. see code.

`$reader = Reader::createFromPath(public_path('/files/imported/'.$request->filename.'.csv'), 'r')->setHeaderOffset(0) ;
        $records = Statement::create()->process($reader);
        $count = count($records);
        $partition = 1;
        $limit = 0;

        if( $count >= 3000 )
        {
            $x = 1 . str_repeat("0", strlen($count)-1);
            $partition = $count/$x;
            $limit = $count/$partition;
        }

      
        $data = array();

        for( $pacer = 0 ; $pacer <= $partition ;  $pacer++)
        {
            $stmt = $pacer == 0 ? (new Statement())->limit($limit) : (new Statement())->offset( sizeof($recs) )->limit($limit);

            $recs = array();
            $recs = $stmt->process($reader);
            
            //WHAT I WANT
          $data[$pacer] = $recs->getRecords() ;
            

           /* TAKES TOO LONG
             foreach ($recs as $rec) {
               $data[$pacer][] = $rec;
            }*/
        }
     
        return $this->safe_json_encode([
            'filename' =>$request->filename,
            'count' => $count,
            'partitions' => $partition,
            'limit' => $limit,
            'data' => $data,
        ]);`

**Comment by nyamsprod** [comment]
@MND13 thanks for using the library. I must point out that you can get that answer from the documentation website where all return type of the public API are given/explain. Just search the PHP documentation for how to convert an iterator to an array.
