### ISSUE TITLE
Server error inside CSV file when using Laravel response

### ISSUE THREAD

**Issue by rbruhn** [thephpleague/csv#399]
Laravel 7
Version   9.6

### Question

When using a Laravel download response, I'm receiving an error inside the CSV file. It shows up below the last row in the CSV file. If I don't use the Laravel response and simply echo `$reader->output($fileName)` then die, it works. So it's definitely related to the download response.

 I'm wondering if you have encountered this before and if there is a solution for it. Other downloads I use for TAR files work fine.

Laravel code:
```php
$filePath = Storage::path(config('config.rapid_export_dir') . '/' . $fileName);
$reader = Reader::createFromPath($filePath, 'r');
$reader->setOutputBOM(Reader::BOM_UTF8);

$headers = [
    'Content-Encoding' => 'none',
    'Content-Type' => 'text/csv; charset=UTF-8',
    'Content-Disposition' => 'attachment; filename="'.$fileName.'"',
    'Content-Description' => 'File Transfer',
];

return Response::download($reader->output($fileName), $fileName, $headers);
```

Error code:
```html

<!DOCTYPE html>
--
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width
 
<title>Server Error</title>
 
<!-- Fonts -->
<link rel="dns-prefetch"   href="//fonts.gstatic.com">
<link   href="https://fonts.googleapis.com/css?family=Nunito"   rel="stylesheet">
 
<!-- Styles -->
<style>
html
background-color: #fff;
color: #636b6f;
font-family: 'Nunito'
font-weight: 100;
height: 100vh;
margin: 0;
}
 
.full-height {
height: 100vh;
}
 
.flex-center {
align-items: center;
display: flex;
justify-content: center;
}
 
.position-ref {
position: relative;
}
 
.code {
border-right: 2px solid;
font-size: 26px;
padding: 0 15px 0 15px;
text-align: center;
}
 
.message {
font-size: 18px;
text-align: center;
}
</style>
</head>
<body>
<div class="flex-center position-ref full-height">
<div   class="code">
500            </div>
 
<div class="message"   style="padding: 10px;">
Server Error            </div>
</div>
</body>
</html>
```

**Comment by nyamsprod** [comment]
@rbruhn thanks for using the library. I believe your question is answered in the library documentation website.

**Comment by rbruhn** [comment]
If it does, then I can't find it. I've tried all the various examples. Thanks anyway. I will just switch packages.

**Comment by nyamsprod** [comment]
Did you read this section https://csv.thephpleague.com/9.0/connections/output/#using-a-response-object-symfony-laravel-psr-7-etc ?

**Comment by rbruhn** [comment]
Yes. With and without adding the `$reader->setOutputBOM(Reader::BOM_UTF8);`
Also tried `$reader->getContent()` in place of the `$reader->output()` shown in the code above.
When using getContent(), I got a 500 error when going to the download url. My error log simply said there was an error and spit out the 85K rows of the csv with 4 or 5 letters tagged at the beginning of the error. I don't have that log anymore or I'd show you the start of it. There was no trace for the error. No real message to figure out what went wrong.

**Comment by nyamsprod** [comment]
from what you describe to me it's clearly an issue with Symfony or Laravel way of constructing the HTTP response rather that one with the library I'm afraid. 😢

**Comment by rbruhn** [comment]
Ya, that's what I thought. Which is why I was simply asking if you've ran into the issue or not. Thanks for responding further though.

**Comment by nyamsprod** [comment]
@rbruhn I think you'll find the solution to your issue by reading the Laravel documentation https://laravel.com/docs/8.x/responses#file-downloads  ... your first snippet is incorrect you should correct it. And as I said this has nothing to do with the library 😉

**Comment by rbruhn** [comment]
Tried directly downloading the file. The problem was the file ended up with utf-8 characters scrambled inside the csv no matter what settings I had in the headers. When viewing the file saved on the server, the utf-8 characters are correct. So it's happening during the download. I was trying to use your methods to help with the download to get correct character encoding using BOM.

So, your library works for the file if I just send headers and die. It won't work at all using Laravel download.

**Comment by rbruhn** [comment]
Thought I would let you know I figured this out. The main problem was my file name in the url. It didn't like that so I changed it to be encoded. After fixing that, the Laravel download response still didn't give correct utf8 characters. However, using your example from the documentation finally worked. So it was the filename issue in the URL that caused all the issues. Code below works. Thanks.

```php
$filePath = Storage::path(config('config.rapid_export_dir') . '/' . $fileName);
$reader = Reader::createFromPath($filePath, 'r');
$reader->setOutputBOM(Reader::BOM_UTF8);

$headers = [
    'Content-Encoding' => 'none',
    'Content-Type' => 'text/csv; charset=UTF-8',
    'Content-Description' => 'File Transfer',
    'Content-Disposition' => 'attachment; filename="'.$fileName.'"'
];

return response($reader->getContent(), 200, $headers);
```
