### ISSUE TITLE
Encoding wrong?

### ISSUE THREAD

**Issue by jonyking** [thephpleague/csv#402]
Version: 9.0

Questions:
I created a new csv from a wordpress database. And I got on the end some weird characters. Database, database connection and php-file is utf-8.
The characters are not from the database.

Code:

```
 /*$encoder = (new CharsetConverter())
                ->inputEncoding('utf-8')
                ->outputEncoding('utf-8')
            ;*/

$filename = 'report-' . time() . '.csv';
            $writer = Writer::createFromPath($AGR_SKYTS_PLUGIN_PATH .'/generated-csv/'. $filename, 'w+');
            //$writer->addFormatter($encoder);
            $writer->insertOne($header);
            $writer->insertAll($records);
```
<img width="695" alt="Bildschirmfoto 2020-11-26 um 10 18 49" src="https://user-images.githubusercontent.com/24831213/100348059-a4468280-2fe6-11eb-9e31-b7fa932786ec.png">

**Comment by nyamsprod** [comment]
@jonyking thanks for using the library. The only thing I can say is that those additional characters are not being added by the library you should either verify your, script, your converter and/or your database connections. That's all I can say with the information given, you could also ask on a forum as this is clearly not an issue on the library itself.
