### ISSUE TITLE
PHP 8.0: league/csv 9.6.1 requires php ^7.2.5 -> your PHP version (8.0.0) does not satisfy that requirement.

### ISSUE THREAD

**Issue by ZaneCEO** [thephpleague/csv#403]
As per title. Could you please update it?

**Comment by nyamsprod** [comment]
@ZaneCEO a PR will be welcomed with the changes you require. Thanks

**Comment by ZaneCEO** [comment]
Gladly! I'll give it a shot later today, thanks!

**Comment by nyamsprod** [comment]
@ZaneCEO for what is worth the master already supports PHP8 but the code static analysis still needs some love 😉

**Comment by ZaneCEO** [comment]
Hey! I just cloned the repo and I [found exactly the change](https://github.com/thephpleague/csv/commit/9f24cf4e136805e41e15394b85850c298bffec9e) I was going to make :-D

So... that's all for now, thanks!
