### ISSUE TITLE
New Tag for PHP 8.0 ?

### ISSUE THREAD

**Issue by KangAdmin** [thephpleague/csv#404]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | yes/no

#### Proposal

Hello,
It seems you make some change in Master branch to make it compatible with PHP 8.0, but no new tag
Could you create a new tag to get it, if modification are finish !
Thank you !

**Comment by nyamsprod** [comment]
@KangAdmin indeed the modification are not finished as you can see the test suite is broken. But feel free to finish them any help is welcomed and will be credited in the changelog. 👍

**Comment by iquito** [comment]
Can a version 9.6.2 be released with the new PHP version constraint at least? Currently, if you try to use `leage/csv` with PHP8, it downgrades from 9.6.1 to 9.5.0. Even if this library has problems with PHP8, a downgrade to a previous version is even worse, and the new minimum version constraint PHP>=7.2.5 is an improvement over PHP^7.2 in general. No new major version is needed to at least enable an install without downgrade with PHP8.
