### ISSUE TITLE
Info class is missing in release

### ISSUE THREAD

**Issue by alpham8** [thephpleague/csv#409]
### Bug Report

The `Info` class in src folder is missing in the current release.

| Information | Description |
|--------------|---------|
| Version | 9.6.2 |
| PHP version | 7.4.13 |
| OS Platform | Ubuntu 18.04 |

#### Summary

If you look here, the class is documentated: https://csv.thephpleague.com/9.0/connections/controls/#detecting-the-delimiter-character

But if you look into the release, the class is missing: https://github.com/thephpleague/csv/tree/9.6.2/src

**Comment by nyamsprod** [comment]
@alpham8 indeed because the doc is up to date with the master branch not with release tag. The Info class will be available with the next release. I usually add the documentation before release otherwise the documentation is no longer up to date

**Comment by alpham8** [comment]
I added the static method to my code and it works. A hint: You may want to add `arsort` a the end to sort descending the score.

PS: On docs page the version switcher is broken.

**Comment by nyamsprod** [comment]
`arsort` at the end of what method ? 🤔

**Comment by alpham8** [comment]
Hi @nyamsprod first of all, sorry for the late reply - I forgot to answer you.

I meant, that `arsort` should be placed here: https://github.com/thephpleague/csv/blob/master/src/Info.php#L101

**Comment by nyamsprod** [comment]
`arsort` should not be used because how do you decide in case at least 2 delimiters have the same stats or the correct one has less... this should be a business decision, the method/function should not choose for you it only gives hints. In your case, it may be the correct solution. But it's not 100% bulletproof.

**Comment by alpham8** [comment]
Sure, that's always bussiness logic stuff outside of that class. But if some delimiters are exactly equal, that doesn't harm the sorting itself. So, with that in mind it's indeed universal bullet-proof

**Comment by nyamsprod** [comment]
also if you don't use `asort` the returned array gets the same order asa your input array. In any case I do not see it as a deal breaker.
