### ISSUE TITLE
Incorrect code example toString method not exists

### ISSUE THREAD

**Issue by fey** [thephpleague/csv#417]
## Bug Report

_(Fill in the relevant information below to help triage your issue.)_

| Information | Description |
|--------------|---------|
| Version | 9.6.2 |
| PHP version | 7.4  |
| OS Platform | OSX 10.14.5 |

### Summary

https://csv.thephpleague.com/
Uncaught Error: Call to undefined method League\Csv\Reader::toString()

### Standalone code, or other way to reproduce the problem

Put example code to editor
```php
<?php

// ...
echo $csv->toString(); //returns the CSV document as a string
```

### Expected result

Method exists.
CSV content will be outputed.

### Actual result

Got excepiton
Uncaught Error: Call to undefined method League\Csv\Reader::toString()

## Checks before submitting

* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/thephpleague/csv/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/thephpleague/csv/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

**Comment by nyamsprod** [comment]
Indeed `toString` will be available as soon as `9.7.0` is released... when I have time.

**Comment by fey** [comment]
Yes, think doc should be updated with new release. But now doc has some mistakes.
Propose change to simple `echo (string)$csv` because it has magic method `__toString()`

**Comment by nyamsprod** [comment]
The documentation contains no mistakes it is clearly stated that the feature will be introduced in `9.7.0` which is the case.

**Comment by fey** [comment]
Yeah, this warning is here https://csv.thephpleague.com/9.0/connections/output/#using-the-tostring-method

what do you think about adding this info to main page https://csv.thephpleague.com/ ?

**Comment by nyamsprod** [comment]
@fey the best solution would rather be to release `9.7.0` which I should be done this weekend 🤞🏾

**Comment by nyamsprod** [comment]
version 9.7.0 is releases
