### ISSUE TITLE
Add count() wrapper method

### ISSUE THREAD

**Issue by dereuromark** [thephpleague/csv#42]
When using the offset/limit for pagination, it would be useful if the library had a count() method to quickly determine the total rows without having to fetchAll() including the data memory overhead it comes with.

**Comment by NoMan2000** [comment]
Here's how I did it in a class, this gets both the columns and the rows, and makes sure that the rows are filled.  I've found that both CSV and XLS files will mark a row filled if it once had data and it's quick deleted.  Passing count in by reference, you can see the difference between the rows that are marked as existing but have no values stored in the first element, (or however you wish to pass this.)

    protected function countRows($reader)
    {
        $count = 0;
        $countRows = $reader->each(function ($rows) use (&$count) {
            $count++;
            $this->columns = count($rows);
            if (!empty($rows[0])) {
                return true;
            }
            if (empty($rows[0])) {
                return false;
            }
        });
        unset($count);
        return $countRows;
     }

**Comment by motin** [comment]
Here is a sample benchmark: Counting the rows in a 8,8mb csv file with 52401 rows took 3.29s when running on a recent Macbook Pro.

**Comment by nyamsprod** [comment]
@dereuromark @motin adding the `Countable` Interface is a WIP in the next major release you can  have more information with PR #178 and [the proposed API for v9](https://gist.github.com/nyamsprod/b9fac96126a40185bff48b0c3c5c4529)

**Comment by alexjose** [comment]
+1

**Comment by nyamsprod** [comment]
the Countable interface has been added to the Reader class in the upcoming version 9.0
