### ISSUE TITLE
Force to EncloseField won't remove control characters since v9.7

### ISSUE THREAD

**Issue by patriziotomato** [thephpleague/csv#422]
## Bug Report

_(Fill in the relevant information below to help triage your issue.)_

| Information | Description |
|--------------|---------|
| Version | v9.7.0 |
| PHP version | v7.4  |
| OS Platform | Ubuntu 20.04 |

### Summary

Forcing enclosures will not remove the "magic character"

### Standalone code, or other way to reproduce the problem

Using the example leads to a CSV that still contains the control characters

```php
$records = [
        ['Year', 'Make', 'Model', 'Description', 'Price'],
        [1997, 'Ford', 'E350', 'ac,abs,moon', '3000.00'],
        [1999, 'Chevy', 'Venture "Extended Edition"', null, '4900.00'],
        [1999, 'Chevy', 'Venture "Extended Edition, Very Large"', null, '5000.00'],
        [1996, 'Jeep', 'Grand Cherokee', 'MUST SELL!
        air, moon roof, loaded', '4799.00'],
    ];

    $writer = Writer::createFromPath(__DIR__.'/../storage/app/test.csv', 'w+');
    $writer->setDelimiter('|');
    EncloseField::addTo($writer, "\t\x1f");
    $writer->insertAll($records);
```

### Expected result

```
"Year"|"Make"|"Model"|"Description"|"Price"
"1997"|"Ford"|"E350"|"ac,abs,moon"|"3000.00"
"1999"|"Chevy"|"Venture ""Extended Edition"""|""|"4900.00"
"1999"|"Chevy"|"Venture ""Extended Edition, Very Large"""|""|"5000.00"
"1996"|"Jeep"|"Grand Cherokee"|"MUST SELL!
```

### Actual result

```
"	Year"|"	Make"|"	Model"|"	Description"|"	Price"
"	1997"|"	Ford"|"	E350"|"	ac,abs,moon"|"	3000.00"
"	1999"|"	Chevy"|"	Venture ""Extended Edition"""|"	"|"	4900.00"
"	1999"|"	Chevy"|"	Venture ""Extended Edition, Very Large"""|"	"|"	5000.00"
"	1996"|"	Jeep"|"	Grand Cherokee"|"	MUST SELL!
        air, moon roof, loaded"|"	4799.00"

```

## Checks before submitting

* [X] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/thephpleague/csv/issues)
* [X] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/thephpleague/csv/pulls)
* [X] I have added every step to reproduce the bug.
* [X] If possible I added relevant code examples.
* [X] This issue is about 1 bug and nothing more.
* [X] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

**Comment by nyamsprod** [comment]
fixed by #421

**Comment by patriziotomato** [comment]
Any plans when to release this fix?

**Comment by nyamsprod** [comment]
@patriziotomato should be released next week.

**Comment by patriziotomato** [comment]
Thanks so much

**Comment by nyamsprod** [comment]
9.7.1 has been released
