### ISSUE TITLE
[PHP8] Fatal error: Cannot make non static method League\Csv\Modifier\StreamFilter::validateString() static in class League\Csv\AbstractCsv in /home/backend-coding-challenge-sitzplan/vendor/league/csv/src/AbstractCsv.php on line 148

### ISSUE THREAD

**Issue by Oelti** [thephpleague/csv#423]
Hallo folks,

by updating from PHP7 to PHP8 your Plugin CSVLeague8 counter into following issue:
Fatal error: Cannot make non static method League\Csv\Modifier\StreamFilter::validateString() static in class League\Csv\AbstractCsv in /home/backend-coding-challenge-sitzplan/vendor/league/csv/src/AbstractCsv.php on line 148

The problem is that the Trait StreamFilter.php Line 218 is not declared as static which is used in AbstractCsv.php on line 41 and overwritten as static in line 148. When you declare it as static in the traitthe Fatal error is gone. I don´t know why PHP7 is not seeing it as an error.

Can you fix it as soon as possible?

Thanks
Oelti

**Comment by nyamsprod** [comment]
@Oelti League/CSV 8 is no longer supported please upgrade your code to use the latest stable version of the library.
