### ISSUE TITLE
How to retrieve header with several empty values?

### ISSUE THREAD

**Issue by jotajotaramos** [thephpleague/csv#424]
|    Q        |   A
|------------ | ------
| Version     | 9.7

## Question

Hello:

I am aware that duplicated headers names triggers a an exception . But sometimes I need to read CSVs that have more that one empty columns.

Any workaround in order to be able to get rid of the columns? Or maybe read the file in a way that the library doesn't consider those empty columns?

Here is an example:

| header1 | header2 |   | header3 |   | header4 | header5 |
|---------|---------|---|---------|---|---------|---------|
| value1  | value2  |   | value3  |   | value4  | value5  |

Thanks a lot for your help.

My best regards.

**Comment by nyamsprod** [comment]
While this is not a help forum where you will find more in-depth help. I would point you to use `Reader::getRecords` with its optional argument as stated [in the documentation](https://csv.thephpleague.com/9.0/reader/#csv-records).
