### ISSUE TITLE
How to detect the last iteration when Iterator's valid() method is not defined?

### ISSUE THREAD

**Issue by Synchro** [thephpleague/csv#425]
|    Q        |   A
|------------ | ------
| Version     | 9.7.1

## Question

I'm iterating over the records of a CSV file, but I want to know when I have reached the end *before* the loop actually terminates. In other iterator implementations I've been able to call [the iterator's `valid()` method](https://www.php.net/manual/en/iterator.valid.php), and it will be false for the last iteration, but that doesn't seem to be available here, even though [the docs](https://csv.thephpleague.com/9.0/reader/#using-the-iteratoraggregate-interface) say I should be able to get at an Iterator interface through the Reader instance. I can see in the code there is a reference to [something that looks like it's the right thing](https://github.com/thephpleague/csv/blob/d5de5a3d57564ef21bb469bf126229925b78c7b2/src/AbstractCsv.php#L312), but I can't see why I can't call it.

My context is this: I am importing large CSV files into a database, and I want to do database inserts in chunks, so I read each CSV row and assemble a query containing many rows, then every so often (say 500 rows), I submit the query to the DB and the chunk is inserted. This is much more efficient that inserting each row individually. So there are two occasions I need to trigger an insert: I've either reached the end of a chunk, or I've reached the end of the file. So I need to check if I've reached the end of the file each time round the loop. My old code (using a different iterator) was something like this:

```php
$csv = new csvthing();
foreach ($csv as $record) {
    //Do stuff
    $data[] = $record;
    if (count($data) == 500 || !$csv->valid()) {
        $this->db->sql_execute($data...
        $data = [];
    }
}
```

However, when I try to do the same thing with this package, `valid()` is not available, so it dies. How should I detect the last iteration of a foreach loop from within the loop if not like this?

## Checks before submitting

* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/thephpleague/csv/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/thephpleague/csv/pulls)
* [x] I have read, search and not found the information on the [documentation website](https://csv.thephpleague.com).
* [x] I have read, search and not found the information on PHP related forums and/or websites.
* [x] This issue is about 1 question around the package with no business or domain specific logic related to a specific situation.
* [x] The question has a descriptive title. For example:  "Can I use the library with compressed CSV documents ?".

**Comment by nyamsprod** [comment]
@Synchro thanks for using this library.

The `Reader` class implements the `IteratorAggregate` interface not the `Iterator` interface please refer to PHP documentation to see how to do what you expect. Also I don't really think you need the `valid` method just insert the remaining records outside the `foreach` construct IMHO.

**Comment by Synchro** [comment]
I can get to the `valid()` method on the internal `Iterator` instance with `$csv->getIterator()->valid()`, however, it always returns false so it's no use. Is there any other way to detect that you're at the end of the file?

Inserting remaining records outside the loop is a really inelegant approach that requires duplicating code, plus the clunky old CSV iterator I'm trying to move away from doesn't require it!

**Comment by nyamsprod** [comment]
Understood but this is out of scope for the package if you need more info or help you may ask on a php help forum for better alternative. Last but not least I would not rely on `$csv->getIterator()->valid()` as the `valid` method is not part of the `IteratorAggregate` interface.
