### ISSUE TITLE
Select multiple columns

### ISSUE THREAD

**Issue by irzafaikar** [thephpleague/csv#426]
Is there any way to read only spesific column and ignore others?
I have read the documentation for single column in https://csv.thephpleague.com/9.0/reader/resultset/#selecting-a-single-column
But I didn't find a way to select multiple column.
Please help me..

**Comment by nyamsprod** [comment]
@irzafaikar unfortunately this is not a help forum and as far as selecting multiple columns this is already covered in the Reader and ResultSet sections of the documentation website

**Comment by GreenImp** [comment]
I can't see anything about selecting multiple columns in the documentation.
The [`ResultSet` docs](https://csv.thephpleague.com/9.0/reader/resultset) explains how to retrieve a single column (As mentioned in the OP), or selecting [key-value pairs](https://csv.thephpleague.com/9.0/reader/resultset/#selecting-key-value-pairs).

Ideally, I'd like a method where I can specify a list of column indexes to fetch. e,g,:

```php
// with numeric indexes
$records->fetchColumns([1, 4, 5]);
// or with names
$records->fetchColumns(['foo', bar', 'baz']);
```

And it would return all the rows, with only those columns, excluding any others. Is this possible?

**Comment by nyamsprod** [comment]
@GreenImp the library allows you to loop over the resultSet and its signature, an Iterator, allows you any kind of filtering your business requirements needs. So while I understand your need for more syntactic sugar methods, the current API already provides you the necessary tools to fullfil your business requirements without having to add/maintain yet another specific solution for a specific need which is already covered in PHP language and/or in more specialized packages/libraries. In other words if you already have a library that can do it and handles traversable you can reuse that library with League/csc

**Comment by nyamsprod** [comment]
@irzafaikar a `Reader::select` and `ResultSet::select` method will land on version `9.12.0` enable selecting specific column. The method is already documented on [the documentation website](https://csv.thephpleague.com/9.0/reader/tabular-data-reader/#select).
