### ISSUE TITLE
Explanation for field enclosure?

### ISSUE THREAD

**Issue by mkoske** [thephpleague/csv#427]
Hello!

Can you explain to me what field enclosure does? It seems it requires some characters like \t\x1f but I don't know what this means.

I have the library working on my project, but I just wanted to know what this actually does.

Br,
Miika

**Comment by nyamsprod** [comment]
@mkoske thanks for using the library if you want to know about csv options please refer to PHP documentation manual 

- https://www.php.net/fputcsv
- https://www.php.net/fgetcsv

there you will have all the information you need.
