### ISSUE TITLE
MD5 checksum

### ISSUE THREAD

**Issue by davidvandertuijn** [thephpleague/csv#429]
Is it possible to create a md5 checksum of the CSV data ?

My work arround is to loop through the data, store it in a temporarily Array, and then calculate the md5 hash. But storing the data in an temporarily Array is using a lot of memory.

**Comment by nyamsprod** [comment]
@davidvandertuijn while your question is a lot out of scope for the library I would suggest you look into [PHP hash feature](https://www.php.net/manual/en/ref.hash.php) for more info
