### ISSUE TITLE
$csv->output('users.csv'); Not accept path

### ISSUE THREAD

**Issue by mitmelon** [thephpleague/csv#434]
When using 

$csv = Writer::createFromString();
$csv->insertOne($records);
$csv->output(__DIR__.'/../users.csv');

Error popups below... Why cant it support path?

Fri Aug 13 15:59:01.224064 2021] [php:error] [pid 4580:tid 1716] [client 127.0.0.1:52529] PHP Fatal error:  Uncaught League\\Csv\\InvalidArgument: The filename `C:\\xampp\\htdocs\\project\\src\\Register/../users.csv` cannot contain the "/" and "\\" characters. in vendor\\league\\csv\\src\\InvalidArgument.php:40\nStack trace:\n#0 vendor\\league\\csv\\src\\AbstractCsv.php(392): League\\Csv\\InvalidArgument::dueToInvalidHeaderFilename('C:\\\\xampp\\\\htdocs...')\n#1 vendor\\league\\csv\\src\\AbstractCsv.php(367): League\\Csv\\AbstractCsv->sendHeaders('C:\\\\xampp\\\\htdocs...')\n#2

**Comment by nyamsprod** [comment]
@mitmelon thanks for using the library. As explain by the exception message your `$filename` argument is invalid. You can refer to [the library documentation](https://csv.thephpleague.com/9.0/connections/output/#downloading-the-document) where it is stated:

> starting with version 9.1.0, the output method will throw an Exception if the provided $filename does not comply with [RFC6266](https://tools.ietf.org/html/rfc6266#section-4)

**Comment by mitmelon** [comment]
> @mitmelon thanks for using the library. As explain by the exception message your `$filename` argument is invalid. You can refer to [the library documentation](https://csv.thephpleague.com/9.0/connections/output/#downloading-the-document) where it is stated:
> 
> > starting with version 9.1.0, the output method will throw an Exception if the provided $filename does not comply with [RFC6266](https://tools.ietf.org/html/rfc6266#section-4)

Which means the library does not support locations with path like file/filename.csv because have tried this too and does not work... It can only save files to current directory.

And again it will be good if the library can just write directly inside a file and save the file inside the desired destinations... Instead of forcing it to store files in same director... As the directory might be public and people could access the file...

**Comment by mitmelon** [comment]
> @mitmelon thanks for using the library. As explain by the exception message your `$filename` argument is invalid. You can refer to [the library documentation](https://csv.thephpleague.com/9.0/connections/output/#downloading-the-document) where it is stated:
> 
> > starting with version 9.1.0, the output method will throw an Exception if the provided $filename does not comply with [RFC6266](https://tools.ietf.org/html/rfc6266#section-4)

Which means the library does not support locations with path like file/filename.csv because have tried this too and does not work... It can only save files to current directory.

And again it will be good if the library can just write directly inside a file and save the file inside the desired destinations... Instead of forcing it to store files in same director... As the directory might be public and people could access the file...

**Comment by nyamsprod** [comment]
> Which means the library does not support locations with path like file/filename.csv because have tried this too and does not work... It can only save files to current directory.

No as a matter a fact, I believe you are using the wrong method for your use case. Again if you refer [to examples in the documentation ](https://csv.thephpleague.com/9.0/writer/#inserting-records) You will see that:

- **first** you define the path where you want you CSV document to be saved to the underlying filesystem
- **then** you use the `Writer::insert*` method of your choice

the `::output` method as stated in the documentation (ie see the link in the previous comment) is for downloading your CSV document using the HTTP protocol hence the validation on the filename prior to it being added to the created HTTP response header.

Hopes this clarify your behaviour better.

**Comment by mitmelon** [comment]
> > Which means the library does not support locations with path like file/filename.csv because have tried this too and does not work... It can only save files to current directory.
> 
> No as a matter a fact, I believe you are using the wrong method for your use case. Again if you refer [to examples in the documentation ](https://csv.thephpleague.com/9.0/writer/#inserting-records) You will see that:
> 
> * **first** you define the path where you want you CSV document to be saved to the underlying filesystem
> * **then** you use the `Writer::insert*` method of your choice
> 
> So in your example you should do the following instead:
> 
> ```
> <?php
> use League\Csv\Writer;
> 
> $csv = Writer::createFromPath(__DIR__.'/../users.csv');
> $csv->insertOne($header);
> $csv->insertAll($records); 
> ```
> 
> The `::output` method as stated in the documentation (ie see the link in the previous comment) is for downloading your CSV document using the HTTP protocol hence the validation on the filename prior to it being added to the created HTTP response header.
> 
> Hopes this clarify your behaviour better.

Thank you very much... I was using createFromString(); that's where the issue was...

Thanks for the clearifications...

**Comment by mitmelon** [comment]
I have another issue... When I added first data... It entered... But when adding the decode instead of it to append it to the existing data it keeps overwriting the existing one instead of appending it...

What's the error here...

Am using insertOne();
