### ISSUE TITLE
Bad tag 9.72?

### ISSUE THREAD

**Issue by owsygavin** [thephpleague/csv#439]
## Bug Report

This looks wrong:

![image](https://user-images.githubusercontent.com/69899593/136197211-9bf5f0b5-1eb3-4cbe-90c3-e4dbfb515163.png)

| Information | Description |
|--------------|---------|
| Version | 9.2.7 / 9.72  |
| PHP version | 7 |
| OS Platform | Mac |

### Summary

Looks like you may have accidentally pushed a 9.72 as well as 9.7.2?

### Standalone code, or other way to reproduce the problem

n/a

### Expected result

only 9.7.2 available

### Actual result

9.7.2 and 9.72 both availbalbe, my Composer got terrible confused

## Checks before submitting

* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/thephpleague/csv/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/thephpleague/csv/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

**Comment by nyamsprod** [comment]
@T2L should be gone now for good. Sorry for the inconvenience

**Comment by T2L** [comment]
yeah, but you cannot just remove the tag, as you will break update process for everyone who has already updated to 9.72, as they won't be able to update to any version below 9.72, i.e 9.7.3 or 9.8 

I guess, now you must continue with version 9.72 onwards
