### ISSUE TITLE
Auto numbering in insert 

### ISSUE THREAD

**Issue by shivsingh7150** [thephpleague/csv#449]
hello,

i am want to use auto numbering first cullom on insert new records

Example: if insert: a,b,c

Then: 1,a,b,c (Automatic add 1)

Example 2: a,s,d

Then: 2,a,s,d (Automatic add 2) so on

Please help if possible

Thanks

**Comment by nyamsprod** [comment]
@shivsingh7150 thanks for using the library. Unfortunately this is not a support group but what you are trying to achieve should be best shown to you in a broader context not just with League/CSV. you are trying to format a PHP array and map some value in it. There are many ways to achieve this so I would suggest using a PHP help forums where people with better expertise at explaining things would surely help you 😉
