### ISSUE TITLE
Any way to filter records in csv?

### ISSUE THREAD

**Issue by mpixelz** [thephpleague/csv#454]
Hi,
Sorry if it sounds silly, I have a csv file which have column called status.
i cant seem to find a method where i can filter records with the status of 'Pass' as to filter students who have passed.
can someone please help me?

**Comment by nyamsprod** [comment]
@mpixelz thanks for using the library I will point you to the documentation website where all is explain. 

https://csv.thephpleague.com/9.0/reader/statement/

If you find the explanation intimidating or not that well written you can then head over PHP forums where dedicated users will gladly help you. This venue is more reserved for feature requests and issue tackling.

Hope the link will be of help
