### ISSUE TITLE
Skip row with certain value in field

### ISSUE THREAD

**Issue by tebeso** [thephpleague/csv#455]
Is it somehow possible to skip a row if it contains a certain value in a specific field? I have a huge CSV and it contains a field that is either 0 or 1. Most of the rows have a 0 and i dont need them. Looking to make a performance improvement here as I currently have to go over each row with a foreach and that takes a lot of time to check that value.

**Comment by nyamsprod** [comment]
@tebeso thanks for using the package. Did you read the documentation ? the part about [Statement](https://csv.thephpleague.com/9.0/reader/statement/) it should resolve your issue.
