### ISSUE TITLE
How to remove simple quote

### ISSUE THREAD

**Issue by MaruanBO** [thephpleague/csv#457]
Hi sr. Im trying to validate records inside CSV where are using simple quote `'`

Information | Description
-- | --
League\Csv version | 9.x
PHP/HHVM version | 7.4
OS Platform | Linux

My csv:

```
phone, nombre, sexo
632276881,,h
632276881,,pepe,h
555222222
659764761,'Jose Alberto, Martinez',h
```
Expected result:

```
phone, nombre, sexo
632276881,,h
632276881,,pepe,h
555222222
659764761,"Jose Alberto, Martinez",h
```

This should insert in db (mysql) like: 
![Screenshot at 2022-03-09 12-21-52](https://user-images.githubusercontent.com/49251757/157432066-4bb557a9-10d7-4db4-9d2f-147ab8ba8763.png)

Actually result:

```
phone,nombre,sex
"34632276881","","h"
"34632276881","","pepe"
"34659764761","'Jose Alberto","Martinez'"
```

In mysql: 

![Screenshot at 2022-03-09 12-26-43](https://user-images.githubusercontent.com/49251757/157432807-a73ed70f-eb47-4ad9-8b14-27e553a39efd.png)

|    Whats i tried        |   Works 
|------------ | ------
|   EncloseField::addTo($normalizedWriter, "\t\x1f");   |  No
|   setEnclosure   |  No
| str_replace | No
| preg_replace | No

In code:

```
$finfo = new File($file, true);
 foreach ($records as $offset => $record) {
                $record = $this->normalizeRecord($record); 
if (preg_grep('/\'/', $records)) {
                $hasSimpleQuotes = file_get_contents($finfo);
                $stripQuotes = str_replace(" ' ", "", $hasSimpleQuotes);  // or perhaps preg_replace with a regular expression if your data is complex
                // modificamos el header
                file_put_contents($finfo, $stripQuotes);
            }
}
```

## Question

¿ How to remove simple quote or remplace them with "?

## Checks before submitting

* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/thephpleague/csv/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/thephpleague/csv/pulls)
* [x] I have read, search and not found the information on the [documentation website](https://csv.thephpleague.com).
* [x] I have read, search and not found the information on PHP related forums and/or websites.
* [x] This issue is about 1 question around the package with no business or domain specific logic related to a specific situation.
* [x] The question has a descriptive title. For example:  "Can I use the library with compressed CSV documents ?".

**Comment by nyamsprod** [comment]
@MaruanBO using `setEnclosure` should work, at least it worked for me 🤔 

```php
<?php

$str = <<<CSV
phone, nombre, sexo
632276881,,h
632276881,,pepe,h
555222222
659764761,'Jose Alberto, Martinez',h
CSV;

$csv = Reader::createFromString($str);
$csv->setHeaderOffset(0);
$csv->setEnclosure("'");
foreach ($csv as $record) {
    var_dump($record);
}
```

**Comment by MaruanBO** [comment]
Still return 

```
phone,nombre,sexo
34632276881,,h
34632276881,,pepe
34659764761,"'Jose Alberto",Martinez'
```
I tried setting `$csv->setEnclosure("'"); `. Still not working

I'm using this method to detect enclosure:

```
    /**
     * Detecta y configura el enclosure de los campos.
     *
     * Si no hay enclosure en la cabecera no significa que no lo haya en el resto del archivo.
     * En ese caso usamos el propuesto por el RFC4180.
     *
     * @see https://tools.ietf.org/html/rfc4180
     */
    private function detectEnclosure($csv): void
    {
        $allowedChars = [" ' ", '"'];
        $columnStats = [];
        $lengthStats = [];

        foreach ($allowedChars as $currentChar) {
            $csv->setEnclosure($currentChar);
            $header = $csv->getHeader();
            $columnStats[$currentChar] = count($header);
            $lengthStats[$currentChar] = array_map('strlen', $header);
        }

        if (1 == count(array_unique($columnStats))) {
            // Se ha detectado el mismo número de campos

            $diffs = array_diff(...array_values($lengthStats));
            if (empty($diffs)) {
                // No hay diferencia, escogemos el estándar
                $detectedChar = '"';
            } else {
                // Buscamos el que coincide con el resultado del diff
                foreach ($diffs as $col => $len) {
                    foreach ($lengthStats as $enclosure => $cols) {
                        if ($cols[$col] == $len) {
                            $detectedChar = $enclosure;
                            break;
                        }
                    }
                }
            }
        } else {
            // Si tenemos más de un valor es que algún campo contiene un delimitador correctamente escapado
            // Nos quedamos con el que produce menos número de columnas
            $detectedChar = array_search(min($columnStats), $columnStats);
        }

        $csv->setEnclosure($detectedChar);
    }
```

**Comment by nyamsprod** [comment]
I do not understand what you are trying but like I said if you run the script I provided you should have the expected result without adding any enclosure detection. the `setEnclosure` method is responsible for the escaping you want to achieve. By default in PHP the enclosure character is '"'.  Please refer to the documentation or to the PHP documentation for more infos.

**Comment by MaruanBO** [comment]
> I do not understand what you are trying but like I said if you run the script I provided you should have the expected result without adding any enclosure detection. the `setEnclosure` method is responsible for the escaping you want to achieve. By default in PHP the enclosure character is '"'. Please refer to the documentation or to the PHP documentation for more infos.

Im trying to detect enclosure to change it dynamically.

**Comment by nyamsprod** [comment]
so your issue is on how you detect your closure not on how the package handle closure 🤔 . In any case the library *does* correctly handle closure if you are performing external tests/tasks then it's up to you to handle any unexpected changes. I do not see what as a maintainer I can do.

**Comment by MaruanBO** [comment]
> so your issue is on how you detect your closure not on how the package handle closure thinking . In any case the library _does_ correctly handle closure if you are performing external tests/tasks then it's up to you to handle any unexpected changes. I do not see what as a maintainer I can do.

Maybe it's a good feature to drop ¿?. Automatic detect enclosure, cause if you set "" enclosure and set $csv->setEnclosure(" ' "), leaguecsv does not work good.

**Comment by MaruanBO** [comment]
> But why would you automatically detect the enclosure ? The only person who know the correct enclosure is the person/system which encoded the CSV just like detecting delimiter they are so many things that can go wrong that I would not use or want to have that in a standard package.

Actually i need to detect enclosure dynamically or force (i tried https://csv.thephpleague.com/9.0/interoperability/enclose-field/#force-field-enclosure) to be every time " ' ". I need it cause i will insert this in the mysql table, and if a don't detect enclosure good this'll insert bad column in bad header column
