### ISSUE TITLE
How can i set password for the export file?

### ISSUE THREAD

**Issue by drupalex10** [thephpleague/csv#459]
_(Fill in the relevant information below to help triage your issue.)_

|    Q        |   A
|------------ | ------
| Version     | 0.0.1

## Question

_I would like to set a password for my export file because it contains some sensitive data. Can anyone help me?__
__Many thanks_

## Checks before submitting

* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/thephpleague/csv/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/thephpleague/csv/pulls)
* [x] I have read, search and not found the information on the [documentation website](https://csv.thephpleague.com).
* [x] I have read, search and not found the information on PHP related forums and/or websites.
* [ ] This issue is about 1 question around the package with no business or domain specific logic related to a specific situation.
* [ ] The question has a descriptive title. For example:  "Can I use the library with compressed CSV documents ?".

**Comment by drupalex10** [comment]
I would like to set a password for my export file because it contains some sensitive data. Can anyone help me?
Many thanks

**Comment by nyamsprod** [comment]
@drupalex10 thanks for using the library. Unfortunately your question is out of scope for this library if you want to protect sensitive data there are many techniques and pattern to use and I am no security expert so any advice on a correct implementation from my part would be at best wrong. 
You should contact a security expert for that.
Hope you will resolve your issue.
