### ISSUE TITLE
Statement where method evaluated on every iteration on the returned ResultSet

### ISSUE THREAD

**Issue by abuhamza** [thephpleague/csv#460]
## Bug Report

_When you define a Statement and process it within a reader you get an TabularDataReader. When looping on this TabularDataReader, the where method evaluated on every iteration. This lead to a very slow looping._

| Information | Description |
|--------------|---------|
| Version | 9.8.0 |
| PHP version | 8.0.16 |
| OS Platform | Mac OS 12.3 |

### Summary

_When you define a Statement and process it within a reader you get an TabularDataReader. When looping on this TabularDataReader, the where method evaluated on every iteration. This lead to a very slow looping._

### Standalone code, or other way to reproduce the problem

```
$reader = Reader::createFromPath('file-with-millions-of-rows.csv');
$duplicated = [1, 2, 3, 4, 5];
$stmt = Statement::create()->where(fn ($record) => in_array($record[1], $duplicated));
$duplicatedRecords = $stmt->process($reader); // Here the whole file is evaluated against the statement as expected.

foreach ($duplicatedRecords as $duplicatedRecord) { // Here again, before retrieving each row, the whole file is evaluated against the statement making loop over the resulted TabularDataReader very slow.
                // do something
}
```

### Expected result

The where callable should be checked only one time (within the process method call) not when iterating over the result set.

## Checks before submitting

* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/thephpleague/csv/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/thephpleague/csv/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

**Comment by nyamsprod** [comment]
@abuhamza thanks for using the library what you are describing is not possible filtering happens only once but depending on your query it will happen during the call to `Statement::process` *or* during the iteration of the `ResultSet` object never during both.

**Comment by abuhamza** [comment]
@nyamsprod thank you for your feedback.

Is it possible to specify where the filtering will happens ?

**Comment by nyamsprod** [comment]
Why would you want to configure that I do not see the added value or am I missing something 🤔

**Comment by abuhamza** [comment]
Thank you for your support.
