### ISSUE TITLE
Read from imported file ?

### ISSUE THREAD

**Issue by brandonbeschta** [thephpleague/csv#469]
|    Q        |   A
|------------ | ------
| Version     | 7.2.0

## Question

The Reader's createFromPath function expects a filepath but if I am trying to read an imported file I do not have a path. Wondering how do I read from a imported file (input of type 'file') Do I use createFromString instead?

## Checks before submitting

* [x ] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/thephpleague/csv/issues)
* [ x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/thephpleague/csv/pulls)
* [ x] I have read, search and not found the information on the [documentation website](https://csv.thephpleague.com).
* [ x] I have read, search and not found the information on PHP related forums and/or websites.
* [x ] This issue is about 1 question around the package with no business or domain specific logic related to a specific situation.
* [ x] The question has a descriptive title. For example:  "Can I use the library with compressed CSV documents ?".

**Comment by nyamsprod** [comment]
@brandonbeschta thanks for using the library. What do you mean by import file can't you just use createFromString ?

**Comment by brandonbeschta** [comment]
I have a simple form that uses a input element with the type 'file' and would like to read it's contents. However on second thought yes I could just create a reader from the file contents. Thank you !
