### ISSUE TITLE
Reading and Writing csv files from S3 using streams

### ISSUE THREAD

**Issue by Silva404** [thephpleague/csv#473]
## Question
 I'm currently working with big files so I'm obligated to use streams and I'm trying to use CSV league combined with Flysystem. The files are stored in S3.

I managed to upload a new empty file normally using the following code.
``` php
$storage = $container->get(Filesystem::class); // this is an instance League filesystem, using the S3 Adapter
$fileName = self::FILE_NAME;
$headers = ['email' , 'full name'];
$stream = tmpfile();
$writer = Writer::createFromStream($stream);
$writer->insertOne($headers);
$storage->writeStream($fileName, $stream);      
```

Porem quando tentamos adicionar novo conteudo a esse csv, nada acontece.
When I try to add new content to the file created before, nothing happens, the **writeStream** doesn't seem to update the file and also does not update the stream with the new content.
```php
$storage = $container->get(Filesystem::class);
$filePath = self::FILE_NAME;
$stream = $storage->readStream($filePath);
$writer = Writer::createFromStream($stream);

$newLines = [
            ['mail@mail.com','manjil'],
            ['mail@mail.com','daniel']
];
$writer->insertAll($newLines);
$storage->writeStream($filePath, $stream)
```

Is there something I'm doing wrong? When we use with local file system adapter, it works as expected because the **insertAll** updates the file directly which does not occur in S3.

**Comment by nyamsprod** [comment]
@Silva404 seems to me to be a configuration issue around how you are using Flysystem 🤔 @frankdejonge might shade some lights on this as I am not familiar with how flysystem works 😢

**Comment by nyamsprod** [comment]
@Silva404 after reading your code twice ... I believe your second example is wrong you are trying to write to a reading stream. I believe you should do as you did in your first example. Hence the error that you get. I can confirm that it is a configuration issue on how you setup and use leagye/flysystem and not directly related to league/csv.
