### ISSUE TITLE
导出中文的时候乱码了

### ISSUE THREAD

**Issue by 449134904** [thephpleague/csv#480]
![image](https://user-images.githubusercontent.com/17736664/200527992-20790094-4d9c-43ea-8ab0-c8af73f6e9c5.png)
![image](https://user-images.githubusercontent.com/17736664/200528071-1bf401e2-0c92-4e3e-bf17-3982e0552136.png)
你好w我写入csv中文的时候乱码

**Comment by nyamsprod** [comment]
@449134904 I only speak french or english could you explain in one of those language your issue 🤔

**Comment by 449134904** [comment]
> @449134904 I only speak french or english could you explain in one of those language your issue 🤔

Hello, I wrote the Chinese csv in garbled code

**Comment by nyamsprod** [comment]
Hi I still fail to understand the actual issue

**Comment by 449134904** [comment]
> Hi I still fail to understand the actual issue

The csv is garbled when written into Chinese

**Comment by nyamsprod** [comment]
How is this related to the package ? 
Did you check your input/output for the charset ? 
Does chinese CSV expect UTF8 or UTF16 ? 
Do you get the same issue with PHP native functions ?

It is difficult for me to search without any context. As fas as I know the package is charset independent so if you have more info I will re-open the ticket.
