### ISSUE TITLE
Cannot make non static method League\Csv\Modifier\StreamFilter::validateString() static in class League\Csv\AbstractCsv

### ISSUE THREAD

**Issue by OskarStark** [thephpleague/csv#485]
## Bug Report

| Information | Description |
|--------------|---------|
| Version | 8.2.3 |
| PHP version | 8.2.2 |
| OS Platform | MacOs |

### Summary

I receive the mentioned error when using the following code snippet...

### Standalone code, or other way to reproduce the problem

```php
$csv = Reader::createFromPath($this->filepath, 'r');

foreach ($csv->fetchAll() as $row) {
    dump($row);
}
```

**Comment by OskarStark** [comment]
The following diff for `StreamFilter` fixes this error:
```diff
    /**
     * Sanitize the stream filter name
     *
     * @param string $filter_name the stream filter name
     *
     * @return string
     */
    protected function sanitizeStreamFilter($filter_name)
    {
-        return urldecode($this->validateString($filter_name));
+        return urldecode(self::validateString($filter_name));
    }

    /**
     * @inheritdoc
     */
-    abstract public function validateString($str);
+    abstract public static function validateString($str);
```

**Comment by OskarStark** [comment]
Downgrading to `7.2.0` works also 👍

**Comment by nyamsprod** [comment]
Version 8 and 7 are no longer supported. I am glad you could revert to version 7 but if possible I would suggest upgrading toward version 9.

**Comment by OskarStark** [comment]
Oh, I executed composer require without a version and it installed version 8 🤔 weird

I will upgrade to 9.8, thanks

**Comment by nyamsprod** [comment]
yep should be 

```
composer require league/csv:^9.0
```

I will try to update the documentation. you get a 8.+ release instead because it had no upper restriction in PHP version and I suppose depending on your system it misleads composer. Hence upper restriction were added back.
