### ISSUE TITLE
Can you add function to compare 2 csv files and return diff as json

### ISSUE THREAD

**Issue by ntuanphuc** [thephpleague/csv#493]
## Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | yes/no

### Proposal

Nowadays, working with data become popular with developers. While working I see that we need to sync data from one to other ends, and in current php there is not many good libraries to do this. I believe this could be useful if The Php League can add it as a feature in csv library.

## Checks before submitting

* [ ] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/thephpleague/csv/issues)
* [ ] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/thephpleague/csv/pulls)
* [ ] Tell if you have the option to provide the code for this proposal.
* [ ] This issue is about 1 feature proposal and nothing more.
* [ ] The issue has a descriptive title. For example: "Add JSON render option".

**Comment by nyamsprod** [comment]
@ntuanphuc thanks for using the library.

Unfortunately, what you are asking is out of scope for the current package. 

The are several packages you can found on packagist.org that can perform what you are asking with less maintenance burden from my end.
