### ISSUE TITLE
Is Writer::insertAll() faster than Writer::insertOne() or not?

### ISSUE THREAD

**Issue by gazzoy** [thephpleague/csv#504]
|    Q        |   A
|------------ | ------
| Version     | 9.11.0

## Question

According to the source code, Writer::insertAll() internally calls Writer::insertOne() with loop. 

Therefore, as of I understood, in case we have 10,000 records to write, there are no performance advantages by using Writer::insertAll() with 10,000 records compared to calling Writer::insertOne() 10,000 times. Am I right?

**Comment by nyamsprod** [comment]
@gazzoy thanks for using the library. The short answer is it depends. The correct answer is you need to benchmark it as depending on the Writer settings insertAll can run a bit faster and use less memory. So best answer is to try both strategy and pick the one that suits you best.

**Comment by gazzoy** [comment]
@nyamsprod Thanks for your reply! That makes sense. Will do :)
