### ISSUE TITLE
how to read csv without BOM?

### ISSUE THREAD

**Issue by langziyang** [thephpleague/csv#505]
hi,if i have csv file,but no BOM, how to read it?i tried use documentation way,but not working.can you write simple demo? thanks

**Comment by nyamsprod** [comment]
@langziyang If you do not have a bom then do not worry about it the package will handle the fact that no BOM is defined.

**Comment by langziyang** [comment]
but when i read csv,i got garbled characters

**Comment by nyamsprod** [comment]
Then you need to specify the [CSV encoding charset](https://csv.thephpleague.com/9.0/converter/charset/) as explained in the documentation

**Comment by nyamsprod** [comment]
you have an example on the page overview of the documentation.

```php
use League\Csv\Reader;
use League\Csv\CharsetConverter;

$csv = Reader::createFromPath('/path/to/your/csv/file.csv', 'r');
$csv->setHeaderOffset(0);

$input_bom = $csv->getInputBOM();

if ($input_bom === Reader::BOM_UTF16_LE || $input_bom === Reader::BOM_UTF16_BE) {
    CharsetConverter::addTo($csv, 'utf-16', 'utf-8');
}

foreach ($csv as $record) {
    //all fields from the record are converted into UTF-8 charset
}
```

Of course you will have to adapt the code to follow you own constraints.
