### ISSUE TITLE
Double spaces are created when writing file with empty enclosure.

### ISSUE THREAD

**Issue by stevenmusumeche** [thephpleague/csv#51]
When writing a file with an empty enclosure, the class replaces every space in the data with two spaces.  For example, a pipe delimited file:

```
$fileWriter->setDelimiter("|");
$fileWriter->setEnclosure(" ");
```

exports this to file (noticed the multiple spaces):

`Rapala  -  Pro  Guide  Electric  Fillet  Knife|more  data`

instead of the actual data:

`Rapala - Pro Guide Electric Fillet Knife|more data`

(Github seems to be mangling the double spaces in my example)

**Comment by dyelton** [comment]
@stevenmusumeche I had to deal with this issue as well. My workaround was to set the enclosure to \x00 which is null.
