### ISSUE TITLE
Enable protection against long lines

### ISSUE THREAD

**Issue by GrahamCampbell** [thephpleague/csv#512]
## Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

### Proposal

openspout allows passing a value to the limit in `fgetcsv` which can be used to protect against giant lines in user input files. This is necessary to prevent DDOS attack by forcing the load of say a 1GB long line into memory, when under normal operation, a 1GB file streamed with only each row a few 100 chars would be fine. This can happen via malicious actor, or just user error, such as opening a quote and never closing it.

I am not proposing we directly copy their implementation, but suggesting we do something better, to enable detection of such bad lines and stop their processing and continue, leaving that row partial, ideally we some kind of marker.

## Checks before submitting

* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/thephpleague/csv/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/thephpleague/csv/pulls)
* [x] Tell if you have the option to provide the code for this proposal.
* [x] This issue is about 1 feature proposal and nothing more.
* [x] The issue has a descriptive title. For example: "Add JSON render option".

**Comment by GrahamCampbell** [comment]
It's not exactly clear how to do this, without needing to be able to rewind the stream. We'd have to know if the last character was a newline, to determine if parsing was aborted mid-line.

**Comment by GrahamCampbell** [comment]
Hmmm, even that is actually incorrect. Consider the following file with an fget length set to 5:

```
foo,"
bar"
```

We would incorrectly thing we are done processing the line. 😭

**Comment by nyamsprod** [comment]
I will close this issue as a won't fix because of the argument I put forward.
