### ISSUE TITLE
php version is locked to 8.1, it causes issues with php upgrade to 8.2 or greater

### ISSUE THREAD

**Issue by MdNadimHossain** [thephpleague/csv#515]
## Bug Report

_(Fill in the relevant information below to help triage your issue.)_

| Information | Description |
|--------------|---------|
| Version |  |
| PHP version |  |
| OS Platform |  |

### Summary

The php version for this package is locked to 8.1 and because of that it causes issues during higher php upgrade. In my drupal site, I am using a contrib module which has a dependency on this package. I have updated the platform to use php 8.2, but as this package requires php 8.1, the site only uses php 8.1.26 rather than 8.2

### Standalone code, or other way to reproduce the problem

_(Please complete the text below to help us fix the issue)_

### Expected result

There should be a new release to at least use the php 8.2

### Actual result

_(What is the current (buggy) behavior?)_

## Checks before submitting

* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/thephpleague/csv/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/thephpleague/csv/pulls)
* [x] I have added every step to reproduce the bug.
* [ ] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

**Comment by nyamsprod** [comment]
@MdNadimHossain thanks for using the library. 

Please refers to the package [README](https://github.com/thephpleague/csv/) page to check which version you are using. 

I strongly believe that is issue has nothing to do with the `league/csv` package but with a third party package which requires a specific version of this package, something we as maintainers of the package can do little about.

You should contact that third party package maintainer and ask for an update of their dependencies requirements.

For record the current version of league/csv is developped and tested against all version of PHP including and after PHP8.1.2
