### ISSUE TITLE
Feature request: Trim parsed csv strings

### ISSUE THREAD

**Issue by PetrKaterinak** [thephpleague/csv#517]
## Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

### Proposal

It would be nice to have possibility to automatically trim() parsed strings. Something like
```php
$parsedCsv = \League\Csv\Reader::createFromPath($path, 'r');
$parsedCsv->trimStrings()
```

So I dont need to use this code each time I'm parsing CSVs:
```php
function trimArrayStrings(&$array) {
    foreach ($array as &$value) {
        if (is_array($value)) {
            trimArrayStrings($value); // Recursive call for nested arrays
        } elseif (is_string($value)) {
            $value = trim($value); // Trim the string
        }
    }
}
```

**Comment by nyamsprod** [comment]
The `Reader` has a `addFormatter` method where you can register a callback to format the record before it is accessible by any other mechanism. Nothing prevents you do to something like this.

```php
$reader = Reader::createFromPath($path);
$reader->addFormatter(fn (array $record): array => array_map(trim(...), $record));
foreach (reader as $record) {
// 
}
```

Hope it will help you.

**Comment by PetrKaterinak** [comment]
Thank you, I've searched for trimming input data in documentation and I didn't got this one.

________________________________
