### ISSUE TITLE
Should we add support for property hooks in the package denormalization feature. 

### ISSUE THREAD

**Issue by nyamsprod** [thephpleague/csv#541]
## Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | yes

### Issue

```php
class UserIdentity
{ 
    public function __construct(
        private string $firstName,
        private string $lastName
    ) {
    }
 
    public string $fullName {
        get => $this->firstName . " " . $this->lastName;
        set {
            [$this->firstName, $this->lastName] = explode(' ', $value, 2);
        }
    }
}
```

- How should the deserialization feature works with this class ?

**Comment by nyamsprod** [comment]
Should the Deserialization feature of the package even try to work correctly with a class containing property hook ?

The current Deserialization mechanism is geared toward simple DTO. The moment you add Property hooks or any advanced feature in PHP to your class you are better of using a fully fledge Serializer package and there are many of them in PHP land. So should Property hook even be supported by the feature ?

**Comment by shadowhand** [comment]
@nyamsprod IMO, this package should not try to support advanced deserialization. As you said, there are many other packages available for those use cases.

**Comment by nyamsprod** [comment]
<img width="801" alt="Screenshot 2024-11-14 at 23 08 51" src="https://github.com/user-attachments/assets/64fb1c1c-9cef-4978-8677-68bcc8184806">
Just added this text to the documentation I hope this is explanatory enough. I will close this issue as resolved

**Comment by nyamsprod** [comment]
<img width="695" alt="Screenshot 2024-11-23 at 23 59 36" src="https://github.com/user-attachments/assets/d5b382e0-baeb-41ec-8b95-a3012eef8665">

I am happy to report that the package serializer is able to handle property hook and aviz without having to change a single line of code so my worries are no more I will even probably remove the warning which are false. The feature supports PHP8.4 features without any seen issue.
