### ISSUE TITLE
Default keys for fetchAssoc

### ISSUE THREAD

**Issue by RobinDev** [thephpleague/csv#62]
Hello,

First, thanks for sharing your code.

By default, why don't choose the csv file's first line to set the keys when we are doing a fetchAssoc without keys ?

Actually, we need to do : 

``` php
$csv = Reader::createFromPath(dirname(__FILE__).'/my.csv');

$header = $csv->fetchOne();
$res = $csv->addFilter(function ($row, $index) { return $index > 0; })
                  ->fetchAssoc($header);
```

I will propose a pull-request in a few minuts.

**Comment by CWSpear** [comment]
Does it make sense for the `callable` in the `fetchAssoc` method to pass in the associative array?

i.e. With this CSV:

```csv
name,email,age
Bob,bob@builder.com,12
```

and with this code:

```php
$reader->fetchAssoc(0, function ($row) {
  print_r($row);
});
```

I would expect this output:

```
array
(
  [name] => Bob
  [email] => bob@builder.com
  [age] => 12
)
```

but I actually get this:

```
array
(
  [0] => Bob
  [1] => bob@builder.com
  [2] => 12
)
```

Ultimately, what I'm trying to do, is figure out a way to iterate over a very large CSV file where the first row are the keys. It is large both in number of columns and rows, so I want to take it just one row at a time (like, I really want to do an `each` or via `query`, but in an associative manner so I don't have to manage matching the keys up myself).

It seems like this isn't able to do this at all (and I don't think `fetchAssoc` is gonna do it anyway, cuz I'm going to run into memory issues as it grows...).

Hope I'm making sense...

**Comment by CWSpear** [comment]
I guess I have two issues here, and I re-read what I wrote and it's a bit confusing. In trying to process a large first-row-keys CSV file, I was looking at `fetchAssoc`, and noticed this quirk about the callback. I realize now `fetchAssoc` isn't going to be the answer either way.

**Comment by nyamsprod** [comment]
Hi @CWSpear ,

About `Reader::fetchAssoc`, this is not a quirk but the intended behavior. To understand it you should try to think of `Reader::fetchAssoc` as being similar to the behavior of `PDO::FETCH_ASSOC`. The method returns an array indexed by column name **as returned in your result set**. 
The `$callable` argument is applied on the CSV content before generating the final result set so it is expected that when you do `print_r` in your closure no re-indexation is shown as it has not occurred yet.

IMHO, you should use `Reader::each` or `Reader::query` to achieve what want something like this:

```php
use League\Csv;

$indexes = [
    "first column",
    "second column",
    "third column",
    ...
];
$res = [];
$csv = Reader::createFromPath('/path/to/my/file.csv');
$nb_iterations = $csv->each(function ($row) use ($indexes, &$res) {
    $item = array_combine($indexes, $row);
    //add here your business logic...
    $res[] = $items;
    return true; //required otherwise the loop will stop!
});
```

Hope this will help.

**Comment by CWSpear** [comment]
I was thinking more along the lines of this: https://github.com/surgeforward/csv/commit/d7b6fbd4cc0530c1230eb513d6d7ede955817ebf

That turns this:

```php
$keys = $reader->fetchOne(0);
$reader->each(function ($row, $index) use ($keys) {
    if ($index === 0) {
        return true;
    }

    $row = array_combine($keys, $row);

    echo $row['email'];
}
```

into this:

```php
$reader->eachAssoc(function ($row, $index) {
    echo $row['email'];
}
```

**Comment by nyamsprod** [comment]
Hi @CWSpear 
could you please open another issue related to your needs has this issue has been closed and you seems to need some other features. I'll respond into this new issue
