### ISSUE TITLE
setOffset() is not respected with toHTML()

### ISSUE THREAD

**Issue by hervethouzard** [thephpleague/csv#66]
Hello,

I have a csv file from which I don't want to use the first 3 lines then I want to convert it to an html table.
So I used something like this:

    $inputCsv = Reader::createFromString(.....);
    $inputCsv->setDelimiter("\t");
    $inputCsv->setEncodingFrom("UTF-8");
    $inputCsv->setOffset(3);
    echo $inputCsv->toHTML('table table-striped');

But the generated table contains the first 3 lines of my CSV file.

Bye,
Hervé

**Comment by nyamsprod** [comment]
This is normal behavior all outputting methods are not affected by the extracting methods.

**Comment by nyamsprod** [comment]
But a quick update on the package could allow such behaviour now could mean BC break  also

**Comment by hervethouzard** [comment]
it's a shame if the library is not doing it and could be a good enhancement.
Thanks for your answer.

**Comment by nyamsprod** [comment]
I didn't say the lib wouldn't do it ... I've just implemented it on my local dev. It took me less than 5 min. to do it But it's a BC break for sure.

**Comment by nyamsprod** [comment]
If you download the `dev-master` the feature is now on the package. You can make some feedback on it if you want. **Of note:** the `dev-master` alias is now `7.0-dev`

**Comment by nyamsprod** [comment]
this issue is resolved and will be made public on the next release. Please read the changelog or the documentation for more information

**Comment by hervethouzard** [comment]
Excellent !
Thank you very much
