### ISSUE TITLE
Character replacement

### ISSUE THREAD

**Issue by louposk** [thephpleague/csv#68]
Hello,
i am trying to create some csv fields as the example
```
$data = [
			['"1","name", "surname"'],
			['"2","name", "surname"'],
			['"3","name", "surname"']
		];
```

I want to add each row to a single line but the outlut is the following:
```
"""1"",""name"", ""surname"""
"""2"",""name"", ""surname"""
"""3"",""name"", ""surname"""
```

I want the output to be the following:
```
"1","name","surname"
"2","name","surname"
"3","name","surname"
etc.
```

I get more " than expected.
Am i doing something wrong??

Thanks

**Comment by nyamsprod** [comment]
According the CSV specification enclosure are only needed when space or in case the enclosure character is used inside your cell. When the latter situation is encounter the specification specifies that the enclosure must be double to prevent misinterpretation of the cell content.
In your exemple you are forcing the enclosure on each cell which:

- is **not** require for the CSV to be valid.
- force PHP fputcsv function the addition of a second enclosure character.
