### ISSUE TITLE
can  csv make some elements with a tag?

### ISSUE THREAD

**Issue by joostshao** [thephpleague/csv#69]
the href link to some elements.
when i click the a tag, it will open my broswer and go to the target web site page ??

**Comment by nyamsprod** [comment]
Hi @joostshao 
I don't understand your question. In what context are your talking about ? Can you be more specific ?

**Comment by joostshao** [comment]
![2015-02-11 17 54 29](https://cloud.githubusercontent.com/assets/3615951/6144877/09b542a4-b217-11e4-945e-428d6801d2a8.png)

click the google text, it will open my default browser and locate to google.com

**Comment by nyamsprod** [comment]
What you are asking is out of scope for the library out of the box. I suggest you look at the [reading documentation page](http://csv.thephpleague.com/reading/) Where you will find informations to help you achieve that using for instance the `Reader::fetchAll` method for example.
