### ISSUE TITLE
Extra row with "null" in reader fetchAll result

### ISSUE THREAD

**Issue by teplolog** [thephpleague/csv#70]
Using fetchAll I have extra row with NULL in result.
See following testcase:
```php
<?php
require_once 'vendor/autoload.php';
use League\Csv\Reader;

$reader = Reader::createFromString("a,b".PHP_EOL."3,11");
$result = $reader->fetchAll();
var_export($result);// array(0 =>array (0 => 'a',1 => 'b',),1 =>array (0 => '3',1 => '11',),2 =>array (0 => NULL,),)

```
My environment:
Ubuntu 14.04.1 LTS
PHP 5.5.21-1+deb.sury.org~trusty+2

**Comment by nyamsprod** [comment]
Hi @teplolog,
This bug has been corrected in the coming 7.0 version which should be release next week. In the meantime you can simply do this

```php
require_once 'vendor/autoload.php';
use League\Csv\Reader;

$reader = Reader::createFromString("a,b".PHP_EOL."3,11");
$reader->setFlags(SplFileObject::DROP_NEW_LINE);
$result = $reader->fetchAll();
var_export($result)

**Comment by barroca** [comment]
This issue is still present on 7.0 and 7.1. 
```
array (
  0 => 
  array (
    0 => 'a',
    1 => 'b',
  ),
  1 => 
  array (
    0 => '3',
    1 => '11',
  ),
  2 => 
  array (
    0 => NULL,
  )
```

**Comment by nyamsprod** [comment]
Hi @barroca,
can you provide your PHP/HHVM version please as I fail to reproduce this issue

**Comment by barroca** [comment]
php version 5.6.9, I'm using a vagrant box with CentOS Linux release 7.1.1503

Thanks.

**Comment by nyamsprod** [comment]
okay, I get it ..it's a change in PHP behavior so the result depend on PHP version 
look at this results which mimic what you are experimenting
http://3v4l.org/c56KM
So it's not a package bug per se. Let see what we can do to mitigate this

**Comment by nyamsprod** [comment]
A way to mitigate this changed behaviour is to **NOT** use the `DROP_NEW_LINE` constant. Like this

```php
require_once 'vendor/autoload.php';
use League\Csv\Reader;

$reader = Reader::createFromString("a,b\n3,11");
$reader->setFlags(SplFileObject::READ_AHEAD|SplFileObject::SKIP_EMPTY);
$result = $reader->fetchAll();
var_export($result)
```
like shown here: http://3v4l.org/oqmvp

**Comment by barroca** [comment]
I see, so for now will you keep the package with the same behavior? 

Thank you for the help! :)

**Comment by nyamsprod** [comment]
yes maybe I'll change with a new major version I don't know yet

**Comment by donnykurnia** [comment]
I got the same issue using fetchAssoc. I think this issues should be put into the documentation. I'm parsing 26k rows of data and getting the incorrect reading at the end of process is not a good sign.

**Comment by nyamsprod** [comment]
@donnykurnia [It is documented](http://csv.thephpleague.com/properties/#the-splfileobject-flags) but I'll make it more obvious then. Or better yet do you want it to be documented elsewhere ? you can make a PR I'll review it and update the documentation

**Comment by donnykurnia** [comment]
Hi @nyamsprod 

I missed the flags because I follow the example page: http://csv.thephpleague.com/examples/

I think setting the obvious flags every time is easily missed steps. Why not make the flags as default flag, still let the user change the flags later, but without any flags setting, it will assume the default flags (SplFileObject::READ_AHEAD|SplFileObject::SKIP_EMPTY) ?

**Comment by nyamsprod** [comment]
@donnykurnia agree but doing so would be consider BC Break that's why this issue is stated to be tackle with the 8.0 release when I start working on it see #105

**Comment by donnykurnia** [comment]
Great @nyamsprod 

I'll try to help as much as I can within my spare time.
