### ISSUE TITLE
Build suddenly failing

### ISSUE THREAD

**Issue by snipe** [thephpleague/csv#71]
Hi gang,

I installed last night with `"league/csv": "~7.0"` in my composer.json, and today my builds are failing:

- Installing league/csv (dev-master 0d3c28b)
    Cloning 0d3c28bf20ad26e1e23599e1746aaf7c680c0477
    0d3c28bf20ad26e1e23599e1746aaf7c680c0477 is gone (history was rewritten?)
    Failed to download league/csv from source: Failed to execute git checkout '0d3c28bf20ad26e1e23599e1746aaf7c680c0477' && git reset --hard '0d3c28bf20ad26e1e23599e1746aaf7c680c0477'
fatal: reference is not a tree: 0d3c28bf20ad26e1e23599e1746aaf7c680c0477
    Now trying to download from dist
  - Installing league/csv (dev-master 0d3c28b)
    Downloading: connection...
                                             
  [Composer\Downloader\TransportException]   
  Could not authenticate against github.com  
                                             
Did I screw something up?

**Comment by snipe** [comment]
(I needed 7.0 because it was not parsing my CSV line breaks correctly without `$csv->setNewline("\r\n");` )

**Comment by nyamsprod** [comment]
Hi,
thanks for using the League\Csv. The branch you are currently using is the dev-master branch. So this can happen when some features are not enough stable and I have to make some git stash/rebase. 

I would recommend using the dev-master branch only for testing purpose and not for production code.

The code will be freeze today for release hopefully next week.

**Comment by nyamsprod** [comment]
the stable release of 7.0.0 is out !!
