### ISSUE TITLE
library doesn't support iconv stream filter

### ISSUE THREAD

**Issue by nsitbon** [thephpleague/csv#72]
Hi, I just pulled the latest version of the library and try to integrate it in my application but it fails at the beginning when I do
```php
$stream = Reader::createFromPath('/home/nsitbon/export_members_20150217.csv');

if ($stream->isActiveStreamFilter()) { 
    $stream->appendStreamFilter('convert.iconv.UTF-16/UTF-8//TRANSLIT');
}
```
it throws the following exception : 
> [RuntimeException]
>   SplFileObject::__construct(): unable to create or locate filter "convert.iconv.UTF-16"

whereas this code works perfectly
```php
$stream = fopen('/home/nsitbon/export_members_20150217.csv', 'r');
$stream_filter_append($stream, 'convert.iconv.UTF-16/UTF-8//TRANSLIT', STREAM_FILTER_READ);
```

any ideas?

**Comment by nyamsprod** [comment]
This is a limitation due to poor support from `SplFileObject` of stream filters. There's a [open bug](https://bugs.php.net/bug.php?id=44392) about this and it has not yet been resolve.

**Comment by nyamsprod** [comment]
In the meantime, nothing prevents you from modifying the [FilterTranscode](https://github.com/thephpleague/csv/blob/master/examples/lib/FilterTranscode.php) class to use iconv extension instead. I understand it is frustrating but if this bug was resolved a even more powerful package could be made and It would also remove the need for `isActiveStreamFilter` in the package.

**Comment by nsitbon** [comment]
thanks for your comments, if you can't do anything about that I'll wait for the fix in the SPL.
I spend some time in the documentation but cannot find if this behaviour is documented, can you tell me if there is something about this in the documentation. I'm sure there is nothing in the tests because I checked.

**Comment by nyamsprod** [comment]
Yep there's nothing, a omission from my part. But you can make a pull request against the [gh-pages](https://github.com/thephpleague/csv/blob/gh-pages/filtering.md) branch to add the warning.

**Comment by nyamsprod** [comment]
I've just updated the documentation by adding a warning section on top of the stream filter documentation page.

**Comment by nsitbon** [comment]
thank you much Ignace.

**Comment by zerocrates** [comment]
FYI, the `php://filter` stream filter support *does* appear to work with filters that contain slashes, as long as you percent-encode the slashes, i.e.

`php://filter/read=convert.iconv.UTF-8%2FASCII%2F%2FTRANSLIT/resource=...`

The linked open PHP bug report in the docs and @nyamsprod's earlier comment indicates this *doesn't* work, but it appears that the filter URI support was fixed to `urldecode` filter specifications [back in August 2008](https://bugs.php.net/bug.php?id=43008), a little bit after the still-open bug about exposing the underlying resource was filed.

It might be worth revising the warning in the documentation about this, at least as it relates to iconv filters specifically.

**Comment by nyamsprod** [comment]
@zerocrates you are totally right seems I had overlooked this one. I've just create a PR with the fix in it. This one will be included in the next release :+1:

**Comment by nsitbon** [comment]
That's really cool guys thanks @zerocrates for pointing the fix and thanks @nyamsprod for implementing it ;-)

**Comment by nyamsprod** [comment]
bug fix is merged in master branch

**Comment by mrfinrod** [comment]
I have the same problem.
Exception thrown here
`if($input_bom === Reader::BOM_UTF16_LE || $input_bom === Reader::BOM_UTF16_BE) {
            $reader->appendStreamFilter('convert.iconv.UTF-16/UTF-8');
        }`
What is the solution of the problem?

**Comment by landsman** [comment]
Same problem here ...

**Comment by spagu** [comment]
and here.

**Comment by nyamsprod** [comment]
@spagu could you provide more information as this bug is related to an unsupported version of the library. It would be best to open a new thread with an example so I could investigate your issue.

thanks in advance
