### ISSUE TITLE
UTF-8 support?

### ISSUE THREAD

**Issue by huglester** [thephpleague/csv#74]
Hello,

As I see from docs, utf8 should be supported without problems, but I am hitting some.

I also tried adding at the top of the file: mb_internal_encoding("UTF-8"); (sinse this sometimes helps)

basicly the code is really simple:
```php
        $writer = \League\Csv\Writer::createFromFileObject(new SplTempFileObject());
        $writer->setNewline("\r\n");
        $writer->setEncodingFrom("UTF-8"); // this probably is not needed?
        $headers = ["Title", "Start date", "End date", "Time", "Address", "Place", "Organizer", "Text", "Contact person", "Email", "Phone"];
        $writer->insertOne($headers);

        foreach($items as $item)
        {
            $data = [
                strip_tags($item['title']),
                format_date($item['date_at']),
                format_date($item['expires_at']),
                $item['start_time'],
                $item['address'],
                $item['place'],
                $item['organizer'],
                strip_tags($item['body']),
                $item['user']['full_name'],
                $item['user']['email'],
                $item['user']['phone'],
            ];

            $writer->insertOne($data);
        }

        header('Content-Type: text/csv; charset=UTF-8');
        $filename = 'events-'.format_date(time()).'.csv';

        $writer->output($filename);
```

but what strange I saw, that when I open the file using sublime - I see all those chars, but i.e. opening this file in excel 2014 gives me invalida characters. Any ideas?

Thank you!

**Comment by Heart1010** [comment]
See our discussion about that here on the BOM topic... and imho there is also a summary in the csv doc about BOM http://csv.thephpleague.com/bom/ section "MS Excel on Windows"
```php
$reader->setOutputBOM(Reader::BOM_UTF8);
```

**Comment by Heart1010** [comment]
@nyamsprod Is this ```$reader->``` in the doc ok?!

![auswahl_562](https://cloud.githubusercontent.com/assets/1481680/6461385/abba9d5a-c19f-11e4-8cd1-bed9acee38d7.png)

**Comment by nyamsprod** [comment]
nope a typo you may fork and fix it :+1:

**Comment by Heart1010** [comment]
you were faster :+1:

**Comment by nyamsprod** [comment]
Yep I think this issue is resolve

**Comment by huglester** [comment]
wow. thanks @Heart1010 it works. Thanks for such a fast response :)

**Comment by Heart1010** [comment]
@nyamsprod when I only want to store a newly generated csv file to the server (with a bom) because I want to add that csv file to a zip archive for example how to do that the best way? Because the bom is only be written when calling the output or the toString method, isn't it?

**Comment by nyamsprod** [comment]
I don't think there's a easier way. 

Of note starting with v7:

* `setNullHandlingMode` does not exist anymore and is not needed to treat `null` as empty
* you could simplify your code as follow:
```php
$writer = Writer::createFromFileObject(new SplTempFileObject());
$writer->setOutputBOM(Reader::BOM_UTF8);
$writer->insertAll($data);
file_put_contents('file.csv', $writer->newReader());
```

**Comment by Heart1010** [comment]
Perfect, thank you :+1:

**Comment by cambur** [comment]
@nyamsprod that was the solution for me after days of testing.
That and compressing the CSV in a Zip, because the problem was also happening when transferring the file from the API to the Front End.
If I store the CSV in the server and open it with Excel it would look good, but if I transfer the same file  from the api to my front end the text was being re-encoded. Zip was the solution.
