### ISSUE TITLE
Should Exceptions be more detailed to make errors more catchable?

### ISSUE THREAD

**Issue by tmoitie** [thephpleague/csv#75]
For example, someone uploaded a CSV with a couple of empty header fields at the end of the CSV, and the following exception was thrown: 
```php
        if (! $this->isValidAssocKeys($res)) {
            throw new InvalidArgumentException(
                'Use a flat non empty array with unique string values'
            );
        }
```
There's not much here that I can differentiate between another InvalidArgumentException other than the message, which I assume is not going to maintain BC?

**Comment by tmoitie** [comment]
If not should I be approaching this problem from a different tack? Should I be validating the first row independently of the library?

**Comment by nyamsprod** [comment]
In your case I would say try to fetch the header first and validate it prior to do fetchAssoc this is the easiest thing to do .. adding more exception classes/level is IMHO not required. Do remember that fetchAssoc also accepts array so this kind of situation should solve itself quite nicely.
