### ISSUE TITLE
Allowed Memory Size Error and Memory Limit

### ISSUE THREAD

**Issue by josoroma** [thephpleague/csv#76]
Using a big file of 75MB we are getting the following error:

Fatal error in module Reader:
Allowed memory size of 134217728 bytes exhausted (tried to allocate 81 bytes)

Now I am going to play with @ini_set('memory_limit', '-1'); and see what happens. PLease let me know if there is something I am missing to improve my query.

Thanks for your time and happy hacking!

This is the same piece of code that works but only using small files:

```php
	public function convertItemsFile($files)
	{
		$itemsFileName = 'items_file.csv';

		$items = $this->fileExists($files, 'shortname', $itemsFileName);

		if ($items) {

			$input = $items[0]['name'];

			$csvItems = Reader::createFromPath($input);

			$headers = $csvItems->fetchOne();

			$dataItems = $csvItems
			    ->setEncodingFrom('UTF-8')
			    ->setDelimiter(',')
			    ->setOffset(1)
			    ->addFilter(array($this,'filterItemsByStyleCodes'))
			    ->fetchAssoc();

			$output = $this->_csvFilesPath . 'vp-' . $items[0]['shortname'];

			@unlink($output);
			touch($output);

			$csvItems = Writer::createFromPath($output);

			$csvItems->insertOne($headers);

			foreach ($dataItems as $row) {

				$csvItems->insertOne([
					$row['company'],
					$row['item-number'],
					$row['description'],
					$row['style-code']
				]);

			}

		}
	}

```

**Comment by nyamsprod** [comment]
you shouldn't use `Reader::fetchAssoc`  as it returns a multidimentional `array`. For big files I would recommend using `Reader::query()` as you directly use an `Iterator` which will use less memory. This is explain in [the documentation](http://csv.thephpleague.com/reading/)

**Comment by josoroma** [comment]
Thank you @nyamsprod

Now I am going to improve my code using Reader::query

Have a nice day!

**Comment by josoroma** [comment]
Sorry but I still dont get it right!

Could you please share an small example?

Thanks.

**Comment by nyamsprod** [comment]
Since I don't know exactly what you are trying to do I can only do something like this. Hope it will help

```php
    public function convertItemsFile($files)
    {
        $itemsFileName = 'items_file.csv';

        $items = $this->fileExists($files, 'shortname', $itemsFileName);

        if (! $items) {
            return;
        }

        $inputCsv = Reader::createFromPath($items[0]['name']);
        $inputCsv->setDelimiter(",");

        $outputCsv = Writer::createFromPath($this->_csvFilesPath.'vp-'.$items[0]['shortname'], 'w');
        $outputCsv->insertOne($inputCsv->fetchOne());

        $inputCsv->setOffset(1);
        $inputCsv->addFilter(array($this,'filterItemsByStyleCodes'));

        $callable = function(array $row) {
            return [
                $row['company'],
                $row['item-number'],
                $row['description'],
                $row['style-code']
            ];
        };

        $outputCsv->insertAll($inputCsv->query($callable));
    }
```

**Comment by josoroma** [comment]
Your example looks very useful!

Thanks!

**Comment by josoroma** [comment]
Update: My first version, using the associative array works nice but only incrementing following values directly in the php.ini:

max_input_time = 60
memory_limit = 512M

safe mode is off. 

Then I tried the code you suggest, using query and a callable method, but the behavior gets worse, running out of memory:

```
	public function convertItemsFileCallable($files)
	{
		$itemsFileName = 'items_file.csv';

		$items = $this->fileExists($files, 'shortname', $itemsFileName);

		if ($items) {
			// echo 'HERE'; die;

			$input = $items[0]['name']; // The absolute path of items_file.csv

			$inputCsv = Reader::createFromPath($input);
			$inputCsv->setEncodingFrom('UTF-8');
			$inputCsv->setDelimiter(",");

			$output = $this->_csvFilesPath . 'vp-' . $items[0]['shortname'];

			@unlink($output);
			touch($output);

			$outputCsv = Writer::createFromPath($output, 'w');

			$headers = $inputCsv->fetchOne();

			$outputCsv->insertOne($headers);

			$inputCsv->setOffset(1);
			$inputCsv->addFilter(array($this,'filterItemsByStyleCodes'));

			$callable = function(array $row) {
				return [
					$row['company'],
					$row['item-number'],
					$row['description'],
					$styleCode
				];
			};

			$outputCsv->insertAll(
				$inputCsv->query($callable)
			);

		}
	}
```

Note: The csv file has 100.000 records.

Thanks for all your previous support @nyamsprod.

**Comment by nyamsprod** [comment]
like I said I don't have enough info to help you out :( . 
 Bottom line:
* I don't get why you are using touch since I used the `w` open mode;
* you should use `Reader::query` because an Iterator will consume less memory that using `Reader::fetchAssoc` which uses internally `iterator_to_array` which is a no goner as all the data is dump into memory for array conversion.
* The callable thingy on the `Reader::query`could be as well drop if your are just "copying" from one CSV to another.
* If you insist in using the callable on the query method the row can not be indexed with names they are indexeb by number since non array combination has taken place (this is a typo from me)
Anyway all of this is explain in the documentation. So I don't see what I can do more
