### ISSUE TITLE
How to create a plain Writer and save content to ".csv" file

### ISSUE THREAD

**Issue by paslandau** [thephpleague/csv#81]
A very common scenario for me is: 

- importing data from various sources
- manipulating data (usually in some sort of array)
- exporting data as CSV file

My first naive approach to accomplish this with this package would look something like this:

````php
$file = "result.csv";
$writer = new Writer();
$data = [/*...*/];
$writer->insertAll($data );
$writer->saveToCsv();
````
Unfortunately this does not seem to be possible at the moment, because 
1. a `Writer` can only be instantiated via `from...` method (right?)
2. there is no method to simply write the data to a file

My workaround looks like this:
````php
$file = "result.csv";
Utility::writeEmptyFile($file);
$writer = Writer::createFromPath($file);
$data = [/*...*/];
$dataAsString = $writer->__toString();
Utility::writeContentToFile($file,$dataAsString);
````
So I'm forced to handle the file processing myself, which I'd really like to avoid. This becomes especially cumbersome when having to deal with different encodings (a problem you've already solved when reading csv files with your stream/filter-implementation). Do you plan on integrating this functionality? If not, why not :)?

Cheers
Pascal
A very common scenario for me is: 

- importing data from various sources (CSV, XML, etc.)
- manipulating data (usually in some sort of array)
- exporting data as CSV file

The last part doesn't seem to be possible right now. My first naive approach to accomplish this with this package would look something like this:

````php
$file = "result.csv";
$writer = new Writer();
$data = [/*...*/];
$writer->insertAll($data);
$writer->saveToCsv();
````
Unfortunately this does not work, because 
1. a `Writer` can only be instantiated via `from...` method (right?)
2. there is no method to simply write the data to a file

My workaround looks like this:
````php
$file = "result.csv";
Utility::createEmptyFile($file);
$writer = Writer::createFromPath($file);
$data = [/*...*/];
$dataAsString = $writer->__toString();
Utility::writeContentToFile($file,$dataAsString);
````
So I'm forced to handle the file processing myself, which I'd really like to avoid. This becomes especially cumbersome when having to deal with different encodings (a problem you've already solved when reading csv files with your stream/filter-implementation). Do you plan on integrating this functionality? If not, why not :)?

Cheers
Pascal

**Comment by nyamsprod** [comment]
Why can't you just do
```php
$csv = League\Csv\Writer::createFromPath("result.csv", "w");
$csv->insertAll($data);
```
By specifying the open mode parameter as detailed [in the documentation](http://csv.thephpleague.com/instantiation/#createfrompathpath-openmode) your destination file is created if PHP is able to create a file in the destination directory. Just like with PHP `fopen` function :)

**Comment by paslandau** [comment]
True.. that solves problem 1 :)
As for the encoding part: I guess http://csv.thephpleague.com/filtering/#example answers the question 
````
Please review the stream filtering example and the attached FilterTranscode Class to understand how to use the filtering mechanism to convert a CSV into another charset.

The FilterTranscode class is not attached to the Library because converting you CSV may depend on the extension you choose, in PHP you can use the following extensions :

    The mbstring
    The iconv
    The intl
````

Although I feel this is kind of a very basic functionality and should be more prominently shown. Especially since I feel that the `setEncodingFrom` method is very misleading as it does not do anything in terms of encoding conversion.

**Comment by nyamsprod** [comment]
Of note starting with version 7.0 nothing prevents you from using the formatter capabilities of the Writer class to transcode your data in another encoding without using the stream filter api.

**Comment by gabidavila** [comment]
So, I did this:

```
       //Cleaning the file
        $file = 'output/region.csv';

        $csv = Writer::createFromPath($file);
        $csv->setDelimiter(";"); //the delimiter will be the tab character
        $csv->setNewline("\r\n"); //use windows line endings for compatibility with some csv libraries
        $csv->setOutputBOM(Writer::BOM_UTF8); //adding the BOM sequence on output

        $csv->insertOne(['region_name', 'state_id_fk']);
        $csv->insertAll($this->getAlldata());

        $csv->output($file);
```

Why still outputs on my terminal? Is there something I am missing?

**Comment by nyamsprod** [comment]
@gabidavila please read the documentation from `Csv::output` method.

**Comment by jcisio** [comment]
FYI, I had the same problem with @gabidavila. The last line is not necesary. And to flush the cache you can use `$csv = NULL`. So, that method is correct, but if you don't have the CSV created, then look elsewhere (permission etc. like `stat(): stat failed for .../file.csv`).

**Comment by abnersouza** [comment]
@gabidavila you saved my life with this 3 lines

```
$csv->setDelimiter(";"); //the delimiter will be the tab character
$csv->setNewline("\r\n"); //use windows line endings for compatibility with some csv libraries
$csv->setOutputBOM(Writer::BOM_UTF8); //adding the BOM sequence on output
```

I was having issue exporting to csv some special chars like ºC or Chinese chars as well. Setting outputBOM save me. Thanks a lot.

**Comment by jonyking** [comment]
Still a problem creating a new csv file from an array. Some suggestions?
