### ISSUE TITLE
Weird encoding issue when reading .csv generated by Google AdWords

### ISSUE THREAD

**Issue by donaldallen** [thephpleague/csv#82]
I have a .csv from Google AdWords that's actually tab-seperated. This is done by default in Google AdWords, not sure why. But when I var_dump() the array, I get a bunch of characters like this:

![Image of Yaktocat](https://www.dropbox.com/s/dbuv98yt0nt3937/Screenshot%202015-03-27%2011.59.32.png?dl=1)

Here is the .csv I'm trying to use:

https://dl.dropboxusercontent.com/u/30874695/Keyword%20Planner%202015-03-27%20at%2011-13-26.csv

Again, this is straight from Google AdWords, and hasn't been opened/saved in Excel. I've confirmed the strings are 'ASCII'. Here's the code I'm using to read the csv:

```php
$reader = Reader::createFromPath($csv_file);
$reader->setFlags(\SplFileObject::READ_AHEAD|\SplFileObject::SKIP_EMPTY);

$detect_delimiter = $reader->detectDelimiterList();
$delimiter = array_shift($detect_delimiter);
$reader->setDelimiter($delimiter);

$data = $reader
    ->setOffset(1)
    ->fetchAssoc($this->csv_headers);

// Remove duplicate entries
$data = array_map('unserialize', array_unique(array_map('serialize', $data)));
```

**Comment by nyamsprod** [comment]
Hi,
thanks for using the league\csv library. The csv you are using in encoded in UTF-16. You should transcode it's content in UTF-8 in order to view correctly your data. You should use the library stream filter capabilities to do this as explained with a concrete example [in the documentation](http://csv.thephpleague.com/filtering/)

**Comment by donaldallen** [comment]
Thank you so much! That worked flawlessly.

**Comment by maurocasas** [comment]
Really sorry to bring this up, but would you mind sharing how you did this?
I'm having a hard time understanding how to transcode from UTF-16 to UTF-8 using Stream Filters.

Thanks!

**Comment by dewelopinweb** [comment]
> Really sorry to bring this up, but would you mind sharing how you did this?
> I'm having a hard time understanding how to transcode from UTF-16 to UTF-8 using Stream Filters.
> 
> Thanks!

Hi!
You need to convert the entire file. When reading in a stream and converting only a phrase, errors will still come out anyway. For example:
`$content = file_get_contents($path_to_csv_file);
$content = mb_convert_encoding($content, "UTF-8", "UTF-16");
file_put_contents($path_to_convert_csv_file, $content);`
