### ISSUE TITLE
Filtering out the BOM

### ISSUE THREAD

**Issue by bogdanghervan** [thephpleague/csv#83]
[The docs](http://csv.thephpleague.com/bom/#getinputbom) say that we should rely on the extracting methods to remove the BOM character while the CSV is read, but that doesn't seem to be the case.

Even though the BOM could be detected, it is not automatically removed, but rather included in the first column read.

I've put together an example here to illustrate what I'm doing:
http://runnable.com/VRYJNJ-c0wNVqTc6/parsing-bom-character-for-php

Am I missing something, or is it really up to the developer to manually remove it?

**Comment by nyamsprod** [comment]
Hi,
thanks for using the package. I'm afraid that yes it is up to the developer to manually remove it. As the  `Reader` can not modify the CSV. you can do that using for instance the callable argument of any `Reader::fetch*` methods.

**Comment by nyamsprod** [comment]
I understand your concern but stripping even a single bite of a CSV document with the `Reader` class is simply not acceptable. As per definition a `Reader` class **should not be allowed** to change the nature of the object it interacts with. So in our case we're left with two options:

- **option 1:** As stated in the documentation. Use the extract methods `$callable` argument to remove them.
- **option 2:**: Re-download your CSV and remove the BOM sequences using the BOM methods.

I understand completely that dealing with BOM sequences can be a pain, but unless we come out with a solution that respect the `Reader` contract. I'm afraid the current behavior will stay.

**Comment by Richtermeister** [comment]
I am not implying that the reader should alter the underlying file it reads. Clearly that would be unacceptable. 

However, just like the reader produces a transformed representation of that file (turning delimited to array, filtering, sorting, limiting, etc) I think it would be a simple matter of registering one more internal filter, to strip the BOM character from the first field of the first row before handing this data back to userland code. As it is the Reader registers several Iterator decorators already, this would just be one more.

**Comment by nyamsprod** [comment]
I see your point but your are mistaking the underlying mechanism. the decorators helps selecting rows, They do not in anyway interacts with them. The only way to remove effectively the BOM sequence is through the use of the `$callable`. But in the current codebase this is not possible maybe you can submit a PR and I'll review it. Like I said I'm open for any solution that do not alter the CSV document.


- This filtering can only occurs throught the use of the callback argument 
Remember that all filters are cleared after each query which means that you'll have to register it every time you filter your document.

**Comment by nyamsprod** [comment]
The next major release (v9.0) will automatically remove the BOM on CSV document read. The patch landed on the master branch.
