### ISSUE TITLE
Memory consumption when writing large files

### ISSUE THREAD

**Issue by paslandau** [thephpleague/csv#84]
Hey,

I came across another problem when attempting to write a large CSV file which is somewhat related to https://github.com/thephpleague/csv/issues/81 

**Code to reproduce**
````php
function writeFile($file, $content){
    $spl = new SplFileObject($file,"w");
    $spl->fwrite($content);
    $spl = null;
}

$writer = Writer::createFromString("");
$cols = 100;
$rows = 1000;
$chars = 100;
$text = implode(" ", array_fill(0, $chars, "a"));
$row = array_fill(0, $cols, $text);
$lines = array_fill(0, $rows, $row);
echo "Using ".memory_get_usage()/(1024*1024)." MB after creating data\n";
$writer->insertAll($lines);
echo "Using ".memory_get_usage()/(1024*1024)." MB after inserting data\n";
$str = $writer->__toString();
echo "Using ".memory_get_usage()/(1024*1024)." MB after converting data to string\n";
writeFile(__DIR__."/test2.csv",$str);
echo "Using ".memory_get_usage()/(1024*1024)." MB after writing data to file\n";
````

**Output**
````
Using 0.60456848144531 MB after creating data
Using 0.60501861572266 MB after inserting data
Using 19.885452270508 MB after converting data to string
Using 19.885543823242 MB after writing data to file
````

As you can see, I need to somehow "get" the CSV content (using `$str = $writer->__toString();`) in order to write it to a .csv file.
The resulting string can be very large which leads to a massive increase in used memory (0.6MB => 19.8MB).

Imho it should be possible to perform chunked (as in line by line) writing, like this:

````php
function writeCsv($file, $lines){
    $spl = new SplFileObject($file,"w");

    foreach ($lines as $line)
    {
        $spl->fputcsv($line);
    }
    $spl = null;
}

$cols = 100;
$rows = 1000;
$chars = 100;
$text = implode(" ", array_fill(0, $chars, "a"));
$row = array_fill(0, $cols, $text);
$lines = array_fill(0, $rows, $row);
echo "Using ".memory_get_usage()/(1024*1024)." MB after creating data\n";
writeCsv(__DIR__."/test3.csv",$lines);
echo "Using ".memory_get_usage()/(1024*1024)." MB after writing data to file\n";
````

**Output**
````
Using 0.37704467773438 MB after creating data
Using 0.37732696533203 MB after writing data to file
````
Since it uses `SplFileObject` internally, one could also use the filter api in order to use a streaming filter (e.g. for encoding conversion). I feel the `Writer` would greatly benefit from an `Writer::writeToFile` method.

Any thoughts on that?

Cheers
Pascal

**Comment by nyamsprod** [comment]
Hi @paslandau ,

Why can't you just write directly to the `test3.csv` file ? That being said there's a easy answer to your problem :) .

```php
function writeFile($file, League\Csv\Writer $writer)
{
    $spl = Writer::createFromPath($file, 'w');
    $spl->insertAll($writer);
    $spl = null;
}
```
I'm sure you'll get a drop in memory usage. And yes since Writer is a iterator you can passed it directly to another Writer object :+1:

**Comment by paslandau** [comment]
Hey @nyamsprod ,
feeling really stupid right now.. but I honestly did not now that `insertAll` will actually write the content to the file. I was always thinking the writer would somehow "internally" store the rows in memory and I'd have to call some sort of method to write it to disk.

To be true, the docs did not really explain my simple use case (writing a csv file to disk) anywhere ;)

Anyway, thanks a lot!
