### ISSUE TITLE
Proposal: Use grunt for registering precommit hooks

### ISSUE THREAD

**Issue by swarajgiri** [thephpleague/csv#89]
We could use grunt to register `precommit` hooks that 
1. Check files for `PSR-2` violations
2. Run phpunit tests

It will allow collaborators to commit only if all the conditions pass. 
Precommit hooks, can however be overridden with `--no-verify` to skip checks.

### Pros 
- Enforce coding conventions. No way of saying, oops i forgot to check.
- Ensure no test cases are broken

### Cons
- Addition of node.js / io.js to the development stack, which will make setting up the dev environment a bit   lengthy.

I will submit a PR if this is approved.

**Comment by nyamsprod** [comment]
Hi,

IMHO this is a bit too much. Personally I'm currently able to do all this without the use of grunt or node.js by setting my text editor to run the tests and checks on saves. I'm using SublimeText for that but I'm sure the same can be done with NetBean, PHPStorm, Zend Studio to name more powerful IDEs. 

I'm sure that if a developer is able to setup correctly a node.js/io.js environment he/she will have no difficulty to set up his/her IDE of choice to do the same.

I think a better place to ask for feedback for you proposition is the [group mailing list](https://groups.google.com/forum/#!forum/thephpleague) as this would also impact all other league projects if accepted.

**Comment by swarajgiri** [comment]
I kind of do the same, in sublime.
Faced the tedious task of replicating the entire environment for an intern who i am trying not to harass :p
Will post it in the groups, closing it here.

Thanks.
