### ISSUE TITLE
[bug?] First cell always contains "<?php"

### ISSUE THREAD

**Issue by panique** [thephpleague/csv#90]
Good morning gentlemen,

I've fighting with this weird bug (?) right now:

**UPDATE:** This seems to be a problem in Yii framework itself, not in thephpleague/csv (as I could reproduce the but by just using PHP's native CSV functions). I'm unsure how to handle this issue now.

### Reproduceable problem

When using Yii framework 2.0.3 and putting out a .csv file created with thephpleague/csv 7.0 in the mosst simple, most cleanest way, exactly like in the examples described, I'm always getting a perfect file, but it has `<?php` in the very first cell and puts the cell's content into double quotes.

**Should be**
`test`

**But is**
`<?php"test"`

**My code (a standard controller in Yii2):**

```
    public function test()
    {
        $writer = Writer::createFromFileObject(new \SplTempFileObject());
        $writer->insertOne(array("test", "", "test2")); // header line
        $writer->insertOne(array("123", "444")); // demo content line
        $writer->output('123.csv');
    }
```

**What I've tried:**
- all the different BOM settings
- all the different Delimiters,, Enclosures, NewLine-settings, Encodings
- rendering the file via header()

**Note:**
- showing the data in a HTML table or as raw data works perfectly
- I'm suspecting something in the Yii framework working "into" the CSV creation

I'm kindly asking for a short look if this could be a real bug or just something on my side.
This is a bug-report, not a help request :)

Cheers

**Comment by nyamsprod** [comment]
Hi @panique 
I think this "bug" should be related to the use of output buffer in Yii. You should look at it.

**Comment by panique** [comment]
@nyamsprod Thanks! For historical reasons, this already seems to be an issue in Yii: https://github.com/yiisoft/yii2/issues/7529

**Comment by panique** [comment]
FYI this is indeed a bug in Yii framework: https://github.com/githubjeka/yii2-rest/issues/3
