### ISSUE TITLE
iterate over fetchAssoc

### ISSUE THREAD

**Issue by Mech7** [thephpleague/csv#94]
I didn't see it but maybe i missed it in the docs, but it would be nice if it was possible to iterate over an associated array from the first line.

something like:

```php
$reader = \League\Csv\Reader::createFromPath('/file.csv');
$reader->setMode(Reader::MODE_ASSOC);
foreach ($reader as $row) {
 // here row will be an array with names fro the header
}
```

**Comment by nyamsprod** [comment]
Hi,

Thanks for using the package, what you are looking for is documented in the [extracting data documentation page](http://csv.thephpleague.com/reading/) using the `Reader::fetchAssoc` method.

```php

$reader = \League\Csv\Reader::createFromPath('/file.csv');
foreach ($reader->fetchAssoc(0) as $row) {
    //here row is an array with names from the first line
}
```

**Comment by Mech7** [comment]
@nyamsprod Yes i saw that one, only this will load one huge array which will cause for memory problems on larger csv, it would be nice if it would just return an iterator with assoc.

**Comment by nyamsprod** [comment]
Understood,

This method was created when PHP 5.5 Generator where not around. I plan to update this behavior in a upcoming release when PHP 5.4 will be EOL. In the meantime you can achieve the same result using `Reader::query` method in association with `Reader::fetchOne`. 

```php
$reader   = \League\Csv\Reader::createFromPath('/file.csv');
$header   = $reader->fetchOne();
$iterator = $reader->setOffset(1)->query(function($row) use ($header) {
	return array_combine($header, $row);
});

//you are using an iterator so the memory usage shouldn't be a issue anymore
foreach ($iterator as $row) {
    //here row is an array with names from the first line
}
```
This is a crude example of an alternative but I'm sure you get the idea. When `Reader::fetchAssoc` will be updated then this code can easily be remove or updated.

**Comment by curtisgibby** [comment]
It would be nice to have this example in the docs.

**Comment by itjunkii83** [comment]
I am using the above code and it is making an array with spaces added to the end of each key - I verified the CSV does not have a space - also I can't seem to access value when using the key.

[﻿Tracking ID ] => 724423122750

Any Idea where I am going wrong?

**Comment by alexdesignworks** [comment]
@nyamsprod The fact that this method works differently based not only on the type of the first argument, but also whether it is provided or not, makes it really confusing to use. TBH, I've rarely seen such behaviour controlled by one argument. 

I was expecting a behaviour like this: if not provided = defaults to `0` and retrieves the header, if array - maps keys from array. But I would never expect it to return an IteratorMap.

I'm not sure what can be done, but it is really confusing.

**Comment by nyamsprod** [comment]
@alexdesignworks This is why this method is being removed in the [next major release](http://csv.thephpleague.com/upgrading/9.0/#readerfetchassoc-is-removed)
