### ISSUE TITLE
change development workflow to PRs

### ISSUE THREAD

**Issue by cordoval** [thephpleague/csv#97]
currently commits are being pushed to master directly
would help a lot to follow your work on this package to create PRs even if you are the top lead or maintainer, this is how it is done in FOSS. I respect your decision if you ignore this request though it would be a great deal of help to get PR notifications and help review contributing.

Thank you

**Comment by nyamsprod** [comment]
I'm not promising I'll do it right away but I'll try for futur contribution

**Comment by cordoval** [comment]
yeah and thanks again for your work man :+1:
