### ISSUE TITLE
also any chance ) of getting a tag for latest master?

### ISSUE THREAD

**Issue by cordoval** [thephpleague/csv#98]
thanks

**Comment by nyamsprod** [comment]
the master is tag/alias as 7.1.x-dev on packagist

**Comment by cordoval** [comment]
@nyamsprod thanks for your hard work, no need for a big release, our request is for at least a minor number.

**Comment by nyamsprod** [comment]
@cordoval  sorry but I don't understand your request :(

**Comment by cordoval** [comment]
i think perhaps what i was asking earlier was about a bump to 7.0.2 if you consider it right

**Comment by nyamsprod** [comment]
@cordoval The master was about to be tagged and release as 7.1 because a new method has been added to the package but in the meantime bug #55 was reported so depending on its resolution I'm delaying the 7.1 release

**Comment by cordoval** [comment]
again i am not asking for 7.1

**Comment by nyamsprod** [comment]
@cordoval version 7.1 is released
